### ISSUE TITLE
String ERANGE errors with persona voice files with long names

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1029]
This bug was found right in the middle of a long BP mission, so I did my best to recreate the exact circumstances it occurred there.

Please see this mod for a reproducible test case:
 https://drive.google.com/file/d/0B_q0tkX7VcSaY0FUbjliTXFWcjg/view?usp=sharing

Run message.fs2, call in Delta reinforcement wing, and order them to attack the Shivan ship. The game should crash.

The full error you should see is:

`Error: ERANGE: String error. Please Report.
Trying to put into 32 byte buffer:
.ogg`

The filename being played, uef3fleetfattackdesperate.ogg, only has 29 characters with the extension. Looking inside Vis Studio, there's a null terminator replacing the first character of the filename that its trying to process. So the string becomes "\0ef3fleetfattackdesperate.ogg.og"

It seems this only occurs when the voice file is in voice/personas. I had tried putting this in just sounds at first and it didn't crash.

I leave this in anyone's capable hands. :)

(Shout out to Cobra for originally finding this)

**Comment by niffiwan** [comment]
note the obvious candidate (31ebefefe158fc73086efa19a8a9f205938f374d) doesn't seem to be the cause as Axem reverted it and the bug remained; probably needs a bisect to figure out the commit. Seems to have been introduced between 5th Oct & 10th Oct.

**Comment by MageKing17** [comment]
Well, that commit obviously can't be the issue because the ERANGE is from `strcat_s()`, not `strcpy_s()`. Not that using unsafe concatenation would be *better*.

This is half table issue (in that specifying the filename without the extension would remove the error) and half code issue (in that the code really should return the extension-stripped version back to the code that wants to concatenate the actually-found extension back on).

**Comment by AxemP** [comment]
![222](https://cloud.githubusercontent.com/assets/6625164/19296490/8c99df44-9001-11e6-807c-a38366d1e038.png)

Oops I forgot this call stack too.

**Comment by MageKing17** [comment]
So, `WaveFile::Open()` was written with the assumption that, if `keep_ext` is false, the extension will already have been stripped off. The code to parse a message makes no attempt to strip the extension, so obviously that prerequisite isn't being met.

Personally, I think the correct fix here is to make `WaveFile::Open()` strip the extension if needed rather than trying to guarantee none of its callers supply a filename with an extension without caring what the extension is.

**Comment by asarium** [comment]
I can reproduce this with the test mod Axem provided and I'll try to find a solution soon. I agree with @MageKing17 that the function should probably strip the filename since setting a variable with the name `keep_ext` to `false` implies that the extension will be removed by the function.

@AxemP Thank you very much for providing the test mission. Cobra also reported this bug but I could never reproduce it. Test missions like this are incredibly helpful for fixing bugs.
FYI, the mod doesn't work on Linux since the "missions" folder starts with an upper case letter and the file system on Linux is case sensitive so FSO won't find that folder. It's easy to fix here but for mod releases it might be a bit annoying. I'll try to find a solution for this so that FSO shows a warning if such a case mismatch is encountered.
