### ISSUE TITLE
RTT HUD gauges broken with TTF fonts

### ISSUE THREAD

**Issue by WoolieWool** [scp-fs2open/fs2open.github.com#1038]
(duplicated from Mantis #0003185)
Text elements of render-to-texture gauges used with a cockpit model break when used with truetype fonts. The text may display in the wrong place, upside down, backwards, as garbage, or not at all. I have created a demonstration mod that shows off this issue. This is a modification of fightermedic's cockpit mod that replaces font01.vf with a TTF of Bank Gothic. You will see no text on the cockpit gauges when you load any mission (this mod runs off of MediaVPs 2014 and works with retail missions). Removing the fonts.tbl, which defines the truetype font in place of font01.vf, makes everything display correctly.

Download here: https://www.sendspace.com/file/ev2bhb

**Comment by asarium** [comment]
The mod you uploaded has some serious issues. Please fix those and then I can take a look at the bug since these issues could cause the issues you described.

**Comment by niffiwan** [comment]
Try this one; I think I've cleaned up all the warnings (except for 3D sounds). Unpacked the cockpit mod in order to fix various things.
http://www.mediafire.com/file/vahzrvlkj53tx7n/cnbmk2.7z

Also note; there seems to be something odd occurring with the pilot select screen cursor (when entering a new pilots name). With the mod loaded, the cursor was top left of screen. With just mediavps loaded; there didn't seem to be any cursor at all, so... ¯\_(ツ)_/¯

**Comment by asarium** [comment]
Thank you for fixing the mod, I can reproduce the bug now. The text gets rendered to the texture but it's in the wrong location so there seems to be an issue with how the render location is determined, probably something I missed when I added the TTF rendering.
