### ISSUE TITLE
FR: New/Better "Mouselook" Controls

### ISSUE THREAD

**Issue by WoolieWool** [scp-fs2open/fs2open.github.com#1045]
This proposal would allow the player to be able to set up the mouse to move the camera instead of steer the ship, in a similar way to how it can be used in flight sims such as Il-2 Sturmovik. This would allow players without head tracking to be able to easily look around the cockpit (if playing a mod with cockpits) or look to the sides and/or rear to see things that would otherwise be out of view, with much more finesse and control than a hat switch.

**Comment by asarium** [comment]
AFAIK, this is already supported. @z64555 recently added the freelook code which allows to do this but I don't know how to enable it.

**Comment by asarium** [comment]
I just checked this and there is an option in the controls settings called "Free Lock View". I have it bound to Numpad 0 and when I press that I can look around the cockpit using the normal flying controls.

**Comment by z64555** [comment]
Freelook is a feature of the original FS2 source, which was broken for a time when Swifty was implementing the head tracking stuff. I revived it, it got killed during antipodes merge, and I recently revived it again.

When in Freelook mode, the engine will take pitch and yaw controls (which are normally applied to controlling the craft) and gimble the pilot's virtual head.

Before I close this issue, is there anything wrong with Freelook, or do you have some suggestions on its improvement?

**Comment by WoolieWool** [comment]
Having figured it out, there are two things that could seriously improve it:
1. Making an option to enable it permanently for the mouse instead of holding KP0, so you can look around while flying, and another option to make it not snap back instantly when you stop moving the mouse.
2. Making the sweep speed with the mouse much faster, so it's like looking around in an FPS (you "point" instead of "steer" the head).
These would make it much more usable and efficient.

**Comment by z64555** [comment]
It would be possible to add a new control that would toggle freelook on/off instead of hte default "on while pressed" control.

The gimble/slew speed from the mouse is set from the mouse's sensitivity. If this were to be seperated it would require finagling on the controls GUI, or otherwise set to some speed that the player cannot adjust.

**Comment by JohnAFernandez** [comment]
Having to push this to 21.4 as this is a feature.

**Comment by z64555** [comment]
Pushing to 22.2 due to being a feature dependent on Controls5 but not part of Controls5 original agenda

**Comment by z64555** [comment]
I want to do a bit of cleanup/refactoring the way the viewmodes are done.  Currently they're stored in a bitfield and the actual view mode behavior is acted upon certain combinations of bits.

...Which isn't a great way about doing it since there's a number of view modes with a confusing combination.  I want to instead convert them into enum classes so it would not only be easier to do the logic (currently have to do nested if's or a specific bit mask each time) but it would be easier to understand.

**Comment by JohnAFernandez** [comment]
This did not make the feature freeze, and so is being pushed back to 23.2

**Comment by z64555** [comment]
Issue split into #2996 and #4480
