### ISSUE TITLE
Proposal: fire-turret sexp

### ISSUE THREAD

**Issue by WoolieWool** [scp-fs2open/fs2open.github.com#1062]
This sexp would work exactly the same as fire-beam, but would be used to fire a normal turret instead. This would allow precise control of heavy non-beam turrets like railguns, mass drivers, torpedo launchers, etc.

**Comment by asarium** [comment]
As far as I know, the reason this doesn't exist yet is that before firing the turret it needs to be aimed at the target which may take some time so it's not easy to implement with SEXPs. However, I added the required functionality to the scripting API some time ago so you could write a script that aims and fires the turret and then call that script from a SEXP.

**Comment by WoolieWool** [comment]
But don't beam turrets on multiparts like the Orion's frontal beam need to be aimed too, and regular turrets that are not on multiparts likewise wouldn't need to be aimed?

**Comment by asarium** [comment]
I don't know the specifics of the code but AFAIK the fire-beam SEXP just ignores the multi-part nature of the turret and fires the beam directly.

**Comment by wookieejedi** [comment]
To update this discussion, there is a script which does this, but it doesn't quite work as expected for single part turrets. My guess is because if the ship is not in the fov for the single part turret then it will forget the target, but then because turret.Target = ship was called it turns off auto targeting. As opposed to a multi part that will try and move and search for it

**Comment by RhymesHLP** [comment]
Reiterating the need for this because this is a significant hurdle for balancing capship-heavy missions.

**Comment by Goober5000** [comment]
I actually tried coding a `fire-turret` sexp *years* ago.  It turns out it was more complicated than it looked.  That doesn't mean it's impossible, just that it involved more moving parts than I wanted to deal with at the time.

**Comment by wookieejedi** [comment]
Indeed... In thinking about/reviewing the current the code I think the best way to make an easier PR and still get a good amount of use would be a `set-unset-turret-target` sexp. This would allow the FREDer to get pretty close to the behavior they might want (ie telling which ships to fire at what) but would be much easier to code and hence more likely to actually get done.

**Comment by asarium** [comment]
In my opinion, if something is feasible to be implemented with scripting then it should be implemented that way and exposed to FRED via a scripting SEXP. That way the SCP does not have to deal with keeping backwards compatibility for two APIs (SEXPs and Lua) and the scripting API is possibly extended to more use cases which could be useful in the future.

**Comment by Baezon** [comment]
I'd like to mention that I disagree. Given the clearly very large demand for this in sexp form and the _significantly_ higher barrier to entry and overhead involved with scripting I think a sexp implementation is sorely needed. This very situation has resulted in FREDders using hacky workarounds like 'turret-pretend-to-fire' a clearly undesirable result!

I mention mostly because I've already implemented a sexp 'forced-target' for turrets ( which notably differs from the scripting implementation in that scripting version can easily lose its target requiring more overhead in order to reacquire it) which id like to merge after the stable.

**Comment by Baezon** [comment]
Given the described issues with a literal 'fire-turret' SEXP, and the addition of turret-set-forced-target I think this can be closed.
