### ISSUE TITLE
Text cursor no longer appears

### ISSUE THREAD

**Issue by Yarn366** [scp-fs2open/fs2open.github.com#1141]
The OpenGL Core merge (edecb1ca7320c914be6fe450cc3e7753e8ee957f) broke the text cursor that appears when player is supposed to type something--for example, to enter a name for a new pilot. (The cursor graphic is ~~the third special character in the main font, the same one used for the weapons gauge~~ cursor1.ani.) The bug was introduced either in the first commit of that branch that I could compile (2022f6a792efa38538053a04b9f40c5ef4fc28f1) or earlier in that branch.

**Comment by asarium** [comment]
Do you know where the cursor is drawn? I found something in `UI_INPUTBOX` but that uses an animation and not a special character.

**Comment by Yarn366** [comment]
Yeah, it actually is an animation: cursor1.ani, specifically. (I really should have check that before posting this report.)

And no, I don't know what part of the code draws the cursor (but a search for `cursor1.ani` should reveal it).

**Comment by MageKing17** [comment]
Took a look at this and couldn't find out why it wasn't working. I stepped through with a debugger and everything seems, at first glance, to be doing exactly what it's supposed to do; there's just no visible result on my screen. `gr_bitmap()` can't be broken in general, or we'd see way more problems than this, so there's got to be some kind of unintended consequence added as a result of some changes made in the transition to OpenGL Core... the problem is that that's a lot of changes, almost all of which I don't really understand. :/

**Comment by Yarn366** [comment]
Found the problem: `gr_bitmap` isn't obeying clip offsets. In the call to that function that draws the cursor (near the end of `UI_INPUTBOX::draw()`), if I add `gr_screen.offset_x_unscaled` and `gr_screen.offset_y_unscaled` to their respective coordinates and change `GR_RESIZE_MENU_NO_OFFSET` to `GR_RESIZE_MENU`, the cursor works properly.

**Comment by asarium** [comment]
@Yarn366 Great find! The clip offset was previously handled inside the graphics code but since @SamuelCho refactored that to a more general primitive rendering interface, the offset doesn't get added anymore.

I changed the gr_bitmap code so that it adds the correct offset but the cursor still doesn't show up. I think this is the cause of this bug but I'll need to do some additional debugging to fix this.

**Comment by MageKing17** [comment]
> Found the problem: `gr_bitmap` isn't obeying clip offsets.

How is that not causing problems in the other parts of the code that also combine `gr_set_clip` and `gr_bitmap` (and there are several)?

**Comment by SamuelCho** [comment]
gr_bitmap used to use gr_tmapper/gr_opengl_tmapper which piped into opengl_draw_primitives. That function took all the verts submitted to it, then manually added a gr_screen.offset_x and gr_screen.offset_y to all the verts. It was really messy. 

We might have to had another affine transformation to the model view matrix to account for that missing translation.

**Comment by Yarn366** [comment]
@asarium How were you adding the offsets? I tried adding `gr_screen.offset_x` to the X vertices and `gr_screen.offset_y` to the Y vertices, and the cursor showed up. (The coordinates are scaled before that part of the function, so you would have to add the scaled offsets rather than the unscaled offsets.)

**Comment by MageKing17** [comment]
Maybe you should post your diff (or upload it to a branch and link that)?

**Comment by asarium** [comment]
@Yarn366 I am currently trying this code:
```c++
auto do_resize = gr_resize_screen_posf(&x, &y, &w, &h, resize_mode);

x += ((do_resize) ? gr_screen.offset_x : gr_screen.offset_x_unscaled);
y += ((do_resize) ? gr_screen.offset_y : gr_screen.offset_y_unscaled);
```

This is similar to how the other code does it but now the cursor is too far right.

**Comment by Yarn366** [comment]
@asarium If I remove the existing call to `gr_resize_screen_posf` and its `if` statement, and then add your code in its place, the cursor works.

Here's a diff showing what I changed (in `gr_bitmap`):
```diff
 code/graphics/2d.cpp | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/code/graphics/2d.cpp b/code/graphics/2d.cpp
index c913b8024..4038eb905 100644
--- a/code/graphics/2d.cpp
+++ b/code/graphics/2d.cpp
@@ -1270,10 +1270,10 @@ void gr_bitmap(int _x, int _y, int resize_mode)
 	w = i2fl(_w);
 	h = i2fl(_h);
 
-	// I will tidy this up later - RT
-	if ( resize_mode != GR_RESIZE_NONE && (gr_screen.custom_size || (gr_screen.rendering_to_texture != -1)) ) {
-		gr_resize_screen_posf(&x, &y, &w, &h, resize_mode);
-	}
+	auto do_resize = gr_resize_screen_posf(&x, &y, &w, &h, resize_mode);
+
+	x += ((do_resize) ? gr_screen.offset_x : gr_screen.offset_x_unscaled);
+	y += ((do_resize) ? gr_screen.offset_y : gr_screen.offset_y_unscaled);
 
 	memset(verts, 0, sizeof(verts));
```

**Comment by MageKing17** [comment]
Okay, yeah, I can confirm that makes the cursor work again (in exactly the same position it is in 3.7.4). I'm just surprised it doesn't appear to have impacted anything else, since this is not the only place in the code where `gr_set_clip()` and `gr_bitmap()` are used together.

**Comment by asarium** [comment]
The patch from @Yarn366 seems to be working fine for me. However, the `gr_bitmap` call needs to use `GR_RESIZE_MENU_NO_OFFSET` which is odd since it implies that using a clip region somehow alters how the resizing functions work. I think that the changes from above should be enough to fix this but we'll have to keep in mind that something may be wrong with the resizing functions

**Comment by asarium** [comment]
@Yarn366 Your changes seem to be working fine for me. Do you want to submit them in a pull request?

**Comment by Yarn366** [comment]
I searched the code for instances of calls to `gr_set_clip` that use non-zero offsets and menu resizing, followed by calls to `gr_bitmap`. The only such instances that I found (besides the cursor) were in the functions `weapon_select_do` and `wl_render_icon`, both of which are in missionweaponchoice.cpp. Both instances require `wl_icon_info.laser_bmap` to be set to something other than -1; however, that variable is only ever set to -1, making those instances unreachable.

Anyway, I'll submit the PR shortly.
