### ISSUE TITLE
F4 log timer doesn't display the correct mission time.

### ISSUE THREAD

**Issue by FrikgFeek** [scp-fs2open/fs2open.github.com#1142]
The F4 log has been switched to a Minute: Second-Second: Centisecond-Centisecond format from H:MM:SS but centiseconds roll over at 60 causing every second in the timer to last 0.6 seconds.

This causes the F4 log timer to accelerate ahead of the mission timer and since there is only one minute digit it rolls over to 0:00:00 after 6 minutes of game time.

**Comment by MageKing17** [comment]
Huh. I really thought I commented on this issue, but I guess I must've accidentally closed the browser tab before posting it. Basically, during @asarium's [TrueType PR](https://github.com/scp-fs2open/fs2open.github.com/pull/692) `gr_print_timestamp()` got moved from the no-longer-extant /code/graphics/font.cpp to /code/graphics/2d.cpp, and rewritten in the process. The problem is that the new version expects timestamps to be milliseconds, when Missiontime is in 65536ths of a second. Simple enough fix, which PR #1143 provides.
