### ISSUE TITLE
Make code library a shared library

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1165]
Currently, the "code" library of FSO is a static library that is either linked to FSO or FRED (or wxFRED). That means that every executable has their own version of this code contained in them. If the code library would be converted into a shared library then all external executables could share the same library which would reduce the download size of the engine builds. It would also allow to use a few useful features of MSVC such as minimal rebuild or incremental linking which is only available for DLLs or executables.

Since shared linking has some special requirements there are a few changes that will need to be made to the code. Most of the work that needs to be done is moving code out of `freespace.cpp` that is used in the code library. There would be no functional changes to the engine since everything should work as before.

Thoughts?

**Comment by z64555** [comment]
Where exactly would the savings in download size come from? This is a sound theory, but if the bulk of the engine is held within code.lib, then the changes in download size would be minimal.

**Comment by asarium** [comment]
Static linking means that the linker takes the compiled code (in our case `code.lib`) and then combines that with the rest of the code to produce a single, executable file. That means that the code from `code.lib` will be present in every executable that it links to. Dynamic linking produces a single file that contains the code and then every executable uses the same file instead of their own copy.

**Comment by z64555** [comment]
Ok, that'll definitely reduce the combined size of FSO and FRED, as well as any other tools in the future that may use the codebase.

Next question will be: What items/modules should be moved into the code.dll, and which ones should be kept in FSO, FRED?

One of wxFRED's designs is to rely on a front-end/back-end paradigm, where the GUI elements interaction is separate from functions and modules that do "the actual work" of creating the mission. Would a similar paradigm be used here, or should a different paradigm be sought after?

**Comment by asarium** [comment]
`code.dll/.so` will only contain the "engine" code. The code that actually controls how the frame gets drawn and simulated should be located in the FSO executable. FRED and wxFRED would work similarly where they would implement the UI and mission creation code and only use the code library to do the stuff that is specific to the engine.

**Comment by chief1983** [comment]
So, thought about this some more, and wondered what to do about having multiple copies of the engine around.  Currently all the binaries themelves only use external libraries as dependencies that are developed outside of our game.  But the game itself would need to always ensure the engine is run with the right library.  This would be easy on Mac, where everything is bundled, but not so much on Linux/Windows.  It also doesn't get us the space savings on Mac, since as stated, everything is bundled.  We would still be taking these objects and placing them inside the .app, so if we get wxFred going too, they would have to be copied within its own .app.  The only other option on that platform would be a Framework.  Honestly, the more I think about this, the more I feel we're opening ourselves up for DLL hell.  Not sure the space savings on some platforms are worth the logistics nightmare that could ensue trying to figure out how to keep executables and libraries correctly grouped together.

At best, I could see us putting the internal libraries inside a folder named with the same scheme as the executable, so that would include the version, date, whatever was configured.  But even that still seems like a logistics headache.

We also link numerous other objects into the executable too right?  All the image libraries I believe?  Doing that every build for both Fred and FS2 is also eating up space that could be saved.  But in that case we would be better to just rely on platform shared libraries or distributing them alongside like we are with other third party libs now.  But we've previously decided the space savings aren't worth the logistics headache.

**Comment by z64555** [comment]
Hey, when did "we" decide the space savings aren't worth the headache? :P 

But yeah, .lib is really easy for developers to work with compared to .dll's: Just build it and go.

**Comment by MageKing17** [comment]
> Hey, when did "we" decide the space savings aren't worth the headache? :P 

It's always a matter of cost-vs-benefit; we already stopped distributing full-blown debug builds and PDB files, which were the biggest space hogs (well, except they compressed pretty well, so download sizes didn't shrink as much as space taken up in the FS2 folder decreased). How much would this decrease filesizes, how much would it make an already-confusing codebase more confusing, and how much of a performance impact would it have? These are all questions I'd like to have answers to before we make any kind of change like this.

Also, since downloads have started being hosted on bintray, I'm not sure download size matters all that much anymore, beyond making sure it doesn't skyrocket so people on slower connections don't have to spend all day just downloading a single build...

**Comment by chief1983** [comment]
"We" is probably the SCP before even I joined, although I do remember this topic coming up several times way back when.

**Comment by TheMatthew** [comment]
Would the code in the library be all newer code? I am wondering if this means the code could be licensed under a license that prevents indemnification, which is not a bad thing. Then again, I am not yet scp.

An advantage I did not see being mentioned here about the dll/so would be that it will avoid having fred and the game that are different versions by mistake as the logic is common in the core.

**Comment by z64555** [comment]
> @chief1983 
> "We" is probably the SCP before even I joined, although I do remember this topic coming up several times way back when.

Ah, gotcha.

> @TheMatthew 
> Would the code in the library be all newer code?

No, it would still be same some code that's there, with some changes here and there as necessary. And no, the codebase would still be under the original Volition license and everything that's mixed in there currently, so more restrictive licenses (GPL) remain a no-go.

**Comment by Goober5000** [comment]
Eugh.  I agree with others; the marginal space savings aren't worth the massive logistics headache.

**Comment by asarium** [comment]
I'm going to continue to convert the code but if you really want to close this issue you can do that.

However, I have found another reason to do this conversion. If code is a dynamic library we can expose a C-API from it and use that to do the launcher communication instead of relying on the current binary interface. That would make the interaction more robust and we could even expand the API to provide access to other things, e.g. table data.

**Comment by z64555** [comment]
Nah, we should leave the discussion open for a while longer, in case we missed a arguing points for either action.

**Comment by chief1983** [comment]
I see a benefit here, but I think the time for it would be when we have an installer/launcher that can better manage the binary installation for us.  I see there are benefits but I still think the headache introduced by having to keep copying/renaming your code.dll on top of everything else isn't going to be worth it.  How would you even go about having multiple ones installed?  The only way I see it working is if we have the code.dll file also be renamed along with the binaries themselves.  Then it _might_ be feasible now.  I just rather would have seen us with a better management system for all of this even before we introduced all these other DLL dependencies into the build system.  How long until we have an issue with those DLLs where we can't have two different FSO versions alongside each other because their dependencies conflict?

**Comment by asarium** [comment]
To address your first point, the code library would obviously named similarly to how the executables are named already.

The second point has been discussed before. With 3.8 it should be possible to put the executables into their own subfolders since the engine no longer requires that the executable file is located at the root of the installation. A launcher should be able to launch FSO now by simply setting the working directory to the FS2 root and then launching the executable, wherever that file may be located. ngld and I discussed such a system when designing the new mod management system but it hasn't been implemented yet.

**Comment by chief1983** [comment]
Good to hear, I just don't want to keep putting the cart before the horse with even more binary confusion on the part of the end user, and developer alike.  But since Nebula/Knossos development seems to be picking up again maybe this will become a solved problem after all.  I'm all for it as long as the introduced headaches are minimal.

**Comment by Goober5000** [comment]
We haven't had a very good track record of avoiding headaches.  Even the CMake conversion, which was thoroughly tested with regards to generating solution files without errors, still introduces the massive inconvenience of requiring a complete solution rebuild whenever I pull a git update.  I'm not persuaded that the feature is worth the significant hassle it created.

This proposal has the potential for even bigger downsides.  @chief1983 already mentioned the potential for two shared code libraries to conflict with one another.  What if a git bisect just happened to require comparing two conflicting builds?  Debugging would be a nightmare.

Shared libraries are only practical when the shared library is updated rarely compared to the build that uses it.  In the case of the code library, we update it literally every time we release a new build.  That's insane.

This ticket is a solution in search of a problem.  There are only three reasons to use a shared library and all of them are toothless:
1. Saving space or bandwidth - Space is cheap.  Bandwidth for an EXE is cheap compared to a mod.
2. Better integration with the launcher - We already have launcher integration that works pretty well.  This would provide only a marginal improvement and there are many areas of the code that need improvement much more than this.
3. Better integration with future tools - This is nebulous and speculative.  And we already have solutions like exporting sexp data that could very easily be extended to table data.

The more I think about this proposal the more strongly I feel that it should not be done.

**Comment by asarium** [comment]
> We haven't had a very good track record of avoiding headaches. Even the CMake conversion, which was thoroughly tested with regards to generating solution files without errors, still introduces the massive inconvenience of requiring a complete solution rebuild whenever I pull a git update. I'm not persuaded that the feature is worth the significant hassle it created.

Then you probably never had to actually *edit* the build system or else you would know that it was unmaintable before the CMake switch. The occasional rebuilds are only required since the CMake code is still being fixed as new issues are found.

Re: the rest:

Making the code library shared is not my primary goal but instead I would like to decouple the code in the "code" library and the code in the Freespace2 target. It would clean up the interaction between the different parts of the code and would allow to develop new executable targets without having to include a ton of "stub" functions.

Making code a shared library is just something that would be possible once that is done and you do raise good point against that specific part of this discussion.

**Comment by chief1983** [comment]
I'll admit I'm still on the fence about this particular feature, but as for CMake, I _did_ edit the build system quite a bit, and while it might have been a bit of a headache to maintain numerous project files for multiple platforms, they worked.  Meanwhile, we still have unresolved bugs originating from the CMake conversion on the Mac platform.  CMake does make it easier to make file additions and removals, but we still don't have it working as well as what we had before.  And it's been almost a year later.  We've learned a lot about what made it work before in the process of fixing these issues, sure, but it's cost a lot of effort that possibly could have been focused elsewhere.  I'm not sure that other features would have been implementable without it though, as easily as they were, so maybe it is a win in the long run.

I am all for the decoupling, as I have said before, I'd like to see many of our objects within code decoupled from one another, if not for the ability to make individual shared libs out of them, at least to aid in better testing against them.  The same benefits from decoupling code from freespace/fred could often apply to decoupling our numerous objects from one another.  But I think that decoupling code is an obvious first step toward that end, so I support whatever changes are necessary to make that happen, at least virtually, if not as a shared lib.

**Comment by asarium** [comment]
At least for me, CMake is what made it possible for me to add most of the features I added since it was merged. Without it, I probably wouldn't have bothered with developing those features at all. Additionally, I would be doing next to no development without CMake since I use CLion for FSO development on Linux which currently only supports CMake.

**Comment by MageKing17** [comment]
Even when cmake rebuilds my project files (which is *not* every time I update the git repo), the actual builds done after that are not complete rebuilds, so I don't see any time loss there.

**Comment by Goober5000** [comment]
> Then you probably never had to actually *edit* the build system or else you would know that it was unmaintable before the CMake switch. The occasional rebuilds are only required since the CMake code is still being fixed as new issues are found.

I've literally been on the SCP for over a decade and I edited the project files on many occasions.  At one point I was maintaining three separate sets of files: Visual Studio 6, Visual Studio 2005, and Visual Studio 2013.  I can't speak for Mac or Linux, but as far as Windows was concerned it was always a mundane and straightforward process.

Building might have been fixed in the past month or so, but there was a period of time circa December when I was pulling git updates every few days, and each time it happened CMake insisted that every single project in the solution was outdated and needed to be refreshed.  After each project was refreshed it would be entirely rebuilt.  Occasionally, CMake would build the entire solution, invalidate all the projects, and then build the entire solution AGAIN.

> Making the code library shared is not my primary goal but instead I would like to decouple the code in the "code" library and the code in the Freespace2 target. It would clean up the interaction between the different parts of the code and would allow to develop new executable targets without having to include a ton of "stub" functions.

> Making code a shared library is just something that would be possible once that is done and you do raise good point against that specific part of this discussion.

This sounds like a much more reasonable position.  I am in favor of code cleanup and architectural clarity.
