### ISSUE TITLE
Use OpenGL texture arrays for animations

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1169]
Texture arrays are a special type of OpenGL texture that stores multiple images withing a single texture object. The advantage of this is that a shader can access every single image without having to rebind the texture.

We could use this feature (which is part of the OpenGL Core context since 3.0) to speed up rendering of particles since that would be a great application of this feature. The effect batcher already groups the particles by texture and then draws all particles with the same texture with one draw call. With texture arrays this could be further improved by grouping all particles together that render using the same animation which should drastically reduce the amount of draw calls the particle code has to make.

The particle batching code would need to be changed so that the texture array index is added to the rendered vertices so that the shader can access the right texture.

While we are at it we could also just go ahead and convert all textures to array textures since FSO allows to use animations for a lot of images.

**Possible OpenGL implementation:**
Since we allow animations for pretty much all texture types, all samplers in the shaders would need to be an array sampler. This may not be necessary for single image textures but a texture array with a single image behaves pretty much like a normal texture so that shouldn't cause any issues. For the main shader the required image index would need to be passed to the shader as a uniform but since the individual indices stay the same for a single draw call, there don't need to be any changes to the vertices we pass to the GPU.

**Changes to bmpman:**
To make the usage of array textures easier *bmpman* will handle the conversion between a bitmap handle and the texture array + index.

**Possible issues:**
OpenGL texture arrays require that all images have the same size. Do we allow animations where the individual frames have different dimensions? If that is the case then those need to be handled like standard textures with only a single texture. The code could issue a warning to the modder to let them know that performance could be improved by using the same size for all textures.

**Comment by The-E** [comment]
All frames in an animation are expected to be the same size (We do not actually enforce this, but both .ani and IIRC apng do not allow differing frame sizes AFAIK). If necessary, that's a constraint we can enforce on animations.

**Comment by asarium** [comment]
Ok, that's good. Then we won't have to handle that special case. EFFs probably still allow it though so we might break a few mods.

**Comment by The-E** [comment]
They allow it, yes, but I am unaware of any case where someone actually made an animation where frames have different sizes

**Comment by SamuelCho** [comment]
I tried to take a stab at this a couple months ago. At first it seemed pretty straightforward but then it started getting annoying and complicated.

First, there are definitely EFFs that have frames of different dimensions. A lot of mods use HUD assets that are EFFs in place of ANI files. I had to write code to verify if a texture was designated an animation and to check if all the frames in the animation was of matching size before we went ahead and created a texture array.

I also had to make sure that there was communication between texture management and shader determination code. The shader determination code needed access to the functions that determined if a texture had to know well in advance if a shader had to have texture array support flags on or not. 

The biggest issue was the paging system. The bitmap manager assumes that any texture, whether it be from an animation or not, can be loaded or unload at anytime. In cases where we tell OpenGL to render with a texture that's a part of a greater animation that's not yet loaded, I expect opengltexture.cpp will create the whole texture array with the entire animation. But what if the paging system says "I want this texture gone now"? We obviously can't just delete the texture since it's part of a greater array. We can't just say "That's cute Bmpman, we'll keep your suggestion in consideration" and do nothing. We have to keep track of all the frames in the texture array that were marked for deletion to make sure we only delete a texture when all the frames in the texture array are marked for deletion.

So yeah, I was working on it for a bit but then I got unmotivated. I still think this is worth pursuing though.

**Comment by MageKing17** [comment]
I thought animations were loaded and unloaded using their first frame only; when do we try to unload a frame from the middle of an animation?

**Comment by SamuelCho** [comment]
bmpman and OpenGL don't really talk to each other much. Loading a bitmap still doesn't mean OpenGL will have the bitmap resident as a texture. We only tell OpenGL to load a texture on GPU when it's finally rendered for the first time.

You can very easily have OpenGL want to load a texture of an animation mid-frame. You can easily create a case where an explosion is happening off-screen, then you finally look at it and viola, mid-frame load.

**Comment by asarium** [comment]
> First, there are definitely EFFs that have frames of different dimensions. A lot of mods use HUD assets that are EFFs in place of ANI files. I had to write code to verify if a texture was designated an animation and to check if all the frames in the animation was of matching size before we went ahead and created a texture array.

That's unfortunate. At some point we will have to decide if we want to continue to support that since it would make the implementation of this feature a lot harder than it needs to be.

> I also had to make sure that there was communication between texture management and shader determination code. The shader determination code needed access to the functions that determined if a texture was kosher for texture arrays to know well in advance if a shader had to have texture array support flags on or not.

I was hoping to always use array textures even if that array only contains a single image. That way the shaders wouldn't have to use another flag to identify if a normal sampler or an array sampler should be used. There is the issue with render targets here but as far as I can tell it is possible to attach texture arrays to a framebuffer so the single image array trick should work here.

> The biggest issue was the paging system. The bitmap manager expects that any texture can be loaded or unload at anytime. In cases where we tell OpenGL to render with a texture that's a part of a greater animation that's not yet loaded, I expect opengltexture.cpp will create the whole texture array with the entire animation. But what if the paging system says "I want this texture gone now"? We obviously can't just delete the texture since it's part of a greater array. We can't just say "That's cute Bmpman, we'll keep your suggestion in consideration" and do nothing. We have to keep track of all the frames in the texture array that were marked for deletion to make sure we only delete a texture when all the frames in the texture array are marked for deletion.

I'll take a look at the texture paging code. Maybe there is a way to make that smarter without having to refactor bmpman...

**Comment by SamuelCho** [comment]
I kind of think you're gonna have to allow EFFs to have frames of differing sizes. Diaspora uses EFFs for HUDs (I know this because I designed it). It's the only way to get PNGs for HUDs since the HUD system uses bm_load_animation. I think it's inevitable that you'll have to have code that sanity checks if an animation can be unified in a tex array or not.

Assuming all textures be texture arrays is not a bad idea. But that might be complicated by how we handle cubemaps and render targets. Extra vigilance is necessary when trying to simplify the texture and render target OpenGL code.

**Comment by asarium** [comment]
Cubemaps are completely different and thankfully we currently don't mix those with "normal" texture (I hope). I'll have to do some tests with how OpenGL handled texture arrays as framebuffer attachments but hopefully that works.

I guess if EFFs with different sizes are that widespread then there is no way around the issue. The simplest solution would be to just store each frame in a separate texture in that case but that will require quite a lot of management code.

**Comment by TheMatthew** [comment]
This may be a silly/off topic. 

* Is texture animation a slowdown right now?
 
* What kind of win would this feature bring?

* What speedup could this provide?

* Would this encourage the feature to be even more used? e.g. for smoldering damage or fancy new shields?

**Comment by MageKing17** [comment]
> First, there are definitely EFFs that have frames of different dimensions. A lot of mods use HUD assets that are EFFs in place of ANI files.

> I kind of think you're gonna have to allow EFFs to have frames of differing sizes. For example, Diaspora uses EFFs for HUDs (I know this because I designed it).

Why does using EFFs for HUDs automatically mean each frame will be a different size? (Note: I have basically no idea how HUD assets work.)

**Comment by SamuelCho** [comment]
We're basically just changing the plumbing in our OpenGL texture handling code. There's a bit of overhead that builds up if you're repeatedly switching textures and issuing draw calls. This would reduce the number of textures we'd have to context switch while cutting down the number of draw calls. I've seen the effects batcher take up to 3 milliseconds to render so cutting that down would be a big win in terms of performance.

**Comment by SamuelCho** [comment]
The reason why frames in HUD EFFs are sized heterogeneously is simply a hold over to how FS2 used ANIs to merge a bunch of different HUD graphics into one file. So say you had the right arc HUD gauge. That code references three graphics in an ANI file. Though I may be mistaken since it's been a while since I looked at the code since the HUD rewrite. But one of the frames has the right arc graphic, another has the dumbfire indicator, and another has the missile lock indicator. 

So EFF have to follow this assumption since they can be dropped into bm_load_animation as well as ANIs.

**Comment by asarium** [comment]
So far I have come up with two solutions for the variable size animation poblem:

1. Put all frames into individual textures. That will require additional management code to distinguish between same size animations and animations with differing sizes.
2. Put all frames into a single texture array but use UV-scaling to use the right area for images that are smaller than the maximum size. This would require additional code for passing the scaling factors to the shaders since most texture access operations would need to support this.

@SamuelCho Do you have another solution? Personally, I think option 1 is the better option since that keeps the management logic out of the shaders. I have thought about how to manage the different textures and I think I have a design that should be relatively easy to implement and use.

**Comment by SamuelCho** [comment]
I still think 1) is the better option.

**Comment by asarium** [comment]
Ok, I'll pursue that option then.

**Comment by asarium** [comment]
Progress report: The texture management now creates texture arrays for all 2D bitmaps and I added support for rendering those textures with the pass through shader so the basic interface rendering is now working again. The main shader and effect rendering has not been adapted yet.

**Comment by asarium** [comment]
I fixed most of the rendering for texture arrays. Particles and most other things work and already take advantage of texture arrays. I'm seeing a modest performance improvement with these changes so they are definitely worth it:
![figure_1](https://cloud.githubusercontent.com/assets/1013983/24083672/d0a76bfa-0cdb-11e7-8fbe-dec541b5b309.png)

There are still a few rendering bugs but most of the work seems to be done now.

**Comment by asarium** [comment]
I think I fixed most of the rendering bugs but I can't figure out why most of the lighting doesn't seem to work. Here is the current state: https://github.com/asarium/fs2open.github.com/tree/opengl/textureArrays

**Comment by asarium** [comment]
I fixed the lighting issue (I had to introduce a new shader for that unfortunately) so this should be close to finished. I opened #1318 for initial code review and testing.
