### ISSUE TITLE
Available missions list in campaign editor is empty

### ISSUE THREAD

**Issue by Yarn366** [scp-fs2open/fs2open.github.com#1224]
Since the SDL2 merge, the available missions list in the campaign editor has always been empty, even if mission files are present in the missions folder. This makes it impossible to add missions to campaigns with recent versions of FRED!

**Comment by Yarn366** [comment]
I figured out just now that the campaign editor is now looking for missions in `%APPDATA%\HardLightProductions\FreeSpaceOpen\data\missions` instead of than `[FS2 folder]\data\missions`. I haven't yet figured out how to fix this, though.

**Comment by chief1983** [comment]
Yeah it needs to use the primary mod data folder I imagine, or merge all data folders.  Making a campaign from missions in the user data missions folder would probably be a bad idea though.

**Comment by MageKing17** [comment]
> merge all data folders

That sounds like a good idea to me.

**Comment by asarium** [comment]
I think I found the cause of this issue. FRED sets the `Skip_packfile_search` flag when searching for available missions which skips the search in the internal file list. This means that the function will only return files that are located in the default root directory which now is the user directory since that is used for writing files now.

IMO, using that flag is not a good idea at that point because it hides missions that could otherwise be used in the campaign even before the file system changes.

**Comment by chief1983** [comment]
So before the root was the user directory on Windows, it would have only scanned the current mod, or root game filesystem?  No VPs, etc?  I guess if you're editing a campaign you probably have the missions on the filesystem too.  That may be behavior we want to maintain, so we don't create any surprises.  Any way to use the old root for FRED, instead of the user directory root now?

**Comment by MageKing17** [comment]
I highly doubt users will complain that more missions are showing up in the campaign editor; the only usability concern I can think of is the retail missions showing up.

**Comment by chief1983** [comment]
That's kind of what I'm getting at.  If you are working on a new diaspora campaign, all the R1 missions would show up.  Tbp, all the existing packed VP's missions from all the released campaigns.  That's why I think it was intentionally restricting itself to one place.

**Comment by MageKing17** [comment]
That's why it was intentionally not looking in VP files; I don't think only looking in one folder (for FSO, at least; obviously retail only had one folder to look in) is the right idea, though.

**Comment by chief1983** [comment]
Maybe we're thinking about this the wrong way though. Perhaps, even mod developers should be doing their initial work in the user data directory.  New missions, campaigns, etc should maybe all live inside there.

**Comment by asarium** [comment]
We shouldn't force mod developers to use a specific directory. That's just unnecessary. We could change the mission searching code so that it only searches in "real" directories which should fix most of the mentioned issues.

**Comment by AxemP** [comment]
Hi! Modder here. The thing with FRED only looking in the active mod directory was quite the pain. Newbie modders would post semi-regularly on HLP asking where the heck the missions they made are in the campaign directory (they made them in /data/missions but since they were running MediaVPs, FRED would be looking in MediaVPs/data/missions). So having FRED look at all active mission directories (but not in any VPs, which makes sense!) would be very nice.

And I really really wouldn't like modders being forced to use user data directory stuff. I have 2 FreeSpace installs on my computer, a clean one for playing on my C Drive and a messy development one on my F(reespace) Drive. So making me merge those two... please no. :(

Let's not change modding conventions that we've all been using for 10+ years...

**Comment by chief1983** [comment]
Sounds like you are both asking us to make a change, and not make a change, in the same comment.  :P

**Comment by AxemP** [comment]
Okay, so to make myself clear...

"merge all data folders
That sounds like a good idea to me."

That I agree with. I'd like to see that change. It makes sense since that's how FreeSpace currently operates anyway.

"Perhaps, even mod developers should be doing their initial work in the user data directory. New missions, campaigns, etc should maybe all live inside there."

That I don't. That's not how modders have been trained to work for the last decade, and upending that is going to cause a lot of complaints.

(I'm taking user data directory to be the APPDATA%\HardLightProductions\FreeSpaceOpen\data\missions, if I'm misunderstanding something, sorry for the confusion!)

**Comment by chief1983** [comment]
I hear you, was just messing around.  All your points are clear and valid, was mostly spitballing with my previous suggestions.  I was only concerned with pits that might be dug by giving people the option to create campaigns from missions spread across disparate folders that happen to all be in the search path.

**Comment by AxemP** [comment]
Right, I just get _very_ serious about my folder structures. :p 

Personally I don't see that much of a problem, the modder SHOULD be keeping track of where their missions are. If they make a campaign with missions from multiple paths and doesn't put them in the same VP well... they probably have larger issues...
