### ISSUE TITLE
Action SEXPs without parent cause obscure error

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1256]
Since I don't know much about SEXPs and FRED I'm not sure if using a SEXP without a `when` parent is valid or not but it should at least produce a descriptive error message.

Test mission: [SEXPTest.txt](https://github.com/scp-fs2open/fs2open.github.com/files/793058/SEXPTest.txt)
This mission uses the SEXP `( script-eval "ba.print('Test')" )` and causes the error when it is first executed:

```
Error finding sexp argument.  Received value -1 for sexp:
( script-eval "ba.print('Test')" )
```

**Comment by The-E** [comment]
I think this is a pretty straightforward bug. Technically, this sort of thing should be legal (and is for many, many other sexps); sexps without a when operator are executed once on mission start.

The issue here seems to be that script-eval doesn't return the correct value. When an action operator is used like above, eval_sexp expects the sexp value to be set to SEXP_TRUE (I am not sure what a sexp_val of -1 signifies in that context; the relevant code was added by @Goober5000 in commit 8d2b742020c5a10c9f1752d82a4c92a0fd8e84e0, which happened close to 14 years ago).

**Comment by MageKing17** [comment]
> I am not sure what a sexp_val of -1 signifies

Nothing special. It *used* to be `SEXP_KNOWN_FALSE`, but that was changed to `-32767` by @Goober5000 a long time ago. In this context, it just means "`script-eval` didn't return anything"; the only way for `sexp_script_eval()` to return something other than `-1` is for the return type to be `OPR_NUMBER` (which it is if the SEXP is `script-eval-num`); otherwise, it just always returns (or, now that PR #1257 has been merged, I suppose I should say "returned") `-1`.

My question is whether or not we want `script-eval-string` to also return `SEXP_TRUE`, because `modify-variable` does, and it's basically just a fancy `modify-variable`.

**Comment by The-E** [comment]
That's a good point. `script-eval-string` should also return SEXP_TRUE in this instance.

**Comment by Goober5000** [comment]
@The-E, what specifically are you referring to in commit 8d2b742?  Or is that a typo?

According to my investigation, the default return value of -1 dates back to WMC's initial commit of the scripting function (with the log message "Texture replacement stuff") in SVN revision 2715.  Back then, the function was only a few lines long.

I think this was actually a twofold bug: not only should the `script-eval-string` SEXP operator have returned `SEXP_TRUE`, but the default return value for `script-eval-num` should have been 0 instead of -1.  It's a bit late to change `script-eval-num`'s default though.

@MageKing17's explanation is correct and `SEXP_TRUE` is the proper value to return.

**Comment by The-E** [comment]
@Goober5000 I was specifically referring to the code that was throwing that particular error message (which was starting at line 11687 in that patch and which now resides at line 25038), which is only going to be entered if 'sexp_val' is < 0. Given that we catch the 'SEXP_KNOWN_*' and the other special conditions in the code block just preceding it, I wonder what the reasoning here is. Your comment there says that the subsequent check to see if arg_num equals -1 is there to "make sure everything works okay", but I'm not experienced enough in the sexp code to know why this is something we need to 'Error' out of.

**Comment by MageKing17** [comment]
After looking over that code some more, that block of code appears to exist so that if a SEXP that returns a negative value (which wasn't a thing in retail FS2) is used as an argument to another SEXP that expects a positive value, it will silently flip the sign so that the parent SEXP sees a positive number (why this was done, I don't know, but changing it at this point sounds like a backwards-compatibility nightmare). The `arg == -1` check is a safety check so that `query_operator_argument_type()` doesn't get called with an `argnum` of `-1` (although the actually dangerous parameter to be less than 0 when calling `query_operator_argument_type()` is the other one, but it would be in this case, as I'll explain). Why is `find_argnum()` returning `-1`? Because `find_parent_operator()` is returning `-1`, because the SEXP *has* no parent; this is the expected return value for a parentless SEXP, but this code fails to actually check the value of `parent` to know that this entire block of code is unnecessary. Without the `arg == -1` check, that `parent` of `-1` would get passed to `query_operator_argument_type()`, triggering either an assertion or trying to index an array with an index of `-1`, which is obviously a bad idea... but since the whole thing is superfluous if the SEXP doesn't have a parent, the whole rest of the block ought to be skipped if `parent` is `-1`.

**Comment by Goober5000** [comment]
Sorry, this notification got away from me and it took me a while to review old email notifications.

@The-E I should have been more descriptive than "make sure everything works okay".  In order to reconcile positive and negative, this code block needs to figure out what the parent SEXP is looking for.  Since SEXP tree navigation only goes one way (towards the children), the code needs to search for the parent node and then figure out which argument of the parent corresponds to the SEXP in question.  At the time, it appeared to me that `arg_num` could only be -1 if something was catastrophically wrong with the SEXP linkage.  Now, of course, it's obvious that `arg_num` could be -1 if the SEXP in fact doesn't actually have a parent.

Or, in a nutshell, what @MageKing17 said.  He figured out the logic behind that code and proposed the correct solution.
