### ISSUE TITLE
Ballistic ammo not showing with cockpits

### ISSUE THREAD

**Issue by krevett62** [scp-fs2open/fs2open.github.com#1306]
The ballistic ammo shown in the HUD on top of the energy bar has disapeared with the recent nightlies. You can see it in the last post of http://www.hard-light.net/forums/index.php?topic=93286

**Comment by asarium** [comment]
I'm currently taking a look at this and my initial debugging shows that the `Show_ballistic` flag of the weapon energy gauge is somehow reset to `false` even though it's parsed as `true` from the table.

I'll fix the memory handling of the HUD gauges to use `std::unique_ptr` while I'm working on the code.

**Comment by asarium** [comment]
I found the cause for this. The mod used for the bug is using invalid data and FSO 3.7.4 ignores that error and somehow still works. There is a warning for this already so there is no need to change the code. If I remove the invalid line in the HUD gauges table the ballistic ammo gauge shows up again.

@krevett62 In case you want to fix this in your mod: The mod specifies `Filename: Empty` in `+Weapon Energy:` but the `Empty` animation has only one frame. The animation for the weapon energy needs exactly four so FSO rejects the animation.
