### ISSUE TITLE
Feature request: Multiplayer Keep Players in Escort List after respawn

### ISSUE THREAD

**Issue by Shivansps** [scp-fs2open/fs2open.github.com#1674]
Right now if you add a player in your escort list it will remain there until it dies, but no one wants that, if i add my friend on the escort list it is because i want to keep an eye on him all the time and find him fast, having player removed after they die in multiplayer kinda kill the purpose of adding players to escort list in multi.

Also displaying his nick as well as his wing name on Escort list will be good.

**Comment by notimaginative** [comment]
I've been working on this one but it got pretty complicated and I ended up reworking how that code works. Since it was rebuilding, merging, and sorting the list with every single change it required a convoluted series of checks to keep player ships on the list. Now it's just a `SCP_list` which adds and removes entries as needed (with priority sorting of course).  It's limited to 20 entries, with the mission limit determining how many are rendered. We're going to need to test this pretty well to make sure there isn't some regression.

I also changed the name to match what the targetbox does with it: `Alpha 2 (Callsign)`
That string is then trimmed to fit. Is that how you wanted it, or would something like `Callsign (Alpha)` be better?

Additionally, any real players added to the escort list are always sorted first. Not sure if that's a good idea or not so if you've got any opinions on the subject let me know.
