### ISSUE TITLE
Failing to play sound files under specific circumstances

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#1706]
First you might want to check the mission file. Super simple, ship dies and should do a death scream. Since it's dead the message sends it using '#' with a matching name instead. But doing this will not play the sound file, the ani and text are sent just fine.
[test.txt](https://github.com/scp-fs2open/fs2open.github.com/files/1925635/test.txt) (re-extension it to .fs2)

The strangest part is that it only doesn't work if there is a ship which just died, or had died which matches the name with the message sender (sans '#').

**Comment by Goober5000** [comment]
For the specific use case underlying this ticket, we found a workaround: set the ship to always play a death scream, and then create a custom persona with a custom death scream for this ship.

For the more general issue, the messaging code is specifically set up to not play messages from a ship which has died, even if the ship is preceded by the # character.  This appears to be intentional.

**Comment by MageKing17** [comment]
...Okay, but just because it's intentional doesn't mean it can't be changed, or that it *shouldn't* be changed; this seems like a perfectly reasonable feature request.

**Comment by Goober5000** [comment]
Granted.  Also, just because it *appears* to be intentional doesn't mean it actually is.  Off the top of my head, this could be because the `#` character could be trimmed from the message source before the code checks whether the message source matches a ship.

**Comment by MageKing17** [comment]
So it turns out this was *supposed* to have been fixed back in 2009 (see [Mantis #1874](http://scp.indiegames.us/mantis/view.php?id=1874)), but the "fix" was doing nothing. I happened to stumble across the incorrect conditional and came up with a solution, so I'll be opening a PR shortly.
