### ISSUE TITLE
When fired, a weapon with the "apply recoil" flag causes the ship to spin wildly when running a debug build

### ISSUE THREAD

**Issue by plieblang** [scp-fs2open/fs2open.github.com#1763]
This does not happen on a release build and is true for nightlies >= 12/21/2017.

**Comment by asarium** [comment]
I just tested it with the Maxim in the retail campaign but could not reproduce your issue? A debug log would probably help here.

**Comment by plieblang** [comment]
From what I can tell, the Maxim doesn't have `apply recoil` but rather `shudder`.  I extracted `weapons.tbl`, added `apply recoil` to the Subach HL-7, set `$Recoil Modifier:` as specified by the wiki (I set it to 5.0) and experienced the behavior.
[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/2138391/fs2_open.log)

**Comment by z64555** [comment]
Another thing that could be a factor is the ship's mass.

**Comment by TRBlount** [comment]
Yeah, retail ships notably are too light for recoil as is, you need to significantly reduce the modifier for the recoil (approx 1/10) to make it work correctly.

**Comment by plieblang** [comment]
I tried setting it to 0.1 and 0.01 and neither really made a visible difference.  If there was any difference, it's not noticeable because the effect is so exaggerated.

**Comment by FSCyborg** [comment]
I just took a careful look at the math, and I am guessing that this is happening because the larger factors are far outweighing the smaller factors.  

We have:
winfo_p->mass * winfo_p->max_speed * winfo_p->recoil_modifier * sip->ship_recoil_modifier

Weapon mass is usually some random value set by the modder.  If the weapon has a speed of 200, this already overcomes the recoil_modifier of .01 because the result of that multiplication is 2 .  With a weapon mass of 20, even, that would already make the value 40, and then since no one really sets ship_recoil_modifier because it is optional, and that defaults to 1.0 anyway, we can easily end up in a situation where the number is 40.  

Finally, the recoil is added *per fire point*.  That would make the final value of the recoil either 80 or 160, depending on single or double fire.  It is scaling too high.  It should be multiplied by a dulling factor to keep it from being too exaggerated. I would actually think .001 or smaller would be good.  And a multiplication of negative 1 happens in the vector calculation, so we could actually set it there without (admittedly negligible) loss in performance.

Because it had not been working in retail, mods are probably not dependent on the current behavior and it should be acceptable to change.

**Comment by MageKing17** [comment]
> Because it had not been working in retail, mods are probably not dependent on the current behavior and it should be acceptable to change.

Recoil did not *exist* in retail; it was added by @TRBlount in 2015 (PR #44).

Additionally, your analysis leaves out the mass of the ship itself; a physics whack of strength 80 or 160 might be perfectly reasonable, as long as the ship is sufficiently massive. There's insufficient data to determine if this is really a problem, since I don't know any mods that are actually trying to use recoil.
