### ISSUE TITLE
Disabling hud by shift + o prevents from gaining target lock for aspect secondaries or locks permanently until target explodes.

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#1821]
Retail data.
There is some sort cheat. If you acquire lock, disable hud, then turn back from target, launch e.g. cyclops, swap fast to next sbank and shot without targeting, and notice how secondaries still follow target. ;)
Of course this works until you enable hud again.

**Comment by z64555** [comment]
Need repro of this for confirmation

**Comment by FSCyborg** [comment]
I was able to reproduce on a November nightly in Slaying Ravana.  I'm going to look at the relevant code to see if I'm up to the challenge.

**Comment by FSCyborg** [comment]
So anyone is able to jump in here, but my idea on a proper fix would be to perform missile locking as normal when the hud is disabled.  But if this ends up being too much, perhaps just disabling all missile locks until the hud is re-enabled.

**Comment by Goober5000** [comment]
Sound reasonable.

**Comment by z64555** [comment]
Confirmed.  While there's no solid lock for the missiles (that is, they won't hit the target) they will still seek to the target instead of the expected behavior of flying straight like a dumbfire.

This doesn't exactly have a huge impact on gameplay, as you can't hit anything.  Although I haven't confirmed the effect  super-agile missiles.

**Comment by tomimaki** [comment]
Fixed.
