### ISSUE TITLE
Enhancement to control warp type in FRED

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#1835]
Currently, if we want a ship to use "hyperspace" or other warp type in place of the default warp behavior, we have to create a duplicate ship in the ships.tbl just to change that one setting. I propose we enhance this so that we can choose the warp type to use in FRED either via checkbox in the ships editor or via sexp or both. This way any ship can use any warp type and it becomes a mission design tool instead of, essentially, a ship specific feature.

**Comment by Goober5000** [comment]
You could make the same argument for any parameter that's controlled in ships.tbl.  I think this would be more trouble than it's worth, since changing any ship class attribute is a matter of copy+paste+edit.

I speak from experience, since I was the one that converted the "stealth" flag to also be a ship flag.  Also, FSPort and Scroll both use ship copies for certain cases.  Scroll has a GVD Hatshepsut#FastWarpDecel that's only used in one place in one mission.
