### ISSUE TITLE
$Rearm Rate: does not seem to work for ballistic primaries

### ISSUE THREAD

**Issue by Kingspoon** [scp-fs2open/fs2open.github.com#1848]
Primary ballistic weapons just all reload at the exact same rate (a very fast rate)
And in addition to that, no rearming sound is played when primary ballistic weapons are being reloaded by the supply ship.

**Comment by FrikgFeek** [comment]
From my own testing the ballistic rearming sound plays as long as there's an entry for it in sounds.tbl, $rearm rate seems to have changed behaviour recently. From testing it seems to control how many 100s of rounds are loaded per second. Changing the Vulcan's $rearm rate from 20 to 0.5 results in 100 rounds being loaded every 2 seconds or so.

I'm fairly certain this is not intentional.

Example here:

https://www.youtube.com/watch?v=fShIGeD7m9c

**Comment by Kingspoon** [comment]
That is... _Interesting_ behavior. And that explains why in every test case I tried they all seemed to reload at the same rate. Which they _kind_ of do, except its the same amount, at varying rates. 
For primary weapons with low ammo counts this means it doesn't matter what rearm rate you set them as, they will be refilled instantly.

So as it turns out the wiki entry for $rearm rate is just blatantly false:
"Defines the rate the weapons are loaded to the ship
    Syntax: Float, missiles loaded per second"
You don't define how many missiles are loaded per second. The amount that is loaded is always 4 for missiles and 100 for primaries. What you define is how fast those set amounts are loaded.

This is not really ideal behavior. And means pretty much all of my weapons.tbl $rearm rate entries are wrong because of false wiki information and counterintuitive behavior.

As for the sound effect not playing. I see/hear it playing on your video. And I do have the sounds defined in sounds.tbl, but play on my end, they do not.

**Comment by Kingspoon** [comment]
Aaaand I figured out why the sounds weren't playing. I defined the entries in the new sound code way, which doesn't work for some reason. It only works if they're defined in the old retail method. Probably because its hardcoded nonsense. Either way, that's a seperate bug I guess.

**Comment by Goober5000** [comment]
If the ballistic rearm sounds are not defined, the code is supposed to play the standard rearm sounds.

**Comment by FSCyborg** [comment]
Some mods probably depend on this type of behavior, since it looks like it has been around since 2002 or 2003, but we can probably add another option to specify how much ballistic ammo is loaded for a given weapon at a time, with the default being 100.  I *think* I can handle it.

Is "$Rearm Ballistic Batch:" a reasonable name?

We can then edit the wiki entry to reflect the current behavior.

**Comment by Kingspoon** [comment]
I'd probably go with "$Rearm Ballistic Count:" or "$Rearm Ballistic Amount:" or something along those lines.

**Comment by FSCyborg** [comment]
I'll go with "$Rearm Ballistic Count:"

**Comment by FSCyborg** [comment]
Looking at the code, specifying it for any given weapon is the same difficulty as just doing ballistics...
How is "$Rearm Batch Amount:" ?

**Comment by Kingspoon** [comment]
When I'm going through the wiki and see something called "$Rearm Batch Count:", I'm just going to be wondering what 'Batch' exactly is being rearmed here :P

How about adding it as an optional line to "$Rearm Rate:" instead? So when you define it in table it looks like:

$Rearm Rate: 5
+Count: 10  

If +Count isn't being set then it just defaults to retail behavior/numbers instead

**Comment by FSCyborg** [comment]
That works. 👍

**Comment by FSCyborg** [comment]
I am assuming that there is another default value somewhere. We have to go with the $ type.  

What other names sound good?  

"$Reload Increment:" ?

**Comment by FSCyborg** [comment]
I'm going with "rearm increment" for now.  Testing my table parsing code now.

**Comment by Kingspoon** [comment]
:Thunk: There are several optional $'s that also come with optional +'s 
I don't see why that should be a problem? The solution to the 'problem' clearly already exists. If +count is defined without $rearm rate then obviously that should be caught and thrown an error about.
Am I missing something obvious here?

**Comment by FSCyborg** [comment]
The only reason I'm not agreeing with you, is that release builds don't warm or abort when Rearm Rate isn't specified.  The Rearm Rate is set to 2.0 when it isn't.  

So there can be a situation when Rearm Rate is not specified but this new feature is.  And naming it as just "Count" would be extremely unclear in this situation.  So it has to be more specific, unfortunately.

My testing is finished.  The feature seems to work as far as I can tell.  Early crashes were caused by my not adding the new part of the weapons struct to one function, and it hasn't crashed again.

In case you want to test it, here is the build, using "$Rearm Ammo Increment :", but if we find a better name, we can still easily change it.

[fs2_open_3_8_1_20190729_0ba1583_x64_AVX2-FASTDBG-NewFlag.zip](https://github.com/scp-fs2open/fs2open.github.com/files/3465349/fs2_open_3_8_1_20190729_0ba1583_x64_AVX2-FASTDBG-NewFlag.zip)

**Comment by FSCyborg** [comment]
The only reason I am not agreeing with you is that the Rearm Rate has a default value that it can be set to when it is not specified on release builds.  Having +Count without that Rate is possible on release builds and would be confusing to newbies reading the tables or to people who don't know the feature has been added.

But I just completed testing, on everything.  As far as I can tell, everything works without a hitch (it is a really simple feature that should have been added a long time ago).  Here is a test build which uses "$Rearm Ammo Increment:" just bellow "Rearm Rate:"

[fs2_open_3_8_1_20190729_0ba1583_x64_AVX2-FASTDBG-NewRearmFlag.zip](https://github.com/scp-fs2open/fs2open.github.com/files/3465369/fs2_open_3_8_1_20190729_0ba1583_x64_AVX2-FASTDBG-NewRearmFlag.zip)

**Comment by FSCyborg** [comment]
Btw, not specifying "Rearm Ammo Increment:" will not throw a warning because the default values are so widespread and expected and depended upon by so many mods, no reason to force everyone to update their tables unless they *want* to use this feature.

**Comment by Kingspoon** [comment]
I'm perfectly fine with that name :+1: 
And the rest you said makes sense to me.

**Comment by FSCyborg** [comment]
This should be closed.  The faulty wiki entry has been fixed, and the desired behavior has been added.

To further clarify the same default values are still in place, (4 for missiles and 100 for ammo).  These will only change if the table specifies.

**Comment by Goober5000** [comment]
Sounds good.
