### ISSUE TITLE
FRED Crashes on Reload with Setting Arrival Cue of Docker Ship to False

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#1877]
If I have a ship docked to a larger ship, and then set the larger ship's arrival cue to false it crashes FRED next time I load the mission it crashes. The mission still loads and works fine in game though. I have attached the mission, and the fred_debug log. 
[_Dock_Test.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2418068/_Dock_Test.txt)
[fred2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/2418070/fred2_open.log)

**Comment by Goober5000** [comment]
It seems that if no dock leaders can be found in a group of docked ships, FRED won't create any ships in the group.  If one of the ships happens to be in a wing, FRED will crash because the wing will refer to a ship that can't be found.

The solution, I think, is for FRED to test for that case and then just pick a dock leader.

(The dock leader is assumed to be the only ship in the group with a non-false arrival cue.)

**Comment by wookieejedi** [comment]
Thanks for fixing!

**Comment by Goober5000** [comment]
You're welcome!
