### ISSUE TITLE
Bad memory allocation causing instant CTD on load with certain sexps

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#2081]
With nightlies on and after July 29 (with commit #2035 ) Surrender Belisarius will crash almost instantly on load. The amount of details I can give are limited but here's what I got...

Callstack: https://pastebin.com/DF3AhxYr

And when looking around in whats stored in memory, I saw some references around the Iota 2 Docking event. I don't know which sexp exactly is causing it though.

And this ONLY happens with release builds. Any fast debug or debug will not cause a crash.

So far this is confirmed on 2 other windows systems. Unknown if it crashes on Mac or Linux.

**Comment by Goober5000** [comment]
This is due to a bug in Visual Studio.  Apparently it isn't correctly handling the "parameter pack" templated function with this signature:
```
template <typename T, typename... Args>
int eval_nums(int &n, bool &is_nan, bool &is_nan_forever, T& first, Args&... rest)
```

When I removed the function, the game worked correctly.

The problem is that this function is used in a lot of places and replacing it with a simpler substitute (or rather, series of substitutes) is going to be extremely messy.

The first thing to check is whether updating the compiler which processes the nightly builds will fix this error.

**Comment by Goober5000** [comment]
Nope, it's NOT a bug in Visual Studio; it's my fault.  Sorry, Microsoft.  Working on a new fix.
