### ISSUE TITLE
void multi_ts_get_team_and_slot() Depends on Behavior that is not guaranteed

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#2199]
This function depends on the mission creator not using special characters in wing names.  If any mission creator were to do this in a multi mission, a myriad of things would probably break including respawning, and they would have no clue why, and we would probably spend endless time debugging.

`*slot_index = (ship_name[strlen(ship_name)-1] - '1');`  Get's the last character of the ship's name and then subtracts one, oblivious to the fact that we can add other characters to the end of the string using "#".  (Yes, I know this would be a very rare occurrence, but I'd rather change this now instead of trying to figure it out when I get an extremely odd assert)

Not sure if this is related to the bugs that I was looking at when I started looking at this function, but basically we just need a more robust way to get the ship's `wss` slot.

**Comment by Goober5000** [comment]
Is this function ever called with the display name?  From a cursory search, all occurrences are called with the ship's actual name.  The actual name is the full string, including '#' and everything.

**Comment by MageKing17** [comment]
To the best of my knowledge, if a wing has "#" in the name, the ships still get the number added to the end (after the hash), so while hackish, this shouldn't actually be a problem.

**Comment by FSCyborg** [comment]
I looked in FRED before posting and this is the behavior I saw there. Hopefully it is corrected on mission save or at some other point, and I had nothing to worry about.
![bug2](https://user-images.githubusercontent.com/12529946/71055595-40ec7900-2124-11ea-8658-97904f2b8564.png)

In any case, I am currently looking for more robust ways of checking instead of relying on the hack, since there is another bug in the function, and I want to try to guarantee that it works every time, regardless.

This function, I believe, is also the cause (for another reason) of Mantis#2757:
http://scp.indiegames.us/mantis/view.php?id=2757

I lucked out and found a mission where that bug appears every time: All Alone.  For some reason in that mission the ship names are not Alpha 1, Alpha 2 in-mission, and I have already tested the first version of a fix as a host.  We'll see about the rest.  But that's all for now.

**Comment by FSCyborg** [comment]
Every instance I saw was the actual ship name.

**Comment by MageKing17** [comment]
Upon reflection, I think the "ship number goes after the hash" was considered a bug and fixed, with the behavior only being retained if the wing name ended with a hash, which e.g. The Blade Itself uses. So this definitely does need fixing.

**Comment by FSCyborg** [comment]
This may not be the only place that relies on this behavior, so I'm going to need to look for other instances of this, and write fixes individually.

**Comment by JohnAFernandez** [comment]
Appropriate behavior is now in master!
