### ISSUE TITLE
Add throttle and pedals support

### ISSUE THREAD

**Issue by luca2125** [scp-fs2open/fs2open.github.com#2256]
Hi,

I have complete flight system Joystick + Throttle + Pedals but the game don't allow to choose multiple controllers. 

There is a way to add it ?

P.S.

The force feedback seem not work but probably it is not set correcly by me. 

How I can set the force feedback ?

**Comment by asarium** [comment]
There is currently no support for multiple joystick devices. You might be able to make it work with a software solution like vJoy though.

For you other questions, please refer to the [support forum](https://www.hard-light.net/forums/index.php?board=151.0) since this is not the right place for that, sorry.
