### ISSUE TITLE
Review compute_point_on_plane()

### ISSUE THREAD

**Issue by Echelon9** [scp-fs2open/fs2open.github.com#229]
The function `compute_point_on_plane(vec3d *q, const plane *planep, const vec3d *p)` has the following documentation:
```
/////////////////////////////////////////////////////////
//	Given a plane and a point, return the point on the plane closest the the point.
//	Result returned in q.
void compute_point_on_plane(vec3d *q, const plane *planep, const vec3d *p)
{
...
}
```

The function or its documentation cannot both be correct, as there are parts of the function declaration which operate without touching variable *q. It also might be that *p is the desired output.

Note: This was highlighted with the following gcc warning:
```
math/vecmat.cpp: In function ‘void compute_point_on_plane(vec3d*, const plane*, const vec3d*)’:
math/vecmat.cpp:1413:11: warning: variable ‘tv’ set but not used [-Wunused-but-set-variable]
  float k, tv;
           ^
```

**Comment by asarium** [comment]
`p` is most likely not the intended output as it is declared as `const`. Only `q` is changed by the function which matches the documentation.

**Comment by Goober5000** [comment]
Also, there is a common pattern in C functions which stuff a result into an output parameter: the output parameter comes first, and all subsequent parameters are inputs.  This isn't universally followed, but is a good default assumption.

**Comment by MageKing17** [comment]
`*p` is clearly used as input every time it is passed as an argument to another function, and the only part of `compute_point_on_plane()` that doesn't affect `*q` is the `tv =` line.

The most likely reason for the vestigial variable is that it was originally used as a debug value, or perhaps the function used to return tv instead of being a void.

The correct solution seems clearly to be to just remove the line, which PR #274 does.

**Comment by Echelon9** [comment]
Resolved in master.
