### ISSUE TITLE
Feature request: Target-independant beam slash.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2313]
I would like to be able to specify a fixed angle to sweep through for slashbeams, overriding the default dependence on target radius. This would among other things allow for spawned slashbeams without targets to work like slash beams should rather than being indistinguishable from regular beams.

**Comment by MageKing17** [comment]
And the slash angle would just be random, then?

**Comment by EatThePath** [comment]
@MageKing17 as in the orientation of the plane it sweeps through? I suppose so. I assumed it already was, honestly.

**Comment by MageKing17** [comment]
It's semi-random; it uses a randomly-chosen "octant pair" from the model, chosen from a list of "good octant pairs". It's not a terribly complicated method for choosing coordinates for the beam to sweep through (since it's supposed to be fast), but it *does* require a model to be targeted, so we need some other way of generating points to slash between; "pick a random angle" is the most obvious answer, but I wanted to confirm that's what was wanted.

**Comment by asarium** [comment]
Maybe just specify two point it will slash through. If I remember the internal system correctly that is how slashing beams work already.

**Comment by MageKing17** [comment]
...Right, we already implicitly passed that stage; we're talking about a *way* to specify two points when spawning subweapons.

**Comment by JohnAFernandez** [comment]
Fulfilled, woohoo!
