### ISSUE TITLE
 Automated code review for SCP FreeSpace 2 Open

### ISSUE THREAD

**Issue by P-ignatovich** [scp-fs2open/fs2open.github.com#2350]
Hi!
I am a member of the team developing monocodus — a service that performs automatic code review of GitHub pull requests to help organizations ensure a high quality of code.
We’ve developed some useful features to the moment, and now we’re looking for early users and feedback to find out what we should improve and which features the community needs the most.

We ran monocodus on a pre-created fork of your repo on GitHub https://github.com/monocodus-demonstrations/fs2open.github.com/pulls, and it found some potential issues. I hope that this information will be useful to you and would be happy to receive any feedback here or on my email pavel@monocodus.com.

If you want to try our service, feel free to follow the link: https://www.monocodus.com
The service is entirely free of charge for open source projects. Hope you’ ll like it :)

**Comment by Goober5000** [comment]
To quote someone on Discord:
> Well that isn't helpful.  Its basically telling us, "your functions are too long and too complex".  Yeah, we know that already thanks

I looked through the link and the suggestions are an annoying combination of pedantic and trivial.  Not interested.

**Comment by P-ignatovich** [comment]
Okay, thank you for the feedback. Could you then tell me what features and suggestions would make you interested?

**Comment by Goober5000** [comment]
I'm not sure to what extent code reviews can be automated, as they inherently depend on real-life expertise of other coders.  Feedback can be very subjective, such as advice to use a different algorithm, or expertise based on familiarity with the code base.

Take a look at this PR, which was the result of my realization on a different review that the code had drifted from its original purpose due to incorrect assumptions by maintainers over the years:
https://github.com/scp-fs2open/fs2open.github.com/pull/2346

Or take a look at this PR, where my review relied on understanding what the code actually did:
https://github.com/scp-fs2open/fs2open.github.com/pull/2341

These are the sort of things that are needed for code reviews to be meaningful.  By contrast, the issues that monocodus identified were not useful to the review.

Here for example:
https://github.com/monocodus-demonstrations/fs2open.github.com/pull/16
The `read_model_file` function is very long and very complex.  We already know this.  But the PR only concerned itself with making a very minor change to the function; changing the length and/or complexity is completely out of scope for that PR.

Furthermore, the PR only changed a small percentage of the total lines in that function.  A warning about length and/or complexity is inappropriate in this situation.  It would be more appropriate if a PR added a new function or significantly rewrote one.

Take a look at this PR:
https://github.com/monocodus-demonstrations/fs2open.github.com/pull/12
Here, monocodus ran clang-tidy on a line that was not even modified by the PR.  It took a clean, compact line and suggested making it bloated.  This was just annoying.  Furthermore, our repository *already* uses clang-tidy as part of our CI process, so this a) was unnecessary, and b) used a clang-tidy option that is turned off in our configuration.

I wish you luck, but code reviews require a certain amount of human insight.  Simple pattern recognition is not adequate, and I don't know that automated analysis is capable of providing insight.

**Comment by P-ignatovich** [comment]
Thanks for the detailed answer!

I agree that a full review of the code requires an understanding that only the person involved in the development process has. We’re not aiming to create an ultimate replacement for full value code review, but to point out some potential flaws in a couple of minutes after the developer pushes code into a branch so he can fix something before the human reviewer has time to look at pushed code. it’s hard to find an adequate degree of automation that you mentioned, but we try our best. :)

I see the current version of the checker of functions’ length and cyclomatic complexity is not very useful for you. How can we improve it? Would it be more useful if it reported only when changes in the code increase the complexity/length of the function by some amount? For example:

`Cyclomatic complexity of function foo(...) increased by 20% from 20 to 24. Making functions more complicated than they already are is not a good idea`

About bad comments from clang-tidy. It commented on unmodified code due to the error in the algorithm. I’ve added that to our TODO and we’ll fix it soon. 
We currently working on an interface that will automatically use `.clang-tidy` config file if it exists in the repository to report only what the user really needs. It’s not finished yet so default config was used even though you had a config file in your repo. 
Default config is currently far from perfection because most of our team don’t have serious experience in C/C++ and we didn’t yet figure out which of default clang-tidy options are useless for most of the developers. 
Could you please tell which of them are completely useless in your opinion so we can disable them by default? 

Our team is now deciding which features we will add in the near future. We would be happy to know what’s your opinion on some of them.

1. We want our bot to check code formatting after each push using the tool and config chosen by the user. If any issues found,  the report in GitHub checks is created with a button “fix”. After the button is pressed by the user with write access to a branch, a new commit with formatting fixes is created. Do you think it will be useful? Would you consider giving a bot write access to the repo to use this feature?

2. Spellchecking for comments and string literals in code, readmes, and other plain text data. Says for itself. If it founds a typo - it creates a review comment pointing to the string containing it.

Besides that, we want to add a lot of useful checkers and tools to our service. Which existing commenting or fixing tool that would be useful for you? We are open to suggestions and any requests from you would really help us to make monocodus helpful. 

Thanks again for the feedback! Looking forward to receiving your answer.

Regards,

Pavel

**Comment by Goober5000** [comment]
> We’re not aiming to create an ultimate replacement for full value code review, but to point out some potential flaws in a couple of minutes after the developer pushes code into a branch so he can fix something before the human reviewer has time to look at pushed code.

In this case it would be more appropriate to advertise your product as another tool for continuous integration, or for static code analysis.  Look at how clang-tidy is advertised.

> I see the current version of the checker of functions’ length and cyclomatic complexity is not very useful for you. How can we improve it? Would it be more useful if it reported only when changes in the code increase the complexity/length of the function by some amount?

I already answered this here:

"Furthermore, the PR only changed a small percentage of the total lines in that function. A warning about length and/or complexity is inappropriate in this situation. It would be more appropriate if a PR added a new function or significantly rewrote one."

If the function is new or if a significant percentage of the function's lines were changed or added (more than 50%) is, I think, the minimum for these warnings.

> We currently working on an interface that will automatically use `.clang-tidy` config file if it exists in the repository to report only what the user really needs.

Good idea.

> Could you please tell which of them are completely useless in your opinion so we can disable them by default?

I don't want to spend time making a list, and anyway the list is going to be different for every developer.  Using the config file is the best solution.

> We want our bot to check code formatting after each push using the tool and config chosen by the user.

I think there are existing tools which format code as part of continuous integration.  I don't remember what they are, but one developer on our team already uses them.  For your suggestion, our project would not use such a feature, but other projects might.

> Spellchecking for comments and string literals in code, readmes, and other plain text data.

This sounds useful... however, there is a risk for false positives on names, technical terms, and other uncommon words.

**Comment by P-ignatovich** [comment]
Thanks for the answer!

Your feedback has been genuinely constructive for us. I have made additions to the development plan based on the information you provided.

Hope one day we'll make monocodus a lot more useful for you ;)

**Comment by Goober5000** [comment]
Glad to help.  Best wishes and good luck!
