### ISSUE TITLE
FR: AI missile lock time override

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2393]
This request is mainly pertinent to when multilock features are included. Under mutli-lock, certain setups perform very differently for players and AIs. Say you have a bomb that can lock a single target four times. The effect of that is that the player can fire one bomb relatively quickly, or keep holding course and lock all four bombs after waiting four times as long.

However, since the AI doesn't use the multi-lock features itself, what happens is they wait the base lock time, then fire a volley of four missiles. The wild disparity in behavior between the AI and player when using the same missile can get quite awkward. Thus, I would like a way to define a wait time before firing for AIs only that overrides the normal behavior of waiting out the normal base lock time.

**Comment by z64555** [comment]
I would prefer the AI be smart enough to determine if it wants to fire one bomb or all 4 in the volley, rather than had something hardcoded that would essentially have them *only* fire the full volley.

I'd say do a little research into how the AI acquires a lock on their target and what all determines when they're able to fire, as they should closely emulate as to whats capable by a human pilot.

**Comment by Baezon** [comment]
Although this is technically a separate feature request, I'll close this for now since the original reason it was proposed was fulfilled. Can always be re-opened later if this feature is wanted for another reason.
