### ISSUE TITLE
FS1 COOP UP SM3-03A to 06A do not show up on multiplayer mission explorer on 20.1.X builds

### ISSUE THREAD

**Issue by Shivansps** [scp-fs2open/fs2open.github.com#2733]
This is another weird thing, these missions arent showing up on the multiplayer mission explorer on any of the 20.1.X builds, and they do on 19.0.0.
They are being loaded correctly by the game because they work using a campaign file that call them.

[missions.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5205006/missions.zip)

**Comment by JohnAFernandez** [comment]
Weird.....  The mission loading code does not seem to have been updated in something like 7 years, so this would definitely be weird.

**Comment by notimaginative** [comment]
Looks like those missions fail a tstring check which causes them to be skipped. Here's the comment from the code:

`// the untranslated and default-translated strings should always be identical, so if they're different, it might mean we have some data from a different mod`

**Comment by Goober5000** [comment]
Oh right, this feature was introduced because whenever someone would play multiplayer with a mod that used tstrings, the FS2 missions would be all scrambled in the listing.

This likely means the multiplayer FSPort mission strings aren't consistent with the singleplayer FSPort mission strings.  I'll look into that.

**Comment by Shivansps** [comment]
Got it. Thanks
