### ISSUE TITLE
ETS transfer rates are not customizable

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#2852]
As a vintage 90s space sim, FS2 features an energy transfer system that allows the user to shunt energy from shields to weapons and back again. The transfer can trade 1:1 from shields to weapons but 2:1 from weapons to shields; these values are hardcoded and shouldn't be.

A table option should be added to allow this ratio to be customized; I'll leave it to community feedback and the implementor (implementress?) to define where this option is best placed.

**Comment by z64555** [comment]
Ok, so, there's a bit of a design flaw with the energy system. I'll first explain how the transfer system works.
The transfer functions are in hud/hudets.cpp. transfer_energy_to_shields(), transfer_energy_to_weapons(), and transfer_energy_weapon_common().

The amount of energy transferred is a percentage of the max capacity of the system being taken from, starting off with 20% as defined by ENERGY_DIVERT_DELTA.

This energy delta is further scaled by factor that depends on the direction of the transfer, 100% for shield to weapon transfers, and 50% for weapon to shield transfers.

Let E_shield_max = 100, E_weapon_max = 100.
E_shield_delta = 10% * E_weapon_max = 10;
E_weapon_delta = 20% * E_shield_max = 20;

This means that, should shield and weapon caps be equal, it would take twice as many transfers from weapons to shields than it would to transfer energy from shields to weapons for the same amount of energy.

An exploit arises when the shield recharge rate is significantly faster than the weapon recharge rate in terms of energy units (we'll use MJ as an example).  An example ship has a weapon recharge rate of 2% per second and a shield recharge rate of 2% per second.  The weapon energy is 100MJ and the shield energy is 100MJ.  Both effective recharge rates are 2MJ/s, so in this instance there is no design issue.

A second example ship has a recharge rate of 2%/s for both weapon and shield.  This one also has a weapon energy of 100MJ but a shield energy of 200MJ.  The effective recharge rate for weapons is still 2MJ/s but the shield recharge rate is 4MJ/s.  Since the shield recharge is 2x MJ/s as the weapon recharge, this means that the player can shunt ETS allocation to shields and engines and effectively recharge weapons and shields at the same rate while getting a faster afterburner charge rate and speed boost, with only the penalty of needing to transfer some energy occasionally and a somewhat minor reduction in shield strength.

This effectively eliminates the reason of having any energy allocation to weapons for this ship, which is an issue a mod maker would not immediately be aware of unless they had a deep understanding of the ETS nuances to begin with.

**Comment by z64555** [comment]
With the issue outlined above, what options should be given to modders to allow them to address the issue?
Should energy transfers be in MJ (energy units) instead of percentages?
Should energy transfers between systems be equal?
Should there be loss applied to energy transfers?
Should energy transfers be allowed to begin with?

**Comment by PhantomHoover** [comment]
I think the question of whether there's any real appetite from modders to tune this bizarre system for balance is pretty important. Rationalising it will, as you say, take significant effort, and I think the more likely outcome is that everyone who cares about fine energy consumption balance will just turn it off entirely. I also think a flag to unconditionally turn it off is necessary anyway — sure, you can get the same mechanical affect by setting all the ratios to 0, but it's better to give players who are expecting to be able to use it clear feedback that it's not working.
