### ISSUE TITLE
FR: A unified interface for script options

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#2864]
Scripting has grown very popular as a way to customize the FS experience. But with that popularity come issues: Some scripts have usability implications (like the bomb flash script in the MediaVPs) or performance implications (like particle spawn scripts), and due to the way they are currently distributed, they are hard to configure according to the user's wishes.

It is therefore desirable that we create a system that can unify these settings in a way that allows the engine to create an options screen.

A proposal:
* We add a section to scripting.tbl that exposes settings for that particular script, for example like this:
```
$Option:
  +Name: "Explosion flash"
  +Description: "Spawns an explosion flash when bombs detonate"
  +Lua Field: "mvp_bombflash_enabled"
  +Lua Type: bool
```
These options would then be injected into the scripting environment and can then be evaluated by the script to control the runtime behaviour.
* We add a generic key-value store to the pilot file that these options are written to and loaded from on startup

Open questions:
- How do we ensure that options are specific to a given script and do not cause name collisions?

**Comment by asarium** [comment]
I don't think injecting these values into the global name space is a good idea.
Instead, a scripting API should be created that exposes the existing Options system to Lua. This would provide automatic storage handling (although that is on a per-machine basis) and, more importantly, would be automatically supported by the new options UI.

Since all possible options would be needed by Lua scripts anyway, there is no need to add a new table to support this but instead script would just create their options on game start and the options system would take care of passing the config values to the script via callbacks.

**Comment by z64555** [comment]
So... these would in effect be performance options?

**Comment by PhantomHoover** [comment]
Performance, accessibility, player preference. In more or less descending order of importance.

**Comment by z64555** [comment]
ok, and the intended UI is in the menu? I don't think a launcher would be able to get to these options unless they were accessible through the commandline flags

**Comment by MjnMixael** [comment]
Bumping this old discussion because with the `OptionsBuilder` setup in the SCPUI code and the scripts that m!m and I wrote, this is currently possible, albeit slightly differently than The_E's proposal. See the image below. It contains standard FSO built-in options as well as script-built options using the librocket interface.

![screen0542](https://user-images.githubusercontent.com/7740469/210248986-3735582b-eae6-4769-9438-0ce92d667097.png)

I'm unsure if this qualifies for closing this ticket because it seems like The_E wanted something that could be done in the base FSO UI?

**Comment by The-E** [comment]
My original intent was for a way to build something off of wmcgui (i.e. like the old lab). This is now, thanks to SCPUI and the imgui integration, unnecessary.
