### ISSUE TITLE
fs2_open.log file has lost all its newlines

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#298]
Seems to have been introduced by 51832fd563d3b0028d441fd865c709836eec0ee7

**Comment by asarium** [comment]
I think I misread the documentation for `vsprintf`. It only writes `n - 1` characters but I pass the size of the string as the size of the buffer which means that `vsnprintf` doesn't include the last character which is most times `\n`.
Can we be sure that the underlying buffer of `SCP_string` has place for the terminating null character?

**Comment by MageKing17** [comment]
It should be guaranteed as of C++11.

From [StackOverflow](http://stackoverflow.com/a/11752722):
> In C++11 and later, `mystring.c_str()` is equivalent to `mystring.data()` is equivalent to `&mystring[0]`, and `mystring[mystring.size()]` is guaranteed to be `'\0'`

**Comment by Goober5000** [comment]
Looking at that revision, the new code is clever but I don't like the idea of writing directly into the underlying buffer like that.  Isn't that discouraged even though it technically should work?  (And strings weren't even guaranteed to be contiguous in memory until C++11.)

**Comment by MageKing17** [comment]
They weren't guaranteed to be contiguous by the standard, but most implementations were contiguous anyway. Since we now require C++11, there should be nothing dangerous about it (the only reason writing to the buffer underlying a string was discouraged before was because the memory wasn't guaranteed to be contiguous, as far as I'm aware).

See also: http://stackoverflow.com/a/25171213

**Comment by MageKing17** [comment]
Should be fixed since PR #304 was merged.
