### ISSUE TITLE
Bug: Starting FSO in German or French with Unicode Mode Enabled crashes

### ISSUE THREAD

**Issue by BMagnu** [scp-fs2open/fs2open.github.com#2994]
This is due to an issue in the strings.tbl (an FS2 retail table).
A discussion in the discord came to the conclusion, that this should be handled in-engine.

Detailed issue for German:
line 4224 of the strings.tbl has one ``."`` too much at the end of the Line, resulting in a parsing error.

Detailed issue for French:
Somehow, the Engine gets parsing errors on every comment in strings.tbl after line 5390. Remvoing all comments from the file lets the game start properly

**Comment by asarium** [comment]
At least the first issues is not something for the engine to handle. If you enable unicode mode then it is also possible to fix the parsing error.

For the second issue, do you have an error message?

**Comment by SelfGamer** [comment]
> If you enable unicode mode then it is also possible to fix the parsing error.

Could you elaborate on this? I'm not quite sure I understand.

> For the second issue, do you have an error message?

Error: strings.tbl(line 5932):
Error: Expecting int, found [; ------------------------------].

File: parselo.cpp
Line: 309

**Comment by asarium** [comment]
> Could you elaborate on this? I'm not quite sure I understand.
We only do those "fix data errors in the code" things for retail data. If you enable unicode mode via a mod table then you can also just distribute a fixed strings.tbl to fix the quote error.

I will take a look at the cause of the comment error when I have some time.

**Comment by SelfGamer** [comment]
If I understand correctly, this means that while strings.tbl being retail data, unicode support is not, so a mod that needs unicode should supply a corrected override for this table?

And thanks for checking the comment issue, that seems like a genuine bug.

**Comment by chief1983** [comment]
It does seem odd to me that a feature that a feature that is enabled via a simple boolean flag would require duplicating and including a fixed copy of a retail table just because of a bug in that retail data.  We have put fixes in the engine before for bugs in retail data that were exposed by SCP data.  While we can expect that anyone adding unicode support _can_ add this fixed table, that means that everyone doing so will _have_ to add this table for these languages in their mod, and will likely run into this same wall/error in the process of learning this requirement.  I think we should try to do a little more to reduce this headache if it's not too difficult to do so.  If that means a workaround, ok, or even just a way to catch when this particular issue happens and give the user more information.

**Comment by Goober5000** [comment]
I concur with @chief1983.

**Comment by SelfGamer** [comment]
Just found a piece of code in parselo.cpp that handles all these issues in-engine for non-unicode scenarios (Line 2358 - 2373).
``// stupid hacks to make retail data work with fixed parser, per Mantis #3072``
Not too sure why it doesn't work in unicode mode though

**Comment by asarium** [comment]
I did some debugging and the second French error is also caused by the misplaced quote in the German section (FSO basically things we are in a string and won't remove the comments).
