### ISSUE TITLE
Missing hud gauge filenames need to display warnings

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#3090]
If a HUD gauge bitmap is missing, no warning is given to the player, meaning that newer players won't realize they have a borked installation.

**Comment by Svedalrain** [comment]
My installation wasn't borked. I had all the right files. The problem was that I was running at a resolution less than the minimum resolution for the hud in hud_gauges.tbl

**Comment by JohnAFernandez** [comment]
Upgrading to a bug then.

**Comment by Goober5000** [comment]
Can someone write up steps to reproduce this?

It should be easy to add an error message in the appropriate spot, but the ticket doesn't indicate what resolution he was running at, nor whether hud_gauges.tbl was modified.

@Svedalrain

**Comment by Svedalrain** [comment]
Repro: start a mission (except VN script briefings) in Solaris 1.1.4, FSO 21.0 stable, with resolution set to 1024x768. Doing so either causes crash or launches normally, but the reticle in the center of the hud is missing.

Here's a [log](https://fsnebula.org/log/605f5a2f5eea5ac662d7bf71). Note line 254: the apng for the reticle failed to load.

Solaris's only hud in hud_gauges.tbl has a $min resolution of 1280x900, so I'm trying to launch Solaris with an unsupported resolution. Since switching to a resolution above 1280x900, the reticle appears every time. Same if I modify the tabled $min to 1024x768.

There is no obvious indication that my resolution was an issue, or that the reticle was absent because it failed to load (I assumed it just didn't have one), so I missed that it was at all connected to the crash until The E posted a call stack from a minidump.
