### ISSUE TITLE
FR: FRED Events Editor Feature List

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3184]
A non-exhaustive list of things FREDers want for the Events editor... arguably where we spend 98% of our time when making missions.

- [ ] Inline comments (read: not necessarily mouse over)
- [x] Resizable window (read: BIG for both events, and messages). Ideally the events tree would wrap to multiple columns if the window is large enough.
- [x] Keyboard shortcuts. All of them. Functioning. Ctrl-A, Ctrl-C, Ctrl-V, Ctrl-Z and more.
- [x] Colors to arbitrarily highlight events in arbitrary colors.
- [ ] Some ability to visually organize events. Whether that's indents, arbitrary spaces, event folders.. whatever. Events come in groups and often those groups are kind of like their own code function. OK, that feature works. Let's move it out of the way and do something else.
- [x] The Events window should verify that you actually intended to close the Events window when you hit cancel if you have unsaved events.

**Comment by the-maddin** [comment]
It would be nice to have a events filtering feature: a text field called "Filter events", and when the user enters "Alpha 1", all events containig sexps that have "Alpha 1" as an argument (or contain at any position the entered string) are highlighted, maybe by setting a (customizable?) text color.
Most generally useful would be, in my opinion, a full-text search of events, so the filter string "cargo" would match events using the sexp (is-cargo  ...) as well as those with a vessel "Cargo Container 77" or a variable "cargoes-destroyed-num".

**Comment by Goober5000** [comment]
Converted to checkbox form and checked off three items (resizable FRED, keyboard shortcuts, and colors) implemented in #3191.

Based on my investigation, inline comments are not possible in the MFC tree control.  Tooltip comments or @naomimyselfandi's script nodes are the best that can be done.

I haven't investigated, but my hunch is that visual organization of events are not possible either.  I ruled out indentation during the course of #3191, and I don't think arbitrary spacing is feasible either.  I also don't think event folders are feasible because they need the same kind of specialized UI as inline comments.

The only remaining issue is event window confirmation which ought to be pretty easy to do, so I will mark it as Good First Issue.

**Comment by Goober5000** [comment]
Checked off the last item since it was done in #3624.

**Comment by Goober5000** [comment]
Removed "good first issue" since the low-hanging fruit is all done.  I don't think the remaining requests are tractable (see my comments on Feb 10) so this should be considered for closure.
