### ISSUE TITLE
read_model_file seems to open binary files (i.e. POF) only and nothing else.

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#3218]
I tried to modify modelread.cpp to read non-binary files containing a 3d model instead of the binary POF files. However, it only reads POF files, but not other ones; in my case, a non-binary file. Attempting to read a non-POF model file returns an error.

Here's my link to the fork:
[https://github.com/bryansee/fs2open.github.com](https://github.com/bryansee/fs2open.github.com)

[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/5979920/fs2_open.log)
[Custom_FSO.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5979876/Custom_FSO.zip)

**Comment by The-E** [comment]
It doesn't work mostly because you haven't actually done any of the real work required to make it work.

Leaving aside the question of choosing OpenGEX as the additional format you want to add to the engine (which is a bad choice for several reasons, most pressingly the matter that it isn't widely supported by _anyone_), your problem is here, in modelread.cpp:
```
	if (strcmp(fext, "ogex") == 0 || strcmp(fext, "OGEX") == 0) {
		OpenGEX::OpenGexDataDescription fdata_desc;
		char* fbuf;

		DataResult result = fdata_desc.ProcessText(fbuf);
		if (result == kDataOkay) {
			const Structure *structure = fdata_desc.GetRootStructure()->GetFirstSubnode();
			while (structure) {
				structure = structure->GetNextSubnode();
			}
		}
	} else {
```
None of the data read through OpenGEX/OpenDDL is ever passed on to the rest of the engine. That's what you'll have to implement next.
