### ISSUE TITLE
FR: Geo-Mod (Geometry Modification)

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#3302]
In Red Faction and its sequel Red Faction 2, Geo-Mod was a game engine and its own feature developed by FreeSpace 2 developer Volition. It allows the player to alter level geometry with certain weapons, including making holes in surfaces. It was performed with a unique method by creating a new "empty space" object to approximate the size and shape of the damaged area. It is succeeded by Geo-Mod 2.0, which was developed for Red Faction: Guerrilla, but level border geometry can't be modified (using ragdoll physics simulation with a stress-based collapse model for buildings) and upgraded to "Geo-Mod 2.5" for Red Faction: Armageddon.

Understandably, there was talk of implementing Geo-Mod in space combat games such as FreeSpace 2, with the availability of its source code back in April 2002. With Geo-Mod, ships could tunnel through asteroids, planetoids, space stations, and even planet-sized objects with missiles, beams and certain laser weapons. Geo-Mod could be exposed to Lua scripting.

In the long-term, Geo-Mod could focus on PhysX-powered physics simulation. In this regard, it focuses on ragdoll physics simulation with a stress-based collapse model for gravity-dependent buildings. In Guerrilla and Armageddon most building geometry is destructable (though not certain large or important structures) and buildings will react in real-time to damage, eventually toppling over if enough structural support is lost. That way it works on planetary bombardment missions.

**Comment by The-E** [comment]
Beyond the requirement to do boolean ops on a model in realtime and updating the attendant collision geometry, applying geometry modifications violates a fundamental assumption of the engine, namely that every object of the same class shares the same model.
This is an incredibly huge task that does not actually deliver much in the way of added gameplay benefit in FSO.

**Comment by bryansee** [comment]
> 
> 
> Beyond the requirement to do boolean ops on a model in realtime and updating the attendant collision geometry, applying geometry modifications violates a fundamental assumption of the engine, namely that every object of the same class shares the same model.
> This is an incredibly huge task that does not actually deliver much in the way of added gameplay benefit in FSO.

What if Geo-Mod based on entirely physics-based, like those in Red Faction: Guerrilla and Armageddon? Does it still violate FSO's fundamental assumption even with ragdoll physics simulation with a stress-based collapse model for gravity-based ships and objects?

**Comment by The-E** [comment]
No matter which buzzword you throw at it, this will always be an issue.

**Comment by bryansee** [comment]
> 
> 
> No matter which buzzword you throw at it, this will always be an issue.

Why will this be an issue? Is it something else other than a huge task?

**Comment by Goober5000** [comment]
The first issue is understanding the scope of the problem.  The E mentioned an obstacle with model geometry and you asked him about physics.  That's not a promising start.

**Comment by bryansee** [comment]
> The first issue is understanding the scope of the problem. The E mentioned an obstacle with model geometry and you asked him about physics. That's not a promising start.

What's the obstacle with model geometry as @The-E mentioned? POF or BSP data?

**Comment by The-E** [comment]
Bryan, you need to learn how to communicate.

Here's the important bit of what I said:

> **applying geometry modifications violates a fundamental assumption of the engine, namely that every object of the same class shares the same model**

This means that a lot of code that is currently built around the assumption that geometry data is immutable and shared between objects will need to be checked and, if necessary, changed to accommodate for models being changed by whatever method you use to make "geomod" effects.
It's a huge task to do that and make sure that the changes needed do not impact non-geomod data in any harmful way.

_This has not a single thing to do with game physics._ "Ragdoll physics simulation" and "stress-based collapse model", which are two of the buzzwords you threw in there presumably without actually understanding what they mean, what the technologies behind them are and what they do (yes, I know you can quote wiki articles on the subject, I've seen you do it, that does not mean you actually _understand the words you're using_), **have nothing whatsoever to do with this issue**, because it is fundamentally about the engine's ressource management.

**Comment by bryansee** [comment]
> This means that a lot of code that is currently built around the assumption that geometry data is immutable and shared between objects will need to be checked and, if necessary, changed to accommodate for models being changed by whatever method you use to make "geomod" effects.
> It's a huge task to do that and make sure that the changes needed do not impact non-geomod data in any harmful way.
I've got an idea: assign a unique id to the ship that's going to have "geomod" effects.

> As an example, look back on that PR you made to integrate OpenDDL. There, you managed a couple of things correctly: You actually put the correct files in the correct place and you managed to identify the place where the engine starts loading model data - but then you failed to actually understand the example code you copied from the OpenDDL examples, so you were stuck asking "why doesn't this do anything", something that _anyone_ who is at the level required to work on FSO could see within seconds.
> The cold hard truth is that you, Bryan Dunsheng See, are not qualified for this work, no matter how much you wish differently. You are not qualified enough as a coder to write the code you need or want to write, and you are not qualified enough as a communicator to start or even contribute meaningfully to the discussions we're having (the fact that you aren't on the discord doesn't help either).

I'm sorry for the PR I made to integrate OpenDDL. Just give me another chance, because I'm working on something small (look at Lost in the Mist).

**Comment by The-E** [comment]
Thank you for the reply, it makes it much easier to tell you, over and over again, _that you are not competent to comment on this matter_
> I've got an idea: assign a unique id to the ship that's going to have "geomod" effects.

That's not an idea. That's step 1 of a long, long lists of steps towards a solution. It is, in fact, such an obvious requirement that it doesn't even need to be brought up; so obvious in actual fact that _the engine already does this_ simply because there is no other way to do _anything_.
 
> I'm sorry for the PR I made to integrate OpenDDL. Just give me another chance, because I'm working on something small (look at Lost in the Mist).

I am not asking you to be sorry. Making a bad and obviously nonfunctional PR isn't _offensive_, it's just _stupid_ and doesn't do a whole lot to convince me, let alone anyone else, of your abilities.
You've had tons and tons of chances over the years to show your stuff. You still do, with or without my approval. But _every single time_ you have tried to contribute to FSO, the same issues come up. Namely, you not understanding the problem you're trying to solve, you not understanding the code that you need to write, and you not understanding _why_ the solution you're proposing is invalid and, most importantly, _despite being told over and over again that these issues exist_, you still persisting in your behaviour.
You need to change. You need to work on your skills. You don't need to become a professional developer like most of us are, but you absolutely need to learn some of the skills of this profession, _and we are not here to teach you_. It's not a service we can provide to you because _you are seemingly incapable of learning in this environment._
I don't know what's right for you. But I can tell, with absolute certainty, that work on FSO, or for the SCP, isn't it.

**Comment by z64555** [comment]
If any party involved still has something to say, please use another medium such as the hard-light forums or discord, as much of the focus in this discussion has shifted too far away from codebase.
