### ISSUE TITLE
Joystick support broken?

### ISSUE THREAD

**Issue by Pulstar85** [scp-fs2open/fs2open.github.com#3311]
It's been a while since I updated the binaries but now with 21.0 and even 19.0 the joystick isn't registered at all in-game (both 32/64bit).. legacy FSO projects still work fine. Perhaps I'm missing something?

**Comment by z64555** [comment]
What launcher are you using.

**Comment by Pulstar85** [comment]
wxLauncher, yes I use stable builds.

**Comment by NovachenFS2** [comment]
The issue is, that wxlauncher is released with an outdated SDL2.dll today. Unfortunately no of the original developer fixed that and released an update.

I offer an customized version of wxlauncher which uses a newer SDL2 and so fix this issue.

[SDL2.zip](https://github.com/scp-fs2open/fs2open.github.com/files/6177316/SDL2.zip)
Extract the SDL2.dll in the wxlauncher/bin folder and it should work again.

**Comment by Pulstar85** [comment]
Thank you kindly!
