### ISSUE TITLE
FSO 21.0 Stable won't share or release console output to launchers

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#3317]
Caused by #2988, certain launchers that use the console for debugging, such as Knossos, are unable to do so because FSO won't let it.

@ngld discovered the issue while trying to upgrade Knossos.

Proposed solutions include:
* Building FSO with the SUBSYSTEM: set to CONSOLE.  This has the downside of showing a console at awkward times, even when its not needed
* Have FSO grab console on activation of specific flags
* Have FSO grab console only when it needs it, then release when its done.

**Comment by asarium** [comment]
I would be in favor of adding a command line flag for this. As far as I am aware, this is only needed in some very specific circumstances so changing the default behavior (e.g. with `/SUBSYSTEM:CONSOLE`) is not worth it.

**Comment by ngld** [comment]
> certain launchers that use the console for debugging, such as Knossos, are unable to do so because FSO won't let it.

Just to clarify: Knossos can use the console just fine. The issue is that FSO is printing its own output to the console as well which makes `-get_flags` unusable and in turn breaks FSO launching in Knossos itself. A debug build that can't launch FSO isn't too useful so I'd be happy to see this fixed.

> Have FSO grab console only when it needs it, then release when its done.

I'm not sure if this solves the problem since the issue isn't that FSO attaches to the launcher's console. The main issue is that FSO prints it output to the wrong destination (the console instead of its standard output).

Regarding possible solutions:
* If FSO only uses the console when a special flag is passed, it'd fix the issue without requiring a change in Knossos or other launchers.
* If the default behavior is printing to the console and the previous behavior (printing to standard output) requires a flag, I'd have to pass that flag which is probably fine if previous FSO versions ignore it. I can't check the FSO version before the `-get_flags` call so whatever solution we come up with shouldn't produce errors when used with previous FSO versions.
* Another option which might be easier to use would be environment variables. I could set an env var in Knossos which FSO could use to check if it's manually launched by a user or through Knossos. This would allow FSO to print to the console when launched manually and print to stdout (like it did before) when launched from Knossos.
