### ISSUE TITLE
Graphical glitch/assert when opening options menu as a specific pilot

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#3321]
When I try to open the options menu with a certain pilot, in debug builds I get an assert, and in release builds I get a graphical glitch.
My other pilots aren't affected. I was able to access the menu without a glitch or crash using this pilot earlier.
I did this all with the March 24th 2021 nightly. I still get the graphical glitch and assert with the borked pilot and only the borked pilot in 21.0.0. I haven't yet been able to break another pilot file in this way.
[Here are the pilot's files.](https://github.com/scp-fs2open/fs2open.github.com/files/6198781/BorkedPilot.zip)
[Here's a log.](https://fsnebula.org/log/605b4c79b3f5418863d7bf59)

**Comment by Svedalrain** [comment]
![screen0125](https://user-images.githubusercontent.com/73649993/112344939-f9e02280-8c9a-11eb-824f-798854ad446c.png)
Screenshot of the graphical glitch in release builds. The buttons that should be in the bottom right corner are still fully functional.

**Comment by BMagnu** [comment]
Simply put, the Joystick Sensitivity (a value between 0 and 9) of this pilot is 16989 (it's what's read from the CSG file).
Since the options menu cannot render this, it throws this assert.
If you'd try to actually connect a joystick and use it, the controls code should throw an assert as well.
_Why_ the pilot file has this value I don't yet know.

**Comment by Kiloku** [comment]
Would clamping the values read from the file between 0 and 9 be a valid fix?
