### ISSUE TITLE
User-bound mouse buttons are cleared or ignored

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#3322]
In recent nightlies, I effectively cannot bind any mouse button to seemingly any control. Default bindings for joy-0 work perfectly for the corresponding mouse buttons.

When I bind mouse buttons to anything, then accept,, and return to the controls screen from the first options screen where difficulty can be set, all mouse buttons stay bound.
If I instead bind mouse buttons and exit to the mainhall, then return to the controls screen, mouse buttons are no longer bound. The right column shows "None" bound even if I had replaced an existing joystick binding. 
If I bind mouse buttons mid-mission, the mouse buttons still don't do anything, but returning to the controls screen still shows that they are bound. The default joy-0 button bindings work for the mouse, but I don't know how to bind them to arbitrary keys.

**Comment by z64555** [comment]
The problem is that Controls3 has some feature code that's meant to split up the mouse from doubling up with the joystick bindings, however the actual split was done later in the Controls4 and 5 branches.  Some remnant code that did the mouse split got overlooked, and allows users to bind the mouse to a control within the menu, but not effectively save it to file nor will the bindings take effect in-mission.

I should have a fix soonish.
