### ISSUE TITLE
Interval & Delay use Msecs flag gets added erroneously.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3355]
I don't see a rhyme or reason for this. It could be related to a certain build or it could just be totally random. In my case, I tracked down the flag being added around Jan 26, but I could not tell you what FSO build I was using at the time.

The missions got this flag added when I opened the missions in FRED to add a couple new events, iirc. The way the flag is added does not seem to follow a pattern. See this screenshot of an SVN diff. Two events that are nearly identical where one had the flag added and another did not.
![image](https://user-images.githubusercontent.com/7740469/113439422-276e4f80-93b0-11eb-9733-cb59b99b6b05.png)

The flag is not added to all events. Just some. This is, imo, a really big issue. I cannot trust FRED to not break past missions in the background if I happen to open those missions to change or fix anything else.

**Comment by Goober5000** [comment]
I have not been able to reproduce this, and my code inspections haven't yielded any leads either.  This definitely warrants attention as a big issue; I'm just not certain what to do next.

The only thing I can think of is that some other part of the code is having an unintentional side effect of setting this flag - perhaps due to a memory leak.  But it could just as easily be something else.
