### ISSUE TITLE
Cutscene Flags Don't Work On Librocket Interfaces

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3367]
@asarium 

Cutscenes that should play before Command Briefing stages do not play. This will affect all stages should the HD UI ever be completed any further.

These flags specifically. (You cannot currently add them via FRED.) https://wiki.hard-light.net/index.php/Cutscene_flags

**Comment by Goober5000** [comment]
To document what's been going on behind the scenes, I looked into this a week ago and messaged with @asarium about how it could be solved.  It's basically a two-part fix.  Part 1 is to implement the required scripting function, which is now done.  Part 2 is to modify the UI script to use the new function.

Essentially, since the custom UI is controlled through its own script, the script has to handle everything associated with a state transition.  And that includes, in this case, playing the cutscene.

I'll have to defer to @asarium on how the script should be modified.  I assume the relevant file to change is `ui_system.lua`, but I don't know exactly where the cutscene should be plugged in.

**Comment by MjnMixael** [comment]
I assume this is another case of abandoned librocket UI. I have not yet heard from @asarium on adding this functionality to the necessary lua files.

**Comment by Goober5000** [comment]
I wouldn't call it abandoned.  I assume @asarium is either busy or occupied with RL priorities.

**Comment by z64555** [comment]
Setting to low priority and assigning it to 21.6 so it hopefully doesn't get buried again.

**Comment by Goober5000** [comment]
I'm not familiar with what is necessary for Part 2 of this.

**Comment by MjnMixael** [comment]
Resolved
