### ISSUE TITLE
adjust-audio-volume [effects] doesn't fade beams

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3414]
This sexp currently will not fade the volume of any currently firing beams. After the beam finishes, the next beam will be adjusted properly. I suspect this goes deeper and doesn't actually adjust the volume of any currently playing effects (it does fade music; I did not test voice), but I could be wrong. It's easy to tell that it doesn't fade beams. Harder with lasers and stuff.

Test mission attached. Press 1 to fire a beam and begin a fade out of the audio.
[BeamSoundFade.zip](https://github.com/scp-fs2open/fs2open.github.com/files/6430250/BeamSoundFade.zip)

**Comment by jg18** [comment]
@MjnMixael Thanks for the test mission. So far I've just dug into the code.

Turns out the main beam firing sounds are in a special category of "looping 3D" sounds that the `adjust-audio-volume` SEXP currently doesn't handle.

There are a few other "looping 3D" sounds, but I haven't yet looked at what they are.

(Details for coders: these are the sounds you get from calling `snd_play_3d()` with `looping` set to `1`.)

The beam sounds (and maybe other "looping 3D" sounds) also need to be able to be paused (e.g., when you go to the Options menu) and then unpaused with their volumes from before the pause. It looks like `beam_unpause_sounds()` just sets the beam sound volumes to full, which isn't what we want.

I have some ideas on what to do but will need to think and experiment with the test mission.

**Comment by jg18** [comment]
Ok, t he other "looping 3D" sounds are "object-persistent" sounds (coders: see objectsnd.cpp), which is for things like other ships' engine wash and turret/subsystem (in)operation (except for turret fire).

I guess all of these sounds should also be affected by `adjust-audio-volume`.

Still looking into the best way to implement this.

Btw, one looping (non-3D) sound that *isn't* affected by `adjust-audio-volume` is the player's own engine. That's the only exception I've noticed so far.

**Comment by Goober5000** [comment]
Are you referring to `ship_p.wav`, which is "engine sound (as heard in cockpit)"?  Because EngineSnd isn't played on the player's own ship.

**Comment by jg18** [comment]
@Goober5000 I was referring to `Player_engine_snd_loop` which is set in `update_throttle_sound()` in hud.cpp by calling `snd_play_looping()` with `scriptingUpdateVolume` set to `FALSE`.

I'm not exactly sure what sound that var corresponds to, though.

But upon further study, that means that its volume is updated for AAV only by calls to `snd_set_volume()` with that sound specifically and not on every frame (see `snd_do_frame()` for handling AAV for non-3D looping sounds).

**Comment by z64555** [comment]
Does this bug affect any published or in-progress mods in a critical manner?

**Comment by MjnMixael** [comment]
Affects BtA1.

**Comment by jg18** [comment]
@MjnMixael The fix for this was just merged. Can you verify when the next nightly comes out? Asteroth tested it before the merge. Thanks!

**Comment by MjnMixael** [comment]
Confirmed fixed. Thank you.

**Comment by jg18** [comment]
Awesome! Closing.
