### ISSUE TITLE
Unable to bind controls in Solaris specifically.

### ISSUE THREAD

**Issue by DankMemer90** [scp-fs2open/fs2open.github.com#3427]
I am unable to change my controls when playing Solaris. The upper left corner has the text "Controls: Default" whereas other games have it say "Controls: Custom" if that helps. Specifically what happens is that I am able to change the bindings, but clicking accept doesn't exit the menu so I can only leave via ESC which does not save the changes.

**Comment by DankMemer90** [comment]
Found issue: Conflicts in the default bindings for Solaris, it lets me save changes after clearing this conflict.

**Comment by z64555** [comment]
There's a bug with how the "Conflicts!" message was displayed.  The user's normal resolution of 2560 x 1440 had somehow forced the text to be drawn off-screen, as evident by having the user temporarily change their resolution to 1024x768.

The other cause of this issue is something with the default bindings of Solaris being in conflict, which is still under investigation.

**Comment by z64555** [comment]
Cause of the binding issue stemmed from a logic error in the ControlsConfigDefaults.tbl wherein legacy usage of `$Key Mod Shift:` to modify the default binding to be `Shift+` and/or `Alt+` would end up corrupting the binding.  There should be a PR to address this by the end of today.
