### ISSUE TITLE
Review uses of vm_matrix_x_matrix

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#3484]
According to #3470, `vm_matrix_x_matrix` multiplies its arguments in the wrong order.  The codebase needs to be reviewed to check that all uses are correct.  I know that the submodel code, at least, was written assuming the other order, so I'm a little surprised it seems to work the wrong way around.

Assigning to @Baezon as he seems to have the best handle on vector math, though I will review the submodel and docking code in the near future.

**Comment by z64555** [comment]
Assigning to bug triage for project management. Deferring milestone to 21.6.

If there has been any progress towards this issue, please speak up.

**Comment by Baezon** [comment]
I've reviewed some of them, and everything so far had looked good, I've just been busy. 

If it's any consolation, it's less that order is *wrong* versus simply being reversed from the standard convention. As long as the person using it knows this (I think its safe to assume whoever did it in volition did) and the ordering remains consistent for a particular usage, it should be ok.

**Comment by Goober5000** [comment]
Well, when I rewrote the submodel code, I assumed it followed the standard convention.  Despite this, the submodel code actually does work.  This means that either matrix multiplication is commutative (it isn't) or some unknown interaction is causing the observed cases to work correctly.  But if there is such an unknown interaction, we need to understand it so we know whether the unobserved cases are behaving as they should.

**Comment by Baezon** [comment]
If you're referring to functions like this one https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/model/modelread.cpp#L4169

Then it *is* actually correct. Which is to say that order of arguments is "reversed" from the normal mathematical convention, which matches `vm_matrix_x_matrix`, which takes it's arguments in that "reversed" form. The 'standard' convention would put the 'accumulator' matrix `tnorm` on the right, and the parent matrices left-multiply into it repeatedly. But it is revered from that in the code because `vm_matrix_x_matrix` takes its arguments the other way around and so the code is correct.

**Comment by Goober5000** [comment]
Given @Baezon 's previous partial review, plus the subsequent clarification, plus the fact that the code still works as it should, I think the objective of this issue has been satisfied.
