### ISSUE TITLE
Malformed tables can make infinite loop on launch in debug

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3539]
So far the only factor seems to be leaving off a quotation mark in a weapon flag. My last debug log is half a million lines of 
```
WARNING: "wm-m-gtva-S-tiamat-wep.tbm(line 75):
Warning: Missing quotation marks in string list." at parselo.cpp:310
WARNING: "Unexpected end-of-file while looking for line number!" at parselo.cpp:251
wm-m-gtva-S-tiamat-wep.tbm(line 75): Warning: Missing quotation marks in string list.
WARNING: "Unexpected end-of-file while looking for line number!" at parselo.cpp:251
```
If just removing a quote from a weapon table doesn't repro let me know and I'll try to build something for it.

**Comment by jg18** [comment]
@EatThePath thanks for filing this and for doing some digging.

IMO the line
```
error_display(0, "Missing quotation marks in string list.");
```
in parselo.cpp should call `Error()` and abort/crash instead of calling `error_display()`.

AFAIK no compiler/interpreter of any mainstream programming language would accept input that was missing a `"` and IMO FSO/FRED shouldn't, either (no offense ETP 🙂) although an infinite loop is obviously unacceptable behavior.

We *could* try to "infer" the missing `"` but I think the result would be unexpected and potentially unpredictable behavior. Better to fail fast and fail noisily, in my view.

Thoughts?

**Comment by Goober5000** [comment]
Parsing functions should always call `error_display`, which itself calls Error or Warning.  You could change it from 0 (warning) to 1 (error) though.

The real problem is that the parser isn't advancing when it detects this error.  It should probably move to the next line.

**Comment by Goober5000** [comment]
@EatThePath please test and verify that #3545 fixes the issue.

**Comment by EatThePath** [comment]
@Goober5000 I pulled and tested, can't find a way to get trapped in the loop again, so seems good to me.
