### ISSUE TITLE
Feature Gap: Screen Shake not allowed in 3rd person view

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#3563]
Mods should be able to force screen shake to also occur in third person camera views.

I haven't taken a look at the code, but I anticipate this to be an easy addition.

**Comment by z64555** [comment]
Ooooh, there was some salt about this awhile back.  Some folks don't like the screen shake, in particular from weapons such as the Maxim.  There wasn't a consensus on what to do about it, however, since the screen shake not happening in third person was seen as a bug by an SCP dev and as a feature by the user who was complaining about screen shaking.

**Comment by X3N0-Life-Form** [comment]
So now there is a launch flag to disable shudder screenshake altogether, IIRC.
