### ISSUE TITLE
FR: Randomize rotation of 2d shockwaves

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3603]

**Comment by Baezon** [comment]
This seems like not a great idea, there's no bitmap that can survive looking good at all angles, and more importantly seems only to serve the exact function that 3D shockwaves already provide. In what way is a rotated 2D shockwave superior to a 3D shockwave?

**Comment by z64555** [comment]
Probably would have to show some pictures of what's going on and what is desired.

**Comment by EatThePath** [comment]
> 
> 
> This seems like not a great idea, there's no bitmap that can survive looking good at all angles, and more importantly seems only to serve the exact function that 3D shockwaves already provide. In what way is a rotated 2D shockwave superior to a 3D shockwave?

As in, still a planar billboard but spun randomly along the viewing axis. I believe you mentioned nebula poofs do this, and it's been suggested many times as a fireball/particle enhancement

**Comment by Baezon** [comment]
Oh, I see, I misunderstood what you meant. Based on the reading of the code I did, it seems they should have this ability, let me confirm...

**Comment by EatThePath** [comment]
One wrinkle, in discussing this with Kestrellius he pointed out this needs to be optional, because there's potential artistic use to the fixed angle. While I don't think I've seen anyone really use that for shockwaves, I can imagine how one might.

**Comment by Baezon** [comment]
Prognosis looks pretty good, its rendered as a "rotated" bitmap, which means that it keeps track its rotation as you bank, and despite what the wiki says $shockwave rotation is used for this also, although only the pitch value. And additionally there's a conversion bug here which means you'll never be able to move it by more than a few degrees.

With that bug fixed you should be able to arbitrarily rotate it, and I think since shockwaves are explicitly spherical its totally reasonable to randomize its rotation a la #2572, if the rotation is left unspecified.

**Comment by Baezon** [comment]
Actually, taking another look at it #2572 *did* in fact in effect randomize rotation of 2D shockwaves as well, but it's only due to that bug that resulted in this being not evident. Which means, the only thing in the way of this is that bug, thus qualifying it for the stable ;)

**Comment by EatThePath** [comment]
Oh, well in _that_ case... 😁

**Comment by z64555** [comment]
So, what?  With the bug fixed, the feature request is fulfilled?

**Comment by EatThePath** [comment]
once merged this will be closed by #3604 yes
