### ISSUE TITLE
FRED List cleanup when using ship flag "No_Fred"

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3633]
If you set a ship flag No_Fred it does remove the ship from the list in FRED, however it leaves behind a blank space. So if you have a lot of these then it creates a massive blank space in the FRED list. Ideally, instead of just blanking out the space, it would just remove the space entirely. See the attached screenshot where I have 31 ships listed as No_Fred and have a long way to scroll to find Waypoint and Jumpnode.

![image](https://user-images.githubusercontent.com/7740469/131367175-c7f6dc02-9dc6-4dcd-acb4-ed01d44fd1c4.png)

**Comment by Goober5000** [comment]
Good point

**Comment by jg18** [comment]
As I suspected, these spacers exist because FRED depends on offsets in the `m_new_ship_type_combo_box` lining up with an index used elsewhere (`cur_model_index`). For example, see how the two are used together in `CFREDView::OnCmdMsg()`.

While this is undoubtedly fixable, it'll need to be done very carefully, to avoid introducing regressions.
