### ISSUE TITLE
Controls 4/5: Loading v3 Player Profile in FSO v21.4 or before results in the loss of saved controls in the current control profile for that player.

### ISSUE THREAD

**Issue by JadedDragoon** [scp-fs2open/fs2open.github.com#3667]
Tested on Retail FS2 with the controls4/5 pr build.

### Steps to reproduce:
**Stage 1**
1. Launch Controls5 build.
2. Create new pilot.
3. Select pilot and enter game to the mainhall
4. Navigate to `Control Config` in `Options`.
5. Configure some controls using multiple SDL input devices. (the two halves of the x56 HOTAS in my case)
6. Click `Accept`.
7. Name control profile and accept it.
8. Close game.

**Stage 2**
1. Launch non-controls5 build (12.2.0, in my test case).
2. Select pilot created in Stage 1 and enter the game to the mainhall.
3. Exit FS2

**Stage 3**
1. Launch controls5 build.
2. Message notifying that the profile created under Controls5 has been updated to use the new format used by Controls5. (see "Erroneous notification of re-conversion" below)
3. Select pilot created in Stage 1 and enter the game to the mainhall.
4. Navigate to `Control Config` in `Options`.

### Expected Behavior:
At a minimum, accidentally or otherwise opening a v3 player file with a <=21.4 build should not result in the controls being nuked.

### Actual Behavior
- All Joy1+ controls are missing.
- Sometimes controls are completely re-arranged with Joy0 controls being repositioned to the second column.
- Sometimes default (retail) controls are restored in the first column even on controls that were previously unconfigured.
- Cycling all the way through control profile back to the one you started on _appears_ to restore the control profile. In-fact, it _does_ for the duration of the current game session. However, the controls are not saved to disk and only apply in memory. Once the game is closed, the "restored" settings are lost. On subsequent launches the settings cannot be "restored" this way.

### Erroneous notification of re-conversion.
```
Information: Successfully converted playerfile to v3.  Please rebind your mouse controls, if any.
File: plr.cpp
Line: 616
```

Attached is the relevant player data at the end of each stage.

[controls5 overwriten player files](https://github.com/scp-fs2open/fs2open.github.com/files/7198587/controls5.overwriten.zip)

**Comment by z64555** [comment]
Ok hold up, so the complaint here is that using a pilot in Controls5 makes it so that the same pilot's bindings are nuked in trunk (21.4)?

**Comment by JadedDragoon** [comment]
if a v3? pilot with a control profile set is loaded in a version not supporting such, and then loaded with controls 5 again controls 5 seems to erroneously overwrite the player's current control profile with settings from somewhere else... i assume from the player profile.

**Comment by z64555** [comment]
Ok, so, the "erronouse" re-conversion is actually not in error.  Whenever you load up FSO it loads your default pilot and saves it again for some reason.  Thus, whenever you load an older FSO version it down-converts the pilotfile back to v2, then when you load the newer FSO with controls5 is does the conversion again.

I did make a provision to keep the pilotfile bindings for forward compatibility, but its not perfect since the down-conversion strips off the secondary binding feature (the second column of bindings).

**Comment by JadedDragoon** [comment]
It seems a little more than not perfect. Seems a bit like a landmine for players to lose their controls to. It's fine if the pilot file needs reconverting... it's significantly less fine if it destroyed the controls binding in the control profile in the process.

Can't this be made to recognize that a control profile already exists and not over-write it? Or whatever it is that ends with controls being irrevocably lost?

**Comment by z64555** [comment]
To address the issues in itemized fashion:

* All Joy1+ controls are missing.
  * Player files <v3 do not support joystick bindings other than for Joy0.
* Sometimes controls are completely re-arranged with Joy0 controls being re positioned to the second column.
  * This is intended behavior, since retail allows controls to be bound to keyboard and joystick/mouse.  Controls5 re-designed this feature to be more general in that you could bind at most two controllers to a control, regardless if its keyboard, mouse, or any of the joysticks.  The bound Keys are in the first column while bound joystick/mouse buttons are in the second column.
* Sometimes default (retail) controls are restored in the first column even on controls that were previously unconfigured.
  * This is probably a bug in the save mechanism.
* Cycling all the way through control profile back to the one you started on appears to restore the control profile. In-fact, it does for the duration of the current game session. However, the controls are not saved to disk and only apply in memory. Once the game is closed, the "restored" settings are lost. On subsequent launches the settings cannot be "restored" this way.
  * Control bindings for player v3 versions have been taken out and saved as their own file separate from the pilot file.  At worse, the pilot file "forgets" the selected preset when it gets down-converted, but the bindings should not be overwritten. when its re-converted.  This may be a bug with the up-conversion process that's overwriting the preset.

**Comment by JadedDragoon** [comment]
> * Cycling all the way through control profile back to the one you started on appears to restore the control profile. In-fact, it does for the duration of the current game session. However, the controls are not saved to disk and only apply in memory. Once the game is closed, the "restored" settings are lost. On subsequent launches the settings cannot be "restored" this way.
>   
>   * Control bindings for player v3 versions have been taken out and saved as their own file separate from the pilot file.  At worse, the pilot file "forgets" the selected preset when it gets down-converted, but the bindings should not be overwritten. when its re-converted.  This may be a bug with the up-conversion process that's overwriting the preset.

This is the core issue I'm reporting.

**Comment by z64555** [comment]
I've pushed some changes to the Controls5 branch, please check them out.  They namely resolve issues with the control bindings being displayed in the training missions.

I'll try to tackle the issues with loading the pilotfile.

To state again, as an attempt at forward compatibility the pilotfile saves the bindings as best it can.  However, since it is not a perfect duplication of a preset, whenever the pilotfile gets re-converted the bindings for mouse and joy-1 through 3 will be "lost."

I can possibly make the conversion logic check first to see if there's already a preset file that was generated from an earlier conversion and try to use it, but in general the situation is going to still be a mess.

**Comment by JadedDragoon** [comment]
Checking to see if a control profile already exists and not overwriting it would solve most of my concerns, I think.

**Comment by z64555** [comment]
Ok so uh.

My attempts at the conversion logic were shaky at best, mainly because of the fact that multi-joy splits up the mouse bindings away from the joystick bindings.  Although it might be possible to do a full, stress free conversion for the user, on the code side of things it would complicate things to support backward and forward switching between FSO versions while keeping the same .PLR and .CSG data.

So, with sadness, I am officially dropping forward compatibility support from the Controls5 PR.  Meaning, conversions from a Pre-Controls5 PLR and CSG to a post Controls5 version is one-way only, and the PLR and CSG data won't be usable with version Pre-Controls5.
