### ISSUE TITLE
Debug text in visual novel script

### ISSUE THREAD

**Issue by the-maddin** [scp-fs2open/fs2open.github.com#3795]
In the current nightly, FASTDBG build on Linux, compared to last stable, an issue appeared in the visual novel script: Every scene is suffixed with (no wavefile for voice). Yet the voice is played correctly.
The offending text is from a debug section of [missionmessage.cpp](https://github.com/scp-fs2open/fs2open.github.com/blob/5eb924cedcabe1b9d46d533b83f667b049d90b6c/code/mission/missionmessage.cpp#L1596), so maybe, by fixing the script loading order, an older bug was uncovered?
Log:https://fsnebula.org/log/619c34af667b4d76932001d7

**Comment by BMagnu** [comment]
The VN script plays the sound itself and does not rely on FSO to play the sound with the message (presumably to be able to stop it if you interrupt the voiceline).
However, since the messages are routed through FSO's messages, if sound for ingame messages is active, that will always append this to any message that does not have sound.
Hence, this is actually the expected behaviour, since the actual message being sent, has in fact no wavefile attached.

**Comment by Goober5000** [comment]
It's also worth noting that the "no wavefile" message is only appended in debug builds.
