### ISSUE TITLE
FSU Osiris spews debug warnings while switching secondary banks

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3808]
> Warning: Tried to rotate submodel uflap03-R by -0.96, but velocity was 0! Rotating with velocity 1...
> File: modelanimation_segments.cpp
> Line: 294

And here's the animation code in question:

```
  $Subsystem: uflap03-R,      0, 2
    $Flags: ( "untargetable" )
    $animation: triggered
    $type: secondary-bank
      +sub_type: 0
      +delay: 0
      +relative_angle: -54.736,30.0,-54.736
      +velocity: 80,80,0
      +acceleration: 40,40,0
      +time: 250
```

Encountered when a hostile Osiris tried to arm its third secondary bank and encountered every frame until I gave up and quit.

**Comment by BMagnu** [comment]
That is in fact a correct warning, and should be fixed in table.
Admittedly a bit annoying that it triggers every frame, but what you have there is a target rotation in all three axes, but only two of these have a non-zero velocity / acceleration. Since that means it couldn't reach the target angle, it'll warn you about it (and assume a speed of 1rad/s to get things moving at all).
