### ISSUE TITLE
Coverity false positives

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#387]
Apparently Coverity doesn't process `Assertion` statements correctly when analyzing our builds.
The defect 1320549 is an obvious false positive because the `Assertion` should trap it but Coverity doesn't process that correctly.
Can we somehow mark our assert macros as killpaths for Coverity?

**Comment by MageKing17** [comment]
It's not a "false" positive because the Assertion is only checking that the value is not -1, not that it's >= 0. On the other hand, it's a false positive because `get_index_sexp_variable_name()` can't return a negative value other than -1. On the other other hand, `get_index_sexp_variable_name()` could conceivably change in the future and this code would be (slightly) improved by making the Assertion catch more potentially-invalid indices.

We can either mark this as a false positive, or modify the Assertion, however this isn't a failing of Coverity not knowing that Assertion is a killpath.

**Comment by asarium** [comment]
That defect didn't show the issue very well, take a look at 1320552. Coverity says "Condition !(shipnum != -1), taking true branch" which would terminate the execution. `Assert` is handled correctly so I am assuming someone marked that function as being a killpath but neglected to do the same with `Assertion` which is the reason for this issue so we can determine how to mark `Assertion` correctly to reduce the number of false-positives.

**Comment by niffiwan** [comment]
I'm not sure why this is occurring; I thought that Assert and Assertion were both treated equally as killpaths. I'll have to check out the exact issues.

**Comment by niffiwan** [comment]
Right, there does seem to be some sort of issue. I'll have a bit of a play around with the modeling file.

**Comment by niffiwan** [comment]
Right, finally sorted out how to get both Assert & Assertion correctly treated as killpaths.

**Comment by asarium** [comment]
Thanks for the fix, I think this means this issue has been solved.
