### ISSUE TITLE
Arrival Delays are Not Working Correctly

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#3946]
As first noticed by Anatares, mission time starts ticking while in the briefing, which affects in-mission times. For example, If I set the delay of a ship to be 5 seconds in, and wait around it the briefing for at least that long the ship is arrived when the mission starts. Introduced by #3879.

**Comment by Goober5000** [comment]
The title is a little misleading; mission time does not actually run during the briefing, and I confirmed it just now.

Timestamps *do* run during briefing, but they are rewound before the mission begins.  The in-mission counter confirms that the timestamps were rewound correctly, since time and timestamps now derive from the same source.

Something is definitely wrong with arrival delays though, because that is somehow affected by waiting around in the briefing.  Testing proved that this situation could not occur, and yet it is occurring.

**Comment by Goober5000** [comment]
Some weird results while trying to track this down...

1) The timestamp was paused at 8973 during mission load.  The Hope's timestamp was correctly set to this plus 25 seconds, or 33973.
2) The timestamp iterated as expected during the briefing.  After the `GS_EVENT_ENTER_GAME` event, the timestamp was correctly reverted to 8973.
3) However, Missiontime at this point was -2145.02 seconds.  One frame later it was -2144.52, then -2144.02, then -2143.52, and then it finally ticked over to 0.27.
4) When Missiontime reached 0.27, the timestamp was 9976, which implies a start-mission timestamp of 9706.
5) The Hope's timestamp of 33973 elapsed on schedule at 33976, but the Missiontime at this point was 24.52 which implies a start-mission timestamp of 9456.

**Comment by wookieejedi** [comment]
Good points, I've updated the name. Oh interesting... this is one tricky bug.
