### ISSUE TITLE
Pilot conversion notification not displayed after the first pilot

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#3980]
Expected: Pilot conversion infobox should be displayed whenever a pilot file is upgraded to v5, but only once for each pilot
Actual: The infobox is only displayed once, ever

Steps to reproduce:
1) Create a pilot on a 21.4 build
2) Launch 21.5.  The infobox is displayed
3) Create another pilot on a 21.4 build
4) Launch 21.5.  The infobox is not displayed, even after selecting and launching the newest pilot

**Comment by z64555** [comment]
Ok, so... this reveals a bit of a tangle with the conversion process.  The conditional that triggers the info box is looking for if the bindings already have a preset in the `\presets` folder, if it does, then the conversion message isn't displayed but the pilot file is still technically converted.

I say technically converted, because the infobox occurs during the loading stage of the player file, instead of on the saving stage or otherwise its own dedicated conversion function.  This is the "tangle."

Should the bindings/preset not be unique (as is the case of having default binds, or binds that are the exact same as a previously loaded pilot) the infobox won't trigger, but FSO will save/convert the file into the new version.

**Comment by Goober5000** [comment]
Ok, here's what I suggest...

1) When the pilot file is read, and the version number is less than the controls5 version, a flag should be set on the player struct, indicating as such
2) When the player gets to the main hall, if this flag is set, display the infobox using the in-game UI.  (Put the check in the same place as the new user tips.)  Once the infobox is displayed, clear the flag.
3) This flag can be transient and doesn't need to be saved in the player file, since it is only meaningful during a game instance.

This avoids the preset issue, avoids displaying the infobox for players that are only loaded but not used, and uses the in-game UI rather than a weird system window.

**Comment by z64555** [comment]
I'm thinking about intercepting the player before they head into the mainhall when they click on the Accept button within the playermenu (the first player selection screen).  And notify them that accepting the current pilot will update the pilot to v4 and make it incompatible with older versions.  It'll be done with a popup to let them choose to proceed with the conversion or to be allowed to select or create a different pilot.

**Comment by Goober5000** [comment]
That sounds like a good idea.  I'd still like it to be done with the in-game UI though.

**Comment by z64555** [comment]
As suggested in Discord, a QoL feature is to have the option to clone the pilot from the popup menu, which is what I'm currently looking into.
