### ISSUE TITLE
[FR] Changelog in the Github Releases

### ISSUE THREAD

**Issue by LiamDawe** [scp-fs2open/fs2open.github.com#4131]
Hi, to make it easier to follow, can we get the changelogs actually in the release tags? 

I think this GitHub could definitely use more info too. There's no links to anything - how come?

**Comment by ngld** [comment]
I don't think anyone on the team expected someone from outside HLP to stumble on the GitHub so it never was necessary to link to anything since it was assumed that you already knew about HLP and the SCP. The Wiki has some links, though.

The changelog as well is mostly on the forum: https://www.hard-light.net/forums/index.php?board=50.0
A lot of the discussion happens on the Discord, though: https://discord.gg/QFdueKEYrN

I suppose we could add those links to the README just in case someone unfamiliar with FreeSpace or HLP finds the project here.

**Comment by LiamDawe** [comment]
Even just adding a few basic links would be good :)

**Comment by z64555** [comment]
Most of our user base uses the HLP forums, Discord, and Knossos / Nebula to get the latest builds.  Github here is primarily a social hub for programmers, which our userbase is primarily ordinary players and at the most mission designers whose interactions are generally limited to bug reports and feature requests.

Thus, the release's changelog on github has been largely neglected, since only the CI maintainers and automation are the only users that ever look at it.

Rather than try to regurgitate the changelog into the release post, I'll probably wind up linking the Forum post to have a single point of information to maintain.

**Comment by Goober5000** [comment]
Didn't we just update the changelog?
https://github.com/scp-fs2open/fs2open.github.com/pull/4125

Granted this was after the 22.0 release was published.

**Comment by z64555** [comment]
> Didn't we just update the changelog? #4125
> 
> Granted this was after the 22.0 release was published.

Liam means here: https://github.com/scp-fs2open/fs2open.github.com/releases/tag/release_22_0_0

**Comment by LiamDawe** [comment]
> Rather than try to regurgitate the changelog into the release post, I'll probably wind up linking the Forum post to have a single point of information to maintain.

Even that would be a great step too, in addition to adding a few links to the GitHub page, glad you're open to improving it anyway :)

**Comment by JohnAFernandez** [comment]
I manually added links to the forum release thread, which has a change log, to all the releases after 19.0.0 .

I also added placing linking the release thread in the github release to the release instruction so that hopefully we remember in the future.

I'll personally try to remember for each release, as well.  Closing!
