### ISSUE TITLE
Bit depth assertion when using targa icons

### ISSUE THREAD

**Issue by AdmiralNelsonFSO** [scp-fs2open/fs2open.github.com#4161]
I get the assertion: 
ASSERTION: "bmp->bpp == 8" at bmpman.cpp:599

Assert: "bmp->bpp == 8"
File: bmpman.cpp
Line: 599

In both FSO debug and FRED debug when trying to load an icon made of of targas.  The icons appear to display correctly in release.  Is this assertion correct?

log: https://pastebin.com/Rys3Uzvb

**Comment by MageKing17** [comment]
This appears to be related to #1761, although if it works in Release, it suggests that the need to force `BMP_AABITMAP` to 8 bpp (added by Taylor back in 2004, in 6f8a0fef971570cf26a1ca38783b603a7f699bc6) "to fix a couple of OGL bpp passes" may no longer be relevant.

**Comment by notimaginative** [comment]
Pretty sure AABITMAP should always be 8-bit. There are many checks in the code for that, most from retail. But I also don't think targa should be used as AABITMAP either as I believe there used to be one or more asserts for that case. Maybe some things got changed and those asserts were no longer needed but I'm quite sure retail had them.

**Comment by notimaginative** [comment]
Looks like Swifty made the change allowing AABITMAP to be more than 8-bit (https://github.com/scp-fs2open/fs2open.github.com/commit/4a9e605e56ed7373e2a948364451f975998b70ce) and removed some of those asserts. That's why it now works in a release build too.

So someone just needs to go through and remove the rest of those old asserts to stop debug builds from crapping out.
