### ISSUE TITLE
controls are not flushed when weapons are unlocked

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4173]
Prior to the controls merge, if the player's primaries and secondaries were locked, any "fire weapon" control presses would be ignored or flushed.  After the controls merge, the control presses are no longer ignored - unlocking the primary and/or secondary weapons will cause a delayed weapons fire.

I tested this with the "primaries-locked" and "secondaries-locked" flags, although it's possible it happens with "afterburners-locked" as well.

**Comment by z64555** [comment]
Could you check real quick with `afterburners-locked` to see if it has the same behavior?

**Comment by z64555** [comment]
Hmmm, I'm not finding any changes at the moment that would affect that. `check_control` is responsible for eating the keys by checking against `Ignored_keys[]` before returning to the caller (usually a conditional).  So, if there was something to affect this behavior, `Ignored_keys[]` not getting set for the disabled actions is the point of interest for now.

**Comment by Goober5000** [comment]
I put together a test mod:
[lock-unlock.zip](https://github.com/scp-fs2open/fs2open.github.com/files/8510051/lock-unlock.zip)

I originally noticed it when clicking a prompt box option, but it appears that the bug *only* happens then.  It does not happen with the usual sexp-controlled locking/unlocking of weapons, even though both mechanisms use the same ship flag.  And since the afterburner key is typically not bound to a mouse click, it is inapplicable here.

The mission will lock everything, then unlock everything, then show the prompt box.  The normal locking behaves as expected, but if you click an option in the prompt box (using either mouse button) and your mouse is bound to the fire controls, you will fire a weapon after 0.75 seconds.  This does not happen on a pre-Controls5 build.

**Comment by z64555** [comment]
Alright, so this is an issue with the script itself and when the mouse-as-joy toggle switch feature that Controls5 introduced.

The promptbox script uses the `Use_mouse_to_fly` to turn off inputs from the mouse.  As you may know, in Controls5 the `Use_mouse_to_fly` bool was repurposed to switch between mouse mode (mouse inputs identify as mouse) and mouse-as-joy (mouse inputs identify as joystick) mode, the default state of this feature is mouse-as-joy.

To verify this on your end, please unbind all mouse bindings within your control config and try running the test mission again.

**Comment by Goober5000** [comment]
Hmm, this sounds tricky.  In answer to your questions:

1) Unbind all mouse bindings?  The mouse was not explicitly bound to the fire controls; that was the joystick button that the mouse was simulating.  When I switched the mouse behavior from Joy-0 to Mouse, weapons no longer fired, but since the mouse wasn't explicitly bound as a firing control, that is to be expected.
1b) When the mouse behavior was Mouse (not Joy-0), and yet the mouse button was bound to the primary fire trigger, clicking the prompt option did not cause the weapon to fire.

2) Pressing the joystick firing buttons while the popup was on-screen didn't cause weapons to fire, regardless of mouse mode.

**Comment by z64555** [comment]
uhhhh. ok.  Back to digging I go, then.

**Comment by z64555** [comment]
As far as I can ascertain up until now, this is not a controls input issue but more likely with how the engine reacts after the control has been processed.

1. Controls activation are not enqueued by the engine, rather, they are acted upon processing the key input event queue.
2. Controls aren't processed "later on", by checking the control's timestamp value in `CCI::used`.  This is instead only used by sexps.
3. The Player's `control_info` member is cleared at least every frame, and likely cleared every iteration of the engine checking a key input event.

I haven't looked too much at the sexps side of things yet.

**Comment by z64555** [comment]
ok. So as stated on #4426, flushing the mouse states whenver toggling between mouse and joy modes for the purposes of lua scripts will resolve #4173.  The root cause was determined to be how the lua function isMouseButtonDown uses mouse::mouse_down() to check if the buttons are down.

mouse_down() only is true while any of the checked button states (represented as a bitfield) are down.  However, the controls code checks both the mouse_down() and mouse_down_count(), the latter keeps count of all the times that a button went down during the last frame.  Since mouse_down() doesn't reset the down counters like mouse_down_count() normally does, a mouse button event is effectively *not* serviced/eaten/flushed by lua scripts.

#4426 resolves the issue with Axem's lua prompt scripts, but the problem with the counters still exists.  As mentioned in the PR, I can't just have isMouseButtonDown flush the mouse states because a script somewhere may be taking advantage of that behavior to overlay on top of the standard mouse button controls.  I'm thus determining this to be outside the scope of this issue and placing it on the TODO of the Controls Code Project so I can consider the LUA hook designs more in depth.  I will likely make a new hook, might or might not deprecate isMouseButtonDown, and/or rewrite isMouseButtonDown to deal with flushing the downcount.
