### ISSUE TITLE
"stealth" objecttype flag sets all player orders

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4202]
We discovered that the "stealth" object flag sets all player orders as allowed. So a ship that "Stealth" and "Cargo" can receive any order and shows up on the comms board by default.

We tried replacing +Player Orders: () in a -obt.tbm for the "stealth" object type which didn't work. We then copied the entire "Stealth" object type into the tbm and didn't use +nocreate in order to replace the entry entirely and remove player orders that way which still didn't work.

The Wiki page for object types suggests that "stealth" doesn't do anything. I don't know what's true about the type.

**Comment by MageKing17** [comment]
> We discovered that the "stealth" object flag sets all player orders as allowed. So a ship that "Stealth" and "Cargo" can receive any order and shows up on the comms board by default.

Does it work if you put "Cargo" first?

> We tried replacing +Player Orders: () in a -obt.tbm for the "stealth" object type which didn't work.

Unfortunately, the objecttypes.tbl parser doesn't clear the list of accepted orders, so all this told the engine was to *add* no orders to the existing list.

> We then copied the entire "Stealth" object type into the tbm and didn't use +nocreate in order to replace the entry entirely and remove player orders that way which still didn't work.

This table doesn't treat `+nocreate` specially, so as long as the entry already existed, its presence or absence does not change how the entry is parsed (so it did the exact same thing as without `+nocreate`: add no orders to the list of valid orders).

It should be possible to add support for, say, putting `+override` before the list to clear the existing entry (there's something similar for weapon flags, except `+override` goes after the list in that case), though that'll obviously be a new feature.

> The Wiki page for object types suggests that "stealth" doesn't do anything. I don't know what's true about the type.

It certainly has an effect as a *ship flag*, but its presence as an objecttype appears to be a mistake from when the table was first created (or, at the very least, the list of valid orders/goals is a mistake, since retail didn't check `SIF_STEALTH` in `ship_get_default_orders_accepted()`, and reused fighter goals for stealth ships).

The "intended" use-case is that "Stealth" is never ever the first valid object type in the flag list, per this comment in the default objecttypes.tbl:
```
;;WMC - Stealth ships always have another type, so this isn't used
```
