### ISSUE TITLE
set-subsystem-strength string variable

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4226]
set-subsystem-strength does not accept a string variable for the ship name and the mission fails to load if you try it. Seems like this should be a thing you can do?

**Comment by z64555** [comment]
It should be working with string for the ship name, there might be a bug with the cache system.

set-substem-strength takes several parameters: string ship_name, string subsystem_name, int strength_percent, bool repair_submodel (optional), bool repair_ancestor_submodel=true (optional)

**Comment by Goober5000** [comment]
Works as expected for me.  This test case sets the player's sensors to 50% at T=3s, and the transport's sensors to 50% at T=6s.  And it uses a repeating event as well.

[set-subsystem-strength.zip](https://github.com/scp-fs2open/fs2open.github.com/files/8587101/set-subsystem-strength.zip)

**Comment by MjnMixael** [comment]
My event was, admittedly, several conditionals deep but it specifically called out that sexp and variable. There is no doubt that that was the cause. I have since changed the entire sexp to work around it. Guess I'll have to try and recreate it.

**Comment by MjnMixael** [comment]
[Test.zip](https://github.com/scp-fs2open/fs2open.github.com/files/8655526/Test.zip)
This retail compatible mission gives me an error about the string variable on save.

**Comment by Goober5000** [comment]
Took a look at the mission.  This happens because the mission is checking the default value of the string, "na", as a ship name.  In most cases where a variable is used, the syntax checker will just look to see if the variable type matches (number = number, string = string) and that's it.  However, for a few complex types such as subsystems, the syntax checker delves a few layers deeper and these extra layer don't have the simplified variable check.

**Comment by jg18** [comment]
Closing now that the fix is merged.
