### ISSUE TITLE
wing wave discrepancy in red_alert_bash_wingman_status

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4269]
In `red_alert_bash_wingman_status`, in the section of code commented with `// if all parse objects in a wing have been removed, decrement the count for that wing`, there is contradictory logic.  The wing's `num_waves` are checked for > 0 and then later checked for == 0.  This code should be investigated and possibly rewritten.

**Comment by JohnAFernandez** [comment]
Looked at this briefly, and if anyone takes this on, they really have to see what currently happens in game, to see if anything unexpected happens. The code currently seems to preclude setting the `SF_Cannot_arrive` and `Red_alert_deleted` flags with its current checks, and setting these might cause undesired behavior.

And so the `if (wingp->num_waves == 0)
                wingp->flags.set(Ship::Wing_Flags::Gone);`  might be worth fixing by replacing the `wingp->num_waves== 0` with a `wingp->current_wave >= wingp->num_waves` check, pending testing, of course.

I'll write a draft pr and then if we test it a few times and weird stuff does not happen, and it matches expected behavior, I think we should be good.
