### ISSUE TITLE
AI regression when attacking subsystem

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4345]
Normally, when an AI-controlled friendly ship is attacking the subsystem of a larger ship, it will list the name of the ship and subsystem as its current orders.  In recent builds (I've checked as far back as 21.2), if the friendly ship itself comes under attack, it will break off and its orders will then show as "destroy no orders".  In retail, it will show as "no orders".

The proximate cause is that the AI's target subsystem has changed to null.  But it looks like this is an AI regression because in retail, the AI cleanly broke off from its current goal, while in current builds the AI still appears to have its previous goal even though it isn't following it.  More investigation is needed to more accurately characterize the problem.

**Comment by JohnAFernandez** [comment]
I'm taking this one on.  I have some idea already.

**Comment by wookieejedi** [comment]
Made a simple test mission. Seems to go back as far as 19.0, will keep testing though.

**Comment by wookieejedi** [comment]
Okay so previously, if a target goal was not valid the code was 
`strcpy(outbuf, XSTR("no orders", 495)); `

but then it was changed to 
`outbuf += XSTR("no orders", 495);`

So it would instead append the "no orders" instead of properly replace the whole string. Looks just like a copy and paster oversight, since all the other text appends the name of the target with the order
