### ISSUE TITLE
Axems PromptBox script has issues in Antipodes

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#436]
Reported by Phantom Hoover & Doko with BPComplete using Antipodes.

Needs more details.

So far I have:
* Checkpoint popup acts wierd, need to mash mouse button to get clicks recognised
* Similar issue in Eyes-of-the-Storm tower defense mission when placing tanks

Possibly some issue with the Lua function that unhides the mouse pointer; which FSO normally hides & resets to the middle of the screen during gameplay.

**Comment by niffiwan** [comment]
Another report: http://www.hard-light.net/forums/index.php?topic=90891.msg1802856#msg1802856

**Comment by asarium** [comment]
I know what is happening. The CursorManager does not know that there is a lua script unhides the cursor. A simple override should be sufficient. I'll try to submit a bug fix later this day.

**Comment by asarium** [comment]
Upon closer inspection the cause of this issue is a design flaw in the `CursorManager` class (whoever wrote that must have been an idio .. wait, that was me. Nevermind...)

It always sets the state of the cursor every frame which overrides whatever was set before. This means that the `showCursor` method is essentially useless because the previously set values get overwritten anyway. I'll have to change some things so the `showCursor` method is only called once instead of every frame.

**Comment by niffiwan** [comment]
right, this is fixed now, see #442
