### ISSUE TITLE
HUD preset HCF files are not available when created until restart.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4384]
HUD HCF files, which are created when the player modifies their HUD colors in the HUD Config screen, will not be properly loaded or used until the game is restarted.

They do save and they do remain in the list of available HUD Presets but they simply do not load the data.

Start FSO
Enter the HUD Config screen and make a change
Save that change to a new preset under whatever name
You can leave the HUD Config screen and return (without closing FSO) to see the new preset listed when scrolling via the left/right arrows. However the preset itself will not change HUD elements when it's selected.

To get it to actually work, you need to restart FSO.

**Comment by MjnMixael** [comment]
Migrated from Mantis.

http://scp.indiegames.us/mantis/view.php?id=3100

**Comment by wookieejedi** [comment]
@notimaginative IIRC you worked on a PR related to fixing something like this a while back?

**Comment by MjnMixael** [comment]
I should note that I tested this today on rc1 and it's still an issue.

**Comment by z64555** [comment]
Related to #3977

**Comment by notimaginative** [comment]
Yeah, I had a PR back in December which was supposed to fix this exact problem as I remember and I believe it tested fine for me. Perhaps I missed something or it's broken again since. I'll take a look at it and see what's up.

**Comment by notimaginative** [comment]
After re-reading this I realized that it's a different bug than what I had referred to fixing. But I don't remember noticing this issue while I was testing that fix.

But I just tested this procedure as I understand it and everything works fine as far as I can tell.

I went into hud config, tweaked the sliders to make a unique color setup, gave it a name, clicked the save button, then exited to the mainhall without accepting the changes (tried it both ways though). I went back into hud config, cycled to the preset I'd just made, and all of the controls updated as expected. I also tried this in-mission and everything worked properly there too. I then created a few additional presets just to make sure everything still updated properly, and it did.

Am I doing something wrong, or am I misunderstanding the problem?


(I should note there is a known issue where the retail default HCF files don't show up in the list of presets. It's a simple fix, but may have repercussions, which is why it hasn't been addressed yet.)

**Comment by MjnMixael** [comment]
Try making and saving two presets in the same game instance and then swapping between them. I just tested and can't do that until I restart the game.

**Comment by notimaginative** [comment]
I tried again and it worked as expected... I deleted all existing presets, started the game and went into hud config, created and saved 6 different presets, and without exiting hud config switched between them without issue.

I'm just using retail data without any mods loaded and the only cmdline options set are: `-nograb -nomovies -nosound -window`. Works the same whether window or fullscreen.

**Comment by wookieejedi** [comment]
Oh indeed, this is interesting. The bug does not occur for me with retail, but does occur with FotG. Hmm will have to investigate more.

**Comment by notimaginative** [comment]
Reproduced it first try with the mediavps. I'm not sure why that makes a difference exactly, but I'll track it down.

**Comment by notimaginative** [comment]
Found to be an issue with how the default path works when a mod is specified. The mod itself doesn't matter, just that the default path is different from how hud config presets expect it, which in turn causes the parsing code to be unable to find the presets.

A PR to fix this, and allow for retail presets to show up, is coming shortly.
