### ISSUE TITLE
Traitor Voice does not respect Debrief Personas

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4495]
Seems like $Voice in traitor.tbl should work like $Voice Base in rank.tbl where the Debrief Person Index (from the campaign file) is prepended to the voice filename. But this does not in fact work. In traitor table you can setup multiple texts for different personas, but you cannot change the voice file as far as I can tell. Unsure if this is a bug or an FR.

**Comment by Goober5000** [comment]
Well, I just tested this on ST:R on a recent build and it works there.  Attached is the traitor.tbl.
[traitor.txt](https://github.com/scp-fs2open/fs2open.github.com/files/9108650/traitor.txt)

By setting `+Debriefing Persona Index: 8`, the PVE debriefing officer voice and text is used.  Otherwise, the persona 91 is used in the first half of the campaign (with the exception of mission 1, which has No Traitor) and 82 is used in the second half of the campaign.

**Comment by Goober5000** [comment]
However... interestingly enough, the extension matters.  By editing traitor.tbl to use `traitor_debrief.ogg`, none of the ST:R personas are used, and the voice defaults to Admiral Wolf.

**Comment by Goober5000** [comment]
I'd call this high priority because it affects a mod.  Should be a quick fix once the cause is identified.
