### ISSUE TITLE
FRED gives invalid hud gauge warnings for valid hud gauges. Does not give warnings for invalid ones.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4517]
When loading BP2-10 in FRED (debug or regular), FRED gives several "Invalid hud gauge" warnings, for BPTaccom gauges.

However, these gauges are properly defined and work properly in mission. In addition, when loading the mission in FSO fast debug, no warnings are given

However, FRED also doesn't seem to warn properly for actually invalid hud gauges. When loading BP2-02 with a fast debug build, FSO Fast Debug properly detects that the mission tries to load BPTacComE, which does not exist (at the time of this report - BPC 3.0.9). 
However, when loading the mission in FRED fast debug, fred again only gives warnings for valid hud gauges, but **not** for the non-existing BPTacComE.

**Comment by Goober5000** [comment]
The lack of warning for `BPTacComE` is because FRED only gives one error per SEXP tree.  Since every SEXP tree containing that gauge also contains a different gauge FRED errors on, it always returns early before reaching that point.

FRED displays warnings for valid HUD gauges because the lookup function literally can't find them.  I have not yet determined the reason for that.

**Comment by Goober5000** [comment]
Well this is interesting.  FRED runs with its "game" screen resolution set to 640x480, and this is independent of its viewport resolution.  Blue Planet's `mv_root-hdg.tbm` only supports gauges down to a minimum resolution of 1024x600.  Consequently, these gauges are not loaded and FRED can't find them.

By contrast, the prompt box HUD gauges do not specify a minimum resolution, so they are loaded in FRED and are not flagged as invalid.
