### ISSUE TITLE
FR: Lua hooks into hardcoded UI controls

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4533]
Specifically I'd like to be able to capture the ESC key in GS_STATE_SCRIPTING and handle it in the Lua rather than it always going back to the previous gamestate. But I'm sure there could be more potential uses if this feature was broadened and generalized. Here's my discussion with @BMagnu regarding the issue.

> MjnMixael — 06/06/2022
> My use case here is to completely stop FSO from handling ESC in during the scripting game state and handle it in Lua so that I can choose whether to leave the game state or perform something else.
> BMagnu — 06/06/2022
> You'd need to use the action to which ESC is usually bound. But:
> I don't think that is currently possible, because the scripting state does not actually use "the controls" to check whether it has gotten the ESC.
> Rather, it uses a hardcoded, non-rebindable check to the (system) keyboard buffer (similar to, say, pressing F2 in mission for the options) to see whether it should quit.
> The new system is primarily for (rebindable) controls, replacing the on-action hook with more detail.
> Your usecase requires the non-rebindable On Key Pressed hook to be overridable.

**Comment by BMagnu** [comment]
My idea for this, at least for this use case, would be to make a very low-level hook to ``key_inkey()``.
The advantage is that it would be able to catch and override very low-level events, like pressing F2 to go to the options menu.
But that has a few disadvantages:
1. It's highly context sensitive. Some things, like the F2 button, are hardcoded pretty deep and will happen really always except in some few gamestates. Then some other things, like navigating popups, is similarly hardcoded, but only in the popup part, and even then it can depend on the actual popup itself. Navigating this context, and what button does what when is going to be very hard for scripters and would undoubtedly require some knowledge of the C++ code.
2. It's going to be called often. At least once per frame, but possibly more often. Every time the code will query keypresses, effectively. This _could_ in some cases, cause confusion for scripters.

Currently, there are already On Key Pressed and On Key Released. These are, AFAICT, called by the SDL callbacks, and would be even more low level, however due to their nature it is very hard to override them (it'd need a buffer of overridden keypresses that then do not need to be removed on release and stuff), as well as not corresponding to the engine actually _checking_ for keypresses, which forces the scripter to ignore keypresses based on when they occur, and not when they are queried (which makes things hard that interact with holding a key).

Ideas for a better solution, or does this sound suitable?

**Comment by MjnMixael** [comment]
I don't really have a better idea. I think those downsides can be worked through, though, if any scripters are crazy as crazy as I am and want to dive this deep into controlling FSO with Lua.
