### ISSUE TITLE
False Null MOI warnings

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4534]
The first 22.3 nightly gives these warnings where 22.2.0 does not. Does not apply to all models. I don't see a pattern to what models trigger it. Triton in FSU is a perfect example. Also happens with the Fenris. I have verified the POFs in question absolutely do have MOI data.

Load up 22.2.0 debug with FSU 4.6.6. Go to the lab and view the Triton. No warning.
Load up 22.3 debug with FSU 4.6.6. Go to the lab and view the Triton. Null MOI warning is triggered.

**Comment by Goober5000** [comment]
This is probably due to #4443, and in particular `fl_near_zero` being used in the `IS_VEC_NULL` check.  In this comparison, epsilon is the wrong threshold because it has an order of `e-07` and the Triton's MOI values are all `e-08` or smaller.

The fix should be to restore the previous definitions of `IS_VEC_NULL` and `IS_VEC_NULL_SQ_SAFE`, and to restore `IS_VEC_NULL_SQ_SAFE` where it was replaced by `IS_VEC_NULL`.
