### ISSUE TITLE
CTD when changing game states and using multiple On Frame hooks

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4604]
Dump attached. Stack trace went through gamestates and scripting hooks before "The thread tried to read from or write to a virtual address for which it does not have the appropriate access." was thrown in standard vector.

**SNIP**

EDIT: See comment below for updated steps to reproduce

[fs2_open_22_3_0_x64_AVX2-DEBUG_20220830_012832.zip](https://github.com/scp-fs2open/fs2open.github.com/files/9448845/fs2_open_22_3_0_x64_AVX2-DEBUG_20220830_012832.zip)

**Comment by MjnMixael** [comment]
I have confirmed this is not any new code and the crash can be triggered on the latest nightly. Use the attached mod data.
1) Get to the mainhall
2) Go to either the Tech Room OR the Briefing (not Cmd Briefing!)
3) Exit that UI back to the mainhall
4) Go to the opposite UI from the first one you chose.
5) CTD relating to the vector of conditional hooks happens here.
[data.zip](https://github.com/scp-fs2open/fs2open.github.com/files/9462603/data.zip)

**Comment by The-E** [comment]
Okay, I think I can see what's happening here, and why having that empty hook might be fixing it. So, the problem with `briefing.lua` and `tech_database.lua` is that they use the `addHook` function to install new hooks. This is normally fine, however, in this case these functions are being executed in the ONSTATESTART hook, which leads to a crash because we are altering the vector of hooks while iterating through it
 The reason why the empty hooks fix this is because an empty hook is still a hook, so when `addHook` is being called, it only adds another action to an existing hook
