### ISSUE TITLE
Regression: Splash screen conditional and global hooks 

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#4742]
I discovered that the Splash screen conditional and global hooks no longer run what's in them, and tracked it down to June 20, 2021 `Moved script initialization to take place after all table loading to facilitate script condition caching` #3522. 

For example, this script will never trigger:
```
#Conditional Hooks

$Application: FS2_Open

$On Splash Screen: [
    ba.warning("zzz \n")
]
+Override: true

#End
```

I'll also add that whether or not Override is set doesn't seem to make a difference for this test.
Debug log shows the `game_title_screen_display()` function is running ofc (`freespace.cpp` line 7452)
```
SCRIPTING: Splash screen overrides checked
Compiling new shader:
    Default material
Shader Variant Features:
SCRIPTING: Splash screen conditional hook has been run
```

**Comment by BMagnu** [comment]
Due to how scripting is handled, making this work as intended again is highly challenging.
That's because we have two conflicting intentions there:

On the one hand: Scripting should init after everything else. This is notably due to a) the need to have all tables and stuff readable in  On Game Init hooks, and b) to be able to properly load and cache scripting conditions.
On the other hand: We want to be able to access and override the On Splash Screen. Notably, overriding On Splash Screen needs to happen before any load, as the splash screen is shown during load of all the tables.

Since the most common use case for the override is displaying a random custom splash, the need for the override pretty much diminishes with #5054. Thus, after some discussion with @wookieejedi, I propose that the hook should be deprecated (probably alongside #3171) in the following way: Using the +Override will error, similar to how using deprecated lua functions error, and will not be run. Using the hook itself will warn the user if a previous engine version is targeted, and error if a modern engine version is targeted. The hook will be run after On Game Init (which is technically after the splash screen, but the best middle ground we have, I guess).

Unless there is some opposition to this, I'll take a stab at implementing this for 23.2.

**Comment by Goober5000** [comment]
Sounds ok to me, especially if @wookieejedi is fine with it.

**Comment by wookieejedi** [comment]
Awesome, yep all good with me.
