### ISSUE TITLE
Mainhalls stop animating under particular SCPUI condition

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4755]
Using SCPUI for any mission-loaded UI and then backing out of the mission causes the mainhall animations to stop animating until a mission is played and completed.

Specific steps to reproduce. 

1) Utilize the SCPUI mod found [here](https://www.hard-light.net/forums/index.php?topic=98473.0) and launch on a very recent nightly. It should launch out of the box into retail + scpui
2) Start a mission by clicking on the ready room. Any mission, doesn't matter.
3) Back out of the mission by pressing Esc
4) Mouseover any animated mainhall element. They will not animate, but the sound will be played and clicking still works.

I have tried to track this one down on and off for a month and have been unsuccessful. My guess is it has something to do with a librocket context not getting completely unloaded.

EDIT: This issue is a case-study in how keywords cause SCP to ignore tickets.

**Comment by MjnMixael** [comment]
I have tracked this down to line 1422 in mainhallmenu.cpp. Specifically the `timestamp_elapsed` bool never returns true after a mission is started but quit early. This does not happen without an SCPUI interface being loaded. So you could load up a mission that starts with Fiction Viewer (non-SCPUI) and quit. The issue won't occur. But without quitting the game if you then load up a mission that starts with Command Brief (SCPUI) and quit then the issue will occur.

Seems like when SCPUI takes over in this particular case it conflicts with some of @Goober5000 's timestamp stuff.

**Comment by MjnMixael** [comment]
The timer gets paused with `Timestamp_is_paused` and never gets unpaused in this particular case.

**Comment by MjnMixael** [comment]
ok, I see. The timer is paused during mission load and I bet that since SCPUI overrides most UI init and close logic done by FSO, no code is ever reached to restart it.

**Comment by Goober5000** [comment]
Huh, good detective work.

**Comment by Goober5000** [comment]
Ok, the problem here is larger than just the timer.  The root cause is that the mission is being exited, but not cleaned up.  In FreeSpace, this is handled automatically by the state management code, but since SCPUI uses its own state management, it will need to handle this somehow.  The core functionality as seen in `game_leave_state()` is this:
```
if ( going_to_menu_state(new_state) ) {
	freespace_stop_mission();
}
```
The `freespace_stop_mission()` function will perform all of the shutdown/cleanup operations.  That will take care of restarting the timer via `game_time_level_close()`.

There are various other cleanup functions in `game_leave_state()` which may or may not be necessary in SCPUI's case.  Among these are `brief_stop_voices()`, `common_select_close()`, `sim_room_close()`, `campaign_room_close()`, and so forth.

**Comment by MjnMixael** [comment]
Only the level close stuff is needed. I looked at almost everything else. If all they ever do is handle clearing out bitmaps and UI related items, then they can be skipped with SCPUI.

**Comment by Goober5000** [comment]
Ok, sounds good.
