### ISSUE TITLE
running on a Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [scp-fs2open/fs2open.github.com#4829]
Im trying to get this working on my Pi4.
im running Buster/10. 32bit/ RetroPie

im able to compile it just fine, but it will not start. 

im using this since i know that my OS does not have opengl 3.2 or vulkan
```
make -DFSO_FREESPACE_PATH=$romdir/ports/freespace2 -DUSE_OPENAL=1 -DFSO_BUILD_WITH_OPENGL=OFF -DFSO_BUILD_WITH_VULKAN=OFF ..
```
it builds fine, but when try to run it is still says that its looking for  opengl even though i have the command not to build with it, 
and when it starts to build i can see that both opengl and  vulkan are off

i know a one point i did have this working, but its been a long time. 

any pointer will be amazing, im out of ideas

**Comment by The-E** [comment]
OpenGL 3.2 is a hard requirement at this time. Without it, FSO won't work. The "build without opengl" switch is intended for a future implementation of the headless server mode, not for actually playing the game.

**Comment by Exarkuniv** [comment]
ahh, thank for that answer, that makes sense

do you know a older commit that might work on a Pi, as i said at some point there was one

**Comment by Shivansps** [comment]
You can run FSO, but 3.7.2 is the maximum version supported. On ARM 64 bits you just be able to grab the unmodified 3.7.2 code and compile it for ARM linux 64 bits. You do need to remove x86 optimisations manually before compiling because autogen does not recognise the ARM cpu.

./autogen.sh --enable-debug
sed -i -e 's/-mtune=generic -mfpmath=sse -msse -msse2/ /' ./mongoose/Makefile
sed -i -e 's/-mtune=generic -mfpmath=sse -msse -msse2/ /' ./code/Makefile
sed -i -e 's/-mtune=generic -mfpmath=sse -msse -msse2/ /' Makefile
make -j4

For 32 bits the same works but you will be only be able to run FS2 retail anything else will crash. There is a fix for this, the i have a fork of the 3.7.2 branch with the fixes that allows to play using mods whiout crashing. Ill highly recomend you to switch to 64 bits, as it is faster overall. 

Here is the link for the modified 3.7.2 code 
https://github.com/Shivansps/fs2open.github.com

I have a full guide here:
https://forums.raspberrypi.com/viewtopic.php?f=78&t=230316

And the video guides of running FS2 3.7.2 on RPI
https://www.youtube.com/watch?v=TA6ew4aXpl4&ab_channel=shivanSpS

And Wing Commander Saga (full conversion mod)
https://www.youtube.com/watch?v=1Q5ByKGL5to&ab_channel=shivanSpS

As for the launcher, i never managed to get knossos running, so i used WXLauncher.

**Comment by Exarkuniv** [comment]
@Shivansps that worked great, just one question. 
is there a way to start a mod without the launcher, but from command line?

the launcher does not like my with my setup, i have no mouse pointer on it, (still messing with it)

**Comment by Shivansps** [comment]
The launcher is just a command line builder program, you should be able to see on "advanced settings" tab the current command line arguments.
It will be mostly "-mod <modfoldername>" and "-no_glsl" for Wing commander saga.

https://wiki.hard-light.net/index.php/Command-Line_Reference

The one thing i dont remember is how to set the video resolution

**Comment by Exarkuniv** [comment]
again thanks for that, 
thats a great help. 

i will close the issue, since i do have it working
