### ISSUE TITLE
Broken animated skybox textures 

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#4887]
from https://www.hard-light.net/forums/index.php?topic=98532.msg1916129;topicseen#msg1916129
> I've been working with TBP, and its Hyperspace environment uses an animated skybox to create a shifty background.  It's been a bit since I tested a hyperspace mission, and was surprised to find the texture has become static.  I began working back through builds to find exactly when this was introduced, and it seems that it started with the Oct. 25th build.  I checked the commits for that build and found this:

> upgrade texture animation code to use new timestamps

> Now, either someone didn't take into account something with skyboxes, or a new system was implemented to offer a wider range of controls for animated textures, which has deprecated what TBP uses.  So, is this a bug, or a new feature that I need to account for?

**Comment by Goober5000** [comment]
It's a bug.  The texture animation code should work exactly the same as it did before, only it should use timestamps rather than mission time.

The thing is, I tested an animated skybox back when I posted that PR, and the skybox worked fine.  So I'm curious what's going on here.  Which missions are hyperspace missions?

**Comment by TheTrivialPsychic** [comment]
I've been working with 'In The Beginning', which is still in development, but I just tested out 'Raider Wars' mission 'Hell and Back' (RW_07_HaB), which takes place in hyperspace, and encountered the same static skybox (using the Nov 11th build).  I also feel it may be useful to mention (something I hadn't noticed when I made the original HLP post), that while playing a mission in hyperspace (on a recent build), the background will flicker from time to time.  I tried to see if there was a pattern to it, say, if it was reoccurring when the animation file is supposed to restart, but I could find no consistent pattern.

**Comment by tomimaki** [comment]
Animated textures on shadow vessels or mvps ravana doesn't work too on the same build i.e. 25 Oct.

**Comment by TheTrivialPsychic** [comment]
Shadows... I should have noticed THAT one. [Facepalm]

**Comment by EatThePath** [comment]
Is flickering conclusively tied to the changes on the 25th? there's been some other changes recently that could conceivably affect rendering too @TheTrivialPsychic

**Comment by Goober5000** [comment]
It looks like the most recent version of the MVPs Ravana does not have animated textures. But I loaded up a previous version of the MVPs and found the error; it's a simple math error.  I also tested the fix on the TBP mission and I see the skybox being animated now.

It turns out that the skybox I had originally used to test that PR achieved its animation using rotating submodels, not animated textures, so it was a false positive.

**Comment by EatThePath** [comment]
> It looks like the most recent version of the MVPs Ravana does not have animated textures.

Do you have all the optional packages? They should be in the Anim Glows package, or in one of the of the adv packages

**Comment by Goober5000** [comment]
I do have the AnimGlows package.  The HTLRavana-Glow texture is not used on the 4.6 version of the Ravana.  The equivalent texture for that model is RavanaPulse which does not have an animated version.

**Comment by EatThePath** [comment]
Ok, that's an FSU issue than. The 4.5 version has animated textures there, and it appears to be affected by the same bug. Presumably the same fix applies to it, though.

**Comment by tomimaki** [comment]
RavanaPulse-glow.eff is in mv_advanced2.vp

**Comment by tomimaki** [comment]
Linked patch fixed animated textures on Ravana.
