### ISSUE TITLE
Nightlies break BP2-08 The Intervention

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5005]
[As reportred by Muninn_Crow on discord.](https://discord.com/channels/223511295431933953/255067124836335616/1052300088669638676)

In War In Heaven -Act 2, there is a test flight with lots of dialogue options. Alas, in 'pressing the issue' of flight morale, the options for the following path stop advancing. (Tested twice)
Dialogue path: 4. Direct > 3. Personal Strengths > 1. That's the spirit > 1. Discuss squadron morale > 2. Persist > 2. Call her out > (1. Demand better performance;  2. Critique specific behavior) Unable to continue.

Just tested the mission Intervention in the stable build. Works perfectly fine. :/

**Comment by Goober5000** [comment]
I've determined that this is somehow related to #4954 or #4633, but that part of the logic has already been exhaustively tested in everything from FSPort to Scroll to the other Blue Planet mission.  Plus, this doesn't happen for all conversation events, just this particular one.  So this is puzzling.

**Comment by Goober5000** [comment]
I have a better idea of what's going on now but I need to do some more testing to be sure.

**Comment by Goober5000** [comment]
Okay, after extensive testing and looking at this from multiple angles, I believe the event chaining behavior is is working as designed.  As described in commit 06fc8c73a5b892513fe06eab80d67f2a45a075de, the event timestamp field was originally a Schroedinger's hybrid of two data types, that nevertheless worked correctly for almost all cases due to a cascade of coincidences.  BP2-08 contains a mission bug that "still worked" due to a bug in the original event timestamp implementation.  When the timestamp implementation was fixed, the mission bug caused the mission to break.

Events that are chained to repeating events may only proceed once the repeating event has completed -- or, if the chain delay is within the rotation interval, once the delay has elapsed.  In other words, when the event fires, a stopwatch starts, but the stopwatch resets every time the event repeats.  If the chain delay is within the stopwatch interval, then it will fire; if the chain delay is outside the interval, then it cannot fire because the stopwatch resets before the interval elapses.  But once the repetition cycle is complete, the stopwatch will no longer reset.

This is the way the design is intended to work anyway; the original implementation's bug caused the stopwatch to not reset after the first interval.

BP2-08 had a chain delay of 9 on an event, `neutral exam reply 4`, that was longer than the repeat interval of 1 on the previous event, `neutral exam choice 4`.  And since that event had a trigger count of 99999999, it would take about 3.17 years for the event to stop repeating.  The solution is to set the chain delay on `neutral exam reply 4` to 0 to match the other "reply" events.  There are no other "reply" events in this mission with a nonzero chain delay.

**Comment by Goober5000** [comment]
I wrote a quick utility to look for all problematic events in the BP missions folder:
```
In bp2-08.fs2, found event: Menu responds to inputs 2/3/4
In bp2-08.fs2, found event: neutral exam reply 4
In bp2-23.fs2, found event: s3n3 press complete
```

**Comment by Goober5000** [comment]
Hmm, there are a few others...
```
In bta1d_m0_01.fs2, found event: No More Drones - MSG
In bta1_m2_08.fs2, found event: Ensure Transports Have Undocked
In bta1_m3_01.fs2, found event: MSG - SAP - mines gone
In dl2-04-l2.fs2, found event: Mercenaries get out
In dl2-09.fs2, found event: Einstein losing integrity
In dl3-07.fs2, found event: Beam free Cyaegha
In dl4-07.fs2, found event: Beam free
In jad221-01a.fs2, found event: Destroy Core
In jad221-01aa.fs2, found event: Destroy Core
In jad222-07d.fs2, found event: Holley goes what
In M-03.fs2, found event: Fire: Retribution_slash_23_12
```

**Comment by MoerasGrizzly** [comment]
Thank you for supplying me with the information needed to correct the bug on my end! 

Given that some missions do depend on the bugged behaviour, this is probably a case to invoke with target version and/or gamesettings.

**Comment by Goober5000** [comment]
Yeah, I think that might be necessary.

**Comment by Goober5000** [comment]
Ok, #5073 will use the retail behavior by default.
