### ISSUE TITLE
Enabling scripts in FRED causes parsing errors

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#5026]
The errors that are caused when launching FRED maybe shouldn't be hit because parsing between FSO and FRED should be identical.

Use the attached tables. a_fred-sct.tbm should be the only script that's actually run. The mv_exp-sct-tbm is set to $Application: FS2_Open but an error on parse is hit forcing FRED to close.
[tables.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10256055/tables.zip)

**Comment by BMagnu** [comment]
Turns out that this is a _fundamental_ issue with how the new hooks system was devised way back when.
Since some hooks are defined in the freespace.cpp, they aren't initialized when FRED is run (obviously), so FRED thinks that they don't exist at all.
And if "On Mission End" doesn't exist, its no wonder why it'll complain.
The proper solution is to take all all hook definitions, and pull them together in the global_hooks.cpp file
