### ISSUE TITLE
Missile lead indicator does not show properly on alternate $Lead Indicator Behavior modes.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5088]
On the $Lead Indicator Behavior: Average and $Lead Indicator Behavior: Multiple modes, the missile lead indicator displays weirdly.

In a lot of cases it'll only show when your primary weapons are in range, even though you're using, say, a heatseeker missile with a very long range, like the Stiletto.

To test:
Set $Lead Indicator Behavior: Average or Multiple in your game settings.
Fire up The Sixth Wonder
Pick Stiletto missiles for one of your banks.
Switch to said missiles.

Notice how the missile lead indicator does not display, even though the Stiletto has a range of 5.5km

**Comment by MoerasGrizzly** [comment]
Apperently @Kiloku worked on this?

**Comment by Kiloku** [comment]
I did! Will take a look, thanks

**Comment by Kiloku** [comment]
Still trying to figure this out. The issue seems to be a bit of an edge case. 

It happens while your primaries are linked and all of them are out of range. I can tell that it's related to the "Don't Merge Indicators" code, but I'm having a hard time isolating it in a manner that doesn't break other behavior.

**Comment by JohnAFernandez** [comment]
I am just updating this issue to say that Kiloku believes that 5094 is insufficient to fix this and that this whole function needs to be rewritten to be clearer.  So I'm going to close 5094 as per his request, hoping that one of us will get to reworking that function soon, in order to resolve this bug.

**Comment by JohnAFernandez** [comment]
Ok, I just sat down, debugged it, and wrote and tested a fix.

If someone were to rewrite the function, they should put the rendering calls at the end of the function, recording what rendering needs to be done based on the mode given.
