### ISSUE TITLE
23.0.0 RC3 FRED crashing without error when loading mission

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#5092]
Using build FSO-23.0.0-RC3.

May need to check how FRED is saving mission files as unable to open files recently saved in RC3. 
Opening recently saved missions in RC3 crashes FRED without error message or debug.
On reverting back to stable 22.0.0 error messages report missing $AI Behavior: under #Objects, and +Neb2Flags in#Background bitmaps.
Once added back in the mission loads again in stable 22.0

**Comment by Goober5000** [comment]
This is intended.  The `$AI Behavior` line was removed in #4865, and `+Neb2Flags` was migrated to `+Neb2 Poofs List` in #4834

**Comment by EatThePath** [comment]
hang on, I need to make sure i'm reading the issue correctly.
1. Have an existing mission
2. open it in rc3 fred, save
3. Try to open it in rc3 fred again, silent crash
Is that the behavior you're seeing, @dariusbei ? If the issue is that 22.0 can't open 23.x missions successfully, yeah, I can see that as not a bug, but if 23.x can't open 23.x files this is kind of a big deal yeah?

**Comment by EatThePath** [comment]
hang on, I need to make sure i'm reading the issue correctly.
1. Have an existing mission
2. open it in rc3 fred, save
3. Try to open it in rc3 fred again, silent crash
Is that the behavior you're seeing, @dariusbei ? If the issue is that 22.0 can't open 23.x missions successfully, yeah, I can see that as not a bug, but if 23.x can't open 23.x files this is kind of a big deal yeah?

**Comment by MoerasGrizzly** [comment]
> This is intended. The `$AI Behavior` line was removed in #4865, and `+Neb2Flags` was migrated to `+Neb2 Poofs List` in #4834

Wow, ok.

@EatThePath So atm, Fred RC3 has a tendency to hard crash without leaving an error message (as Darius mentioned above). 
As a test case, I tried opening BPC 3.1.6's Loop1-1.fs2 with an RC3 build of Fred. It crashes.

**Comment by dariusbei** [comment]
Now that I'm thinking of it it's not confirmed if the missing flags is the culprit for the silent crash in RC3.
It could just be that RC2 FRED just isn't loading RC3 missions for a separate reason and the crash is being caused by something else.
I'll edit the title to be more descriptive of the issue.
