### ISSUE TITLE
Use proper scaling for briefing icons

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#5197]
As I noticed in my slightly-too-late review of #5047, this PR adds a `scale` parameter to `gr_aabitmap`.  In every other place `gr_aabitmap` needs to scale something, the screen is scaled beforehand, and then `gr_aabitmap` is called.  There's even a `resize_mode` parameter to reflect how the scaling was accomplished.

It will be necessary to remove the `scale` parameter, then scale the briefing icons using the standard technique.

**Comment by MjnMixael** [comment]
You are wrong here, goober. This isn't rescaling the screen coordinates. This is rescaling the bitmap itself.

**Comment by MjnMixael** [comment]
Furthermore, let me add that this must be done afterwards. This scaling should be done after any screen-based scaling. If we're stretching, do we that. Then go into the bitmap drawing method and we scale from there so that the scaling is identical across screen resolutions and whether the UI is stretched or not.

**Comment by Goober5000** [comment]
Closing this as the assumption in the initial comment turned out to be incorrect.
