### ISSUE TITLE
Alt-Tabbing and Pausing can break "seamless with startup" animation flag

### ISSUE THREAD

**Issue by UndyingNephalim** [scp-fs2open/fs2open.github.com#5248]
Either Alt-Tabbing out of the game or pausing it can lead to "seamless with startup" flag for animations breaking. Much more frequent with Alt-Tabbing and re-entering the game than Pausing.

**Comment by BMagnu** [comment]
To shed some light on this:
"seamless with startup" isn't the culprit, but just a flag whcih exacerbates the symptoms.
Animations step forward by the current frametime. When they reach their time limits (so either their duration in forward mode, or 0 in backwards mode, exceptions apply for some flags), their current time is capped to the limit, and depending on the mode they'll be stopped or turned around or whatever. And that is the issue: The time is _capped_, not wrapped around.
In normal operation, that's not an issue as it introduces inaccuracies in the realms of a few milliseconds, especially since non-loop animations end up in a static state anyways. But if you have a frametime that is very large, it'll cause all animations that reach their end within this large frame to be synced up, as no matter where they were, the time is then capped to the limit instead of being wrapped around in the other direction if they're looping.
