### ISSUE TITLE
pref_path given by get_flags cant be trusted

### ISSUE THREAD

**Issue by Shivansps** [scp-fs2open/fs2open.github.com#5270]
When the fs2_open.ini file dosent exist -get_flags json_v1 return this
`FSO is running in legacy config mode. Please either update your launcher or copy the configuration and pilot files to 'C:\Users\shiva\AppData\Roaming\HardLightProductions\FreeSpaceOpen\' for better future compatibility.
{
    "version": {},
    "easy_flags": [],
    "caps": [ ],
    "openal": {},
    "voices": [],
    "flags": [],
    "displays": [ ],
    "joysticks": [],
    "pref_path": ".\\"
}`

in constract, when the file exists even if its empty it prints this
`{
    "version": {},
    "easy_flags": [],
    "caps": [ ],
    "openal": {},
    "voices": [],
    "flags": [],
    "displays": [ ],
    "joysticks": [],
    "pref_path": "C:\\Users\\shiva\\AppData\\Roaming\\HardLightProductions\\FreeSpaceOpen\\"
}`

Now, two issues here:
1) if i rely on get_flags to get the fso data location i can never create the fs2_open.ini file because it will give me a wrong location.
2) that additional string at the start is breaks the normal json parsing and has to be ignored with string manipulation.

I know that first string gives me the actual location of where the ini should be, but im really unsure about having to parse that to get it the first time, thats a little bit risky, what happens if the path contains the ' character for example?

I dont know why this legacy mode exists and im also petty sure this only happens in Windows, altrought i cant confirm 100%.
Since i dont understand it, i cant be sure if this is actually a bug or if im supposed to get the ini location from an alternative way, like parsing that string.

**Comment by Goober5000** [comment]
FSO needs to correctly choose between the current config mode and the legacy config mode depending on whether Knossos or a launcher or a debugger is used to launch the game.  The logic can be found in `os_is_legacy_mode()`.

I don't fully understand the vagaries of the different modes, but it's clear that `pref_path` is explicitly changed from the user profile folder to the ".\\" folder when legacy mode is active.

One way you could get the path without worrying about apostrophes is by explicitly checking `files to '` and `' for better` as the start and end tokens.

**Comment by Shivansps** [comment]
That dosent change due to lang? 
I know this is not going to help with the old versions, but what about adding a "ini_path" to get_flags json_v1? that no matter what will always give the correct folder path for the ini?
It should be safe to add data to the json output.

**Comment by Goober5000** [comment]
It should be independent of language.

The thing is, since `pref_path` is explicitly changed, the "correct folder path" might actually depend on legacy mode, in which case your code shouldn't attempt to get the other location.  I can't be sure.

Perhaps @notimaginative or @ngld could offer insight.

**Comment by ngld** [comment]
Do you have access to SDL2? In that case, you can just call `SDL_GetPrefPath` to get the relevant path since that's exactly what FSO itself does and what I use in Knossos.

https://github.com/scp-fs2open/fs2open.github.com/blob/14689265ceb1fec0f93e39adfde49bd0f8c2b06c/code/osapi/osapi.cpp#L31-L32
https://github.com/scp-fs2open/fs2open.github.com/blob/14689265ceb1fec0f93e39adfde49bd0f8c2b06c/code/osapi/osapi.cpp#L47

Legacy mode exists to support old launchers that were created before FSO adopted SDL2. In fact, before Knossos existed, wxLauncher was the only launcher that supported the new SDL2 location. It exists on all platforms: On Windows, legacy mode reads the settings from the registry. On Linux, the settings are in `~/.fs2_open` and on macOS, they're in `~/Library/FS2_Open`. The modern mode uses `SDL_GetPrefPath` everywhere which makes things a lot easier and more consistent.

Finally, there's an important bit you need to be aware of since you're writing a launcher: Whenever FSO starts, it checks the old config location and the new config location and uses whichever was last modified. This is necessary to make old launchers work even after a user used a modern launcher. To make sure that FSO runs in modern mode, you should *always* update `cmdline_fso.cfg` before you launch FSO.

Also, be careful with how you use the result of `-get_flags json_v1` since it's not necessarily consistent between FSO versions. Different versions support different flags and even the joystick UUIDs changed at one point. Which is (unfortunately) still relevant since there are still mods out there that reference old builds which list the old UUIDs in `-get_flags json_v1` and only accept those in `fs2_open.ini` while newer builds list different UUIDs (for the same devices!) in `-get_flags json_v1` and only accept those in `fs2_open.ini`. In other words, to make joysticks work consistently, you either have to make sure you never launch those old FSO builds or you'll have to check which UUIDs the current build expects and then update the `fs2_open.ini` accordingly before you actually launch FSO. The reason for the change is that SDL2 changed how it generates UUIDs so you could theoretically work around this by forcing old FSO builds to use a newer SDL2 library than the one that's bundled with FSO but I don't know if that'd create other issues.
