### ISSUE TITLE
FR: String variables as directives

### ISSUE THREAD

**Issue by Kanangus** [scp-fs2open/fs2open.github.com#5271]
Currently the engine only supports ints for the directive as variable in FRED. Possible use cases here include updating directives for targets which change names, or quickly directing player attention to something without requiring training messages or script based HUD elements eg, signal strength (poor/fair/strong), etc

**Comment by MjnMixael** [comment]
I was looking at this and the Lua API allows for setting the Directive Text. Assuming that works as expected, it should be pretty trivial to make a LuaSEXP that can update the directive text of any arbitrary mission event. Using that, you might be able to do what you want. I personally wouldn't touch Directive Count to allow strings because the code surrounding that field's usage is all math based. Much easier to just change the text itself.

Because of the FRED UI limitations I don't know that setting the text as, optionally, a variable is the right route to go. If I were designing this for in-engine use then I'd create a built-in set-directive-text SEXP.

**Comment by Goober5000** [comment]
These will do it:

In a -sexp.tbm
```
#Lua SEXPs

$Operator: lua-set-directive-text
$Category: Change
$Subcategory: Scripted
$Minimum Arguments: 2
$Maximum Arguments: 2
$Return Type: Nothing
$Description: Sets an event's directive text to what is contained in the specified message or variable, or to the actual string if neither is found.
$Parameter:
	+Description: The event to set
	+Type: event
$Parameter:
	+Description: The variable, message, or plain text to use
	+Type: string

$Operator: lua-set-directive-keypress-text
$Category: Change
$Subcategory: Scripted
$Minimum Arguments: 2
$Maximum Arguments: 2
$Return Type: Nothing
$Description: Sets an event's directive keypress text to what is contained in the specified message or variable, or to the actual string if neither is found.
$Parameter:
	+Description: The event to set
	+Type: event
$Parameter:
	+Description: The variable, message, or plain text to use
	+Type: string

#End
```

In a -sct.tbm
```
#Conditional Hooks
$Application: FS2_Open

$On Game Init:
[
	mn.LuaSEXPs["lua-set-directive-text"].Action = function(event, text)
		if not event:isValid() then
			return
		end

		local msg = mn.Messages[text]
		if msg and msg:isValid() then
			text = msg.Message
		else
			local var = mn.SEXPVariables[text]
			if var and var:isValid() then
				text = var.Value
			end
		end

		event.DirectiveText = ba.replaceTokens(text)
	end

	mn.LuaSEXPs["lua-set-directive-keypress-text"].Action = function(event, text)
		if not event:isValid() then
			return
		end

		local msg = mn.Messages[text]
		if msg and msg:isValid() then
			text = msg.Message
		else
			local var = mn.SEXPVariables[text]
			if var and var:isValid() then
				text = var.Value
			end
		end

		event.DirectiveKeypressText = ba.replaceTokens(text)
	end
]

#End
```

**Comment by Goober5000** [comment]
Closing as the scripted sexp is an accepted solution
