### ISSUE TITLE
Discrepancy between comments and model instance code

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#548]
The following pair of comments appears three times in the current codebase:

```
// Do collision the cool new way

[...]

// Recover and do usual ship_ship collision, but without rotating submodels
```

They can be found in asteroid.cpp, debris.cpp, and collideshipship.cpp.

The problem is that _both_ the first and second chunks of code use rotating submodels -- or rather, they use the model_instance functions, which take into account the angles of the submodels.

Questions:
1) What does "without rotating submodels" mean?  Does it mean to use the model_ functions rather than the model_instance functions?
2) Why do both "the cool new way" and "the usual" collisions?
3) Is the current usage correct?  If it is, the comments should be clarified.

**Comment by FSCyborg** [comment]
So, I just took a look at these, because I don't want this issue to exist forever.  Someone should double check how I'm reading this, but I feel pretty good about these conclusions. 

The first chunk looks like it actually puts each rotating submodel into a list (vector) and checks each of them for collision individually.  It was probably an addition when they added rotating submodels because this code is from the original code dump.

The second chunk is the basic collision check for the base mesh.  Both are checked because you can collide with both the base mesh and the rotating submodel in the same frame (it's just unlikely).  The model instance information is just for finding the collision normal.

Based on what I'm seeing, we should change the comments on the second block to `// Now complete base model collision checks that do not take into account rotating submodels.`

**Comment by Goober5000** [comment]
That makes sense.  The fact that it's in the original public release sheds some light on things; it's probably exactly what you said: an addition when they added rotating submodels.

The main reason I pinged @SamuelCho is because he is the one who added the model instance code.

**Comment by Goober5000** [comment]
Well hang on.  Was @JohnAFernandez 's change implemented?

**Comment by Goober5000** [comment]
Closing now that this has been actually resolved.
