### ISSUE TITLE
Existing French translations can't be launched on recent FSO builds due to duplicated rank names

### ISSUE THREAD

**Issue by Achille44** [scp-fs2open/fs2open.github.com#5592]
I tried to run my existing French translation mods on recent FSO builds (23.2 RC4, 20230907 nightly), and i get the following error: "All rank names must be unique".
Indeed, several ranks have the same name on my translations because of how the ranks are called in the French army (more details at the end for those interested).

**I guess the easiest way to fix the issue would be to add $Alt Name for ranks.tbl (like it already exists for ships.tbl) without cheking duplicates for these alt names.**

Detailed explanation of the issue with translating ranks in French language:
- In French, when you talk to a superior officer, there is no equivalent to the "yes, sir" that works for every rank, so you have to use the name of the specific rank: "Oui, Lieutenant", which is doable using the $rank variable in dialogues.
- **BUT** in the French army there are two distinct ways to call a rank as described below (source: wikipedia)
![image](https://github.com/scp-fs2open/fs2open.github.com/assets/5891168/b14d796f-1224-49d7-88cf-b44d6a3b953c)
The "grade" is the offical rank title (no duplicates here), and the "appellation" is the the word you have to put at the end of each sentence when talking directly to a superior officer (so here we have duplicates). So, ideally I would need two different names for each rank, which means then two variables instead of one in-game, and I'm not sure it's worth the effort. So I just decided so use the "appelation" as the $Name in my translations, hence the duplicate issue.

**Comment by MjnMixael** [comment]
Due to the upgrades to ranks.tbl, name must be unique as it's used as an identifier in the code instead of the rank's position with the table like it used to be. Alt Name could be a solution here, but that would apply anywhere the Rank Name is displayed. Correct me if I'm wrong, it seems like you just want some kind of distinction between the Rank Name and the Rank Appellation for dialog purposes, which may apply to other languages as well. In that case, I propose `$Title: string` instead of `$Alt Name: string` which would only apply to `$RankTitle` variable replacement. I can add $Alt Name at the same time. But I feel like making this distinction between the rank name and the rank title is justified for French and potentially other languages as well.
