### ISSUE TITLE
Red Alert Mission Chain "Journey from a thousand miles" breaks from RC5 onwards.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5637]
BPC's mission chain from bp-04 to bp-07 breaks at "Frankenstein's Monsters" if the transition between "Wounded Prey" and "Frankenstein's Monsters" is made with a RC5 or higher build. There seems to be some savegame corruption involved: Trying to "restart previous mission" gives the same errors.

Errors are:
Error: Invalid Value for Viewer_obj->type. Expected values are OBJ_SHIP (1) and OBJ_OBSERVER (12), we encountered 8. Please tell a coder.

File: freespace.cpp
Line: 3309

Could not find index 'communications' in type 'object'

stack traceback:
    [C]: ?
    [string "bp2-betty-sct.tbm - On State Start"]:68: in function 'initbetty'
    [string "bp2-betty-sct.tbm - On Frame"]:353: in main chunk

1: Userdata [object]
2: String [communications]

This bug does not occur when the savefile is created using an RC4 or older build.

Steps to reproduce:
Use SkipMeMyMissionYo to skip to bp-04
continue until crash
use SkipMeMyMissionYo to skip to bp-04 using RC4 or lower

notice crash does not occur.

Savefiles are attached for your convenience.

[players.zip](https://github.com/scp-fs2open/fs2open.github.com/files/12749843/players.zip)

Issue appears to be related to the following commit: https://github.com/scp-fs2open/fs2open.github.com/pull/4457

**Comment by Goober5000** [comment]
This bug is caused by the red-alert code trying to determine the wave number of the wing from the previous mission.  Since Alpha 1, 2, and 3 were saved in bp-05, but bp-06 only has a single-fighter wing, it thinks that it's dealing with the third wave of Alpha wing.  This causes it to designate the player as Alpha 3, and then no Alpha 1 data is carried forward to bp-07.  This then causes the game to treat Alpha 1 as nonexistent in bp-07, and the errors that ultimately are displayed are caused by trying to modify a nonexistent ship.
