### ISSUE TITLE
avd_movement::setAVD is the source of many divide by zero issues on coverity

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#5716]
After looking through new and old coverity issues, it turns out many point to this function, specifically the last few lines.

```
void avd_movement::setAVD(float final_position, float total_movement_time, float starting_accleration_time, float ending_acceleration_time, float final_velocity)
{
	//Make sure Pc et al are up-to-date
	this->update();

	Pf = final_position;
	Tf = total_movement_time;
	Tai = starting_accleration_time;
	Taf = ending_acceleration_time;
	Vf = final_velocity;

	if(Tai+Taf >= Tf)
	{
		Tai = Tf;
		Taf = 0.0f;
	}

	if(Tf <= 0.0f)
	{
		Pc = Pi = Pf;
		Vc = Vi = Vf;
		return;
	}

	Pi = Pc;
	Vi = Vc;
	TSi = timestamp();
	
	Vm = (Pf-Pi-0.5f*(Vi*Tai)-0.5f*(Vf*Taf)) / (Tf - 0.5f*Tai - 0.5f*Taf);
	Ai = (Vm-Vi)/Tai;
	Af = (Vf-Vm)/Taf;
}
```

Nothing keeps Tai or Taf to from being 0.0f, and I'm not really clear on how this function works, so I'm wondering what a proper fix for this is.

**Comment by Goober5000** [comment]
I think AVD stands for Acceleration, Velocity, Distance.  This routine is performing calculations for something that accelerates for a period of time, then moves at a constant velocity, then optionally slows down.

The two if() blocks in the middle guard against problems with the denominator, and I *think* they cover all cases.  The first if() checks that the acceleration times are not greater than the total movement time, and if they are, they are modified so that the denominator will be positive or zero.  The second if() guards against the total movement time being negative or zero.

What exactly are the messages generated by Coverity here?

**Comment by JohnAFernandez** [comment]
That Taf can be 0.0.  It's even explicitly set to 0.0f in the first if block.

**Comment by Goober5000** [comment]
Oh - I was so focused on the `Vm = ` line I skipped the lines right below it.

**Comment by JohnAFernandez** [comment]
I forgot to link this issue to the merged pull request.  It should be fixed now.
