### ISSUE TITLE
FR: INI/settings reporting in debug log.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#5900]
The debug log's utility in diagnosing problems can sometimes come from seeing the player's command line flags. As we move more and more things into ingame settings/launcher built .ini files, it might make sense to have the game dump those settings to the log on startup so we don't lose that capability.

**Comment by MjnMixael** [comment]
I looked at this for the last 30 minutes and this is decidedly more complex than just printing the ini file settings. First, just printing the ini isn't enough because these settings can be changed during runtime so you also need to print when the settings are changed. But even more difficult is the fact that the calls from the OptionsManager to pull the settings titles and values has xstr functionality built-in. This is a problem because Options are built at game init but getting display values is not expected until after the xstr system has gone through init. So doing a quick log print as each option is initialized is a no go or you get the xstr int3.

Doing anything more would require a much more in-depth set of work in the OptionsManager code where it serializes and deserializes the values for the ini file. I don't fully understand enough of what's going on in that code to make changes right now. Getting an option key (title) looks to be pretty trivial as that's passed around as an SCP_string reference. But the values themselves are not. The Option.h line 223 is where the real magic happens and probably the best entry point for getting the raw value from the ini, avoiding any xstr nonsense. But you have to deal with the deserializer here and the option key isn't really available until one more function deeper in Option.cpp line 126.

Of course all of that would just be at init and wouldn't necessarily reflect in the log when values are changed. So this really requires a multi-faceted approach and stuff of m!m's OptionManager code. Not impossible but much more than I can currently grasp at the moment.

**Comment by MjnMixael** [comment]
I had a moment of inspiration where I realized this didn't need to happen at the same moment that cmdline printing happened. It could happen after all init.. so I whipped up a PR.
