### ISSUE TITLE
FR: Override the $Randomize particle rotation: flag on a per-effect basis

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5941]
The $Randomize particle rotation flag is awesome, but there's some effects (like Diaspora's exp_nuke and kestrellius's flare effects) that expect particles to not be rotated. Please add a flag to particle_effects where we can set this value for individual tabled effects, overriding whatever default is set by the game_settings flag.

**Comment by Baezon** [comment]
He's almost certainly referring to the [these particle effects](https://wiki.hard-light.net/index.php/Particle_Effects), the ones handled in the `particle` folder.

**Comment by Goober5000** [comment]
Ok, I think I see what this is doing.  The `BeamPiercingEffect` and `ParticleEmitterEffect` types do not have parsing implemented, but these do not appear on the wiki page.  All the ones that do, go through the `ParticleProperties::parse` function.

**Comment by Baezon** [comment]
Yes, those are special cases. I don't think we really need to worry about having this toggle on *every possible particle* of which there are a great many, I think having it be on the main particle effects defined in the typical way using a -part.tbm would be sufficient for now, since that is much simpler to modify and is the great majority of the particle effects people care about.

**Comment by Goober5000** [comment]
Implemented by #5944
