### ISSUE TITLE
Hide key-reset SEXP from FRED

### ISSUE THREAD

**Issue by jlberman** [scp-fs2open/fs2open.github.com#6076]
There is no purpose to key-reset since there's key-reset-multiple.  I get that legacy campaigns still might use it, but it should be hidden from new content.

**Comment by Goober5000** [comment]
The `key-reset` operator very specifically and intentionally works once regardless of the number of repeat iterations.  This is because the training missions have a certain set of operators (messages and Instructor ship goals) that repeat until the player has pressed a certain key, but the key must not be reset for every repeat iteration.

The question is whether modern campaigns would ever use such a technique.  I tend to doubt it, but it's an open question.

We could simply hide the `key-reset` operator as you suggest and force all FREDders to either a) manually enter that operator into the event, or b) implement the behavior using a different technique.

**Comment by jlberman** [comment]
I like option A.  If you want to use key-reset, you're doing it very deliberately.

**Comment by Goober5000** [comment]
Implemented in #6094
