### ISSUE TITLE
Cannot launch Freespace from mission editor on linux (Neither in FRED2, FRED2_Open nor qtFRED)

### ISSUE THREAD

**Issue by topas-rec** [scp-fs2open/fs2open.github.com#6155]
Hey everyone,

I can run Freespace 2 and FS2Open fine on (arch)linux.
FRED2, FRED2_Open and qtFRED also start and interaction works (except some functions in qtFRED, but I think that's because they are not implemented)

When I want to run the game _from the FRED file menu_ it ... well what happens then in detail depends on the editor, but Freespace is never launched.

FRED2: Says `File not found`
![image](https://github.com/scp-fs2open/fs2open.github.com/assets/20391449/2097e22a-41e6-4a92-9bca-b0e908233f05)

FRED2_Open: Says `File not found`
![image](https://github.com/scp-fs2open/fs2open.github.com/assets/20391449/43c52030-14f7-4f3f-af7b-e5d1adef67d2)

qtFRED: Does just nothing

Is there any way to find out more than the given responses from the tools above?
The command line doesn't show any messages when the run command is activated.
I also didn't find anything in the logs.
It would be nice if someone can give me some tips on how to find out more about this.

**Comment by BMagnu** [comment]
How are you launching FRED / qtFRED / FSO?
Through a mod manager like knossos.net?

On a fundamental level, FRED is windows only, so you'd have to run it through wine (and properly configure it).
qtFRED is cross-platform, but not fully implemented yet.
FSO is fully cross-platform, and runs under linux without issue.

My initial reaction is thus: Launching FSO through FRED will not be sensible, as FRED is launched through wine, but FSO should really be launched natively, and FRED can't do that through wine.
So until qtFRED is feature complete, my recommendation would be to, first of all, make sure that all your modding tools are up to date and on a proper version by sourcing them through knossos.net. There is only one up-to-date version of FRED2 (we keep that up-to-date in step with the FSO version), so whatever you have in these two FRED2 tools, they're either identical or one is simply out of date. When using the tools, I'd recommend making the missions with FRED in wine, and then start FSO directly through knossos.net to play and test your mission. If you're working on something larger, using knossos.net to manage mod development could also be helpful.

**Comment by tv-flhs** [comment]
If you put a file called `start_fs2.bat` in the same folder as `fred2_open_....exe` and put the following line inside, it *might* work:
```
start /unix /path/to/your/fs2_open_file -and_the -necessary_parameters
```
You should be able to find the necessary path and parameters in your `fs2_open.log`.

**Comment by topas-rec** [comment]
> How are you launching FRED / qtFRED / FSO?
> Through a mod manager like knossos.net?

I start
* FRED2 (executable from the original (retail), not modded game installation folder) using wine
* FRED2Open (downloaded Windows release build from here, since FRED2Open is not shipped through Knossos.NET in Linux, only on Windows)
* qtFRED (build from source) natively from the build directory

No matter which one I launch, I use the Freespace 2 installation folder as working directory.

For playing the game using FSO and installing mods I use Knossos.NET.

> Launching FSO through FRED will not be sensible, as FRED is launched through wine, but FSO should really be launched natively, and FRED can't do that through wine.

This idea was growing in my mind, too, but I wasn't sure.
Now that's clear.

> I'd recommend making the missions with FRED in wine, and then start FSO directly through knossos.net to play and test your mission

That's okay for me. Thanks.
Can you explain or link an explanation about how to find/start my mission made in FRED2 from FSO, when FSO is launched through Knossos?
Where to put the mission file (`.fs2`) at?

**Comment by topas-rec** [comment]
> /path/to/your/fs2_open_file

Thanks.
Is this the FRED2Open executable?

**Comment by topas-rec** [comment]
> Where to put the mission file (`.fs2`) at?

I guess in the data folder under missions but not directly in the retail or FSO folder, but in a mod folder. Luckily I already created a (still local only) mod which I could use for this. I'll try that.

Partly explained here: https://wiki.hard-light.net/index.php/Tutorial_-_How_to_make_a_mod_from_scratch#Example_2:_VP_files.2C_missions.2C_and_Making_the_Seraphim_flyable

**Comment by tv-flhs** [comment]
Well, guess I took too long to type this out. :P Oh, well, at least it's here for further reference.

> Can you explain or link an explanation about how to find/start my mission made in FRED2 from FSO, when FSO is launched through Knossos?
> Where to put the mission file (.fs2) at?

The easiest solution would be to create a new mod in Knossos.NET and put your mission files inside that. First, you'll have to make sure you're logged in with a Nebula account since the Develop tab apparently doesn't work without one. Next, go to the Develop tab, click `Create New Mod`, fill out the fields (the name and ID are required and "Retail FS2" should be the parent mod) and select the mod in the list. If the right side of the window remains empty, restart Knossos.NET and select the mod again. You should see several new tabs and buttons.
To make the mod functional, go to the FSO Settings tab, select the FSO version you want to work with (probably the latest stable) and click `Save changes`, afterwards switch to the Packages tab and click `+Package`, give it a name (the name doesn't matter much but should only use ASCII characters) and then click `Open Folder`. You should now see the package folder inside your mod directory. Open the `data` folder, create a new `missions` subfolder and save your `.fs2` files there.
Once you've done all that, you should be able to launch FSO through the `Play` and `Debug` buttons in Knossos.NET. In the main hall, go to the tech room, switch to the mission simulator, make sure single missions are selected and you should be able to play your mission.
I think there's a commandline flag to skip these steps and go straight into the mission as well.

**Comment by BMagnu** [comment]
I see.
I would strongly recommend to not use the old FRED2 that shipped with retail. It's old and can't use all the new features we've added since then.
If you just want to quickly test your missions, you can look for your FS2 root folder (the one in your knossos library that contains the vp files). In there, look for the `data/missions` directory. data will probably already exists, while you'll probbaly have to create its missions subdirectory. Save the mission in there, and it'll show up in the mission simulator.
If you want to make a proper mod, you can set that up in the knossos.net develop tab. That creates a directory for your mod specifically. In that case, creating and using `data/missions` within your mod directory is the way to go.

**Comment by BMagnu** [comment]
On that note, this has given us the push to integrate a function to automatically download FRED2_open and set it up in wine in knossos.net under linux.

**Comment by topas-rec** [comment]
Launching it through the tech room works - when circumventing an [issue with the mission file not shown in my personally created mod](https://github.com/scp-fs2open/fs2open.github.com/issues/6158) - thank you.

**Comment by topas-rec** [comment]
> On that note, this has given us the push to integrate a function to automatically download FRED2_open and set it up in wine in knossos.net under linux.

That's great. I also thought that would be nice.

This is my current command for that.
`WINEPREFIX="/home/my/special/prefix/wineprefix" wine "/path/to/fred2_open_24_0_1_x64_AVX.exe"`
Could you make the wineprefix editable as an option? So use the default prefix, but let one setup a specific one.
