### ISSUE TITLE
FSO 24.0.2 crashes with "unrecognized command line parameter -spec_exp".

### ISSUE THREAD

**Issue by AntonieS** [scp-fs2open/fs2open.github.com#6176]
Subj.

Win7 Ult SP1 x64

Later on this machine was wxlauncher and FSO version 3.8.1 - and no problem.

Now I try new version and became 2 errors at start
"unrecognized command line parameter -spec_exp"
and
"unrecognized command line parameter -ogl_spec"

and FSO crashes.

Please help. %)))

**Comment by The-E** [comment]
Those two popups at the start just tell you that those two commandline parameters were not recognized by the engine (because they've been removed in a later version, see [the commandline reference](https://wiki.hard-light.net/index.php/Command-Line_Reference) for details).

Do note that wxLauncher is no longer fully supported. The preferred way to start and manage FSO these days is via [knossos.net](https://knossosnet.github.io/Knossos-Release-Page/), however I am unsure whether that is supported on Windows 7 - given that noone, not even Microsoft, offers support for an OS that old, I strongly recommend upgrading.

**Comment by AntonieS** [comment]
I don't use wxlauncher anymore.
I'm try to launch game from Knossos.NET 1.1.0 and FSO crashes.

Event name: BEX64
Application: fs2_open_24_0_2_x64_AVX.exe
Name of module with error:	StackHash_1dc2

**Comment by AntonieS** [comment]
Knossos.NET works itself fine.

**Comment by The-E** [comment]
Do you have a CPU that supports the AVX instruction set? If not, it might be safer to use an SSE2 build instead.

Also note that, at least according to [this crash report found on the internet](https://serverfault.com/questions/718543/what-does-event-bex64-mean), your OS might not support AVX even if your CPU does.

**Comment by AntonieS** [comment]
My CPU does support AVX and AVX2.
I try with SSE version - same thing

BEX64
fs2_open_24_0_2_x64_SSE2.exe
24.0.2.0

664836a9

StackHash_1dc2

**Comment by AntonieS** [comment]
Thanks for answers. The problem is solved.
Guys, in FSO engine package you're using an absolutely old OpenAL engine library. I have replace it with new and all works fine.
Look at this:
https://openal-soft.org/#download
https://github.com/kcat/openal-soft
https://github.com/ThreeDeeJay/dsoal/releases

and this (sound bekame absolutely fantastic):

https://www.youtube.com/watch?v=VCXQp7swp5k
https://mega.nz/file/lbR21RyQ#RXXx8YRpdd_JkrBc0duidYWOkJklRp-wzki_hLnq_R4

Thanks for FSO - it a great work. %)))

**Comment by Goober5000** [comment]
@AntonieS We have now updated OpenAL in the collection of SCP prebuilt libraries.  Thanks for letting us know :)
https://github.com/scp-fs2open/scp-prebuilt/pull/15

**Comment by AntonieS** [comment]
My pleasure. %)))
