### ISSUE TITLE
Bug: Warp_Flash broken on nightly builds past 2024.07.02

### ISSUE THREAD

**Issue by skdKitsune** [scp-fs2open/fs2open.github.com#6263]
Starting with nightly 2024.07.03, the warp flash effect does not show up on some pc configurations.

https://fsnebula.org/log/669ecad1c241ad89f80010bb - log for 2024.07.02 (the last nightly that works)

https://fsnebula.org/log/669eaca0d9fd840ff60010bd - log for 2024.07.19

**Comment by MjnMixael** [comment]
I tried to track this down but was unable to reproduce the issue. It's clearly tied to #6214 where, notably, Warp Flash used to require a game restart. I removed that requirement because my testing showed (and still shows) it shouldn't be necessary. It is possible I missed something, though, so I did additional testing on a fresh Release build to make sure no code was optimized out which has caused issues with In Game Options in the past. Here is what I said on Discord after doing the testing.

> I built a fresh Release build (that takes upwards of 20 minutes on my shitty work laptop) and launched the MediaVPs, attaching debugger. I set a watch on `Fireball_warp_flash`, the boolean the option toggles. Break when the value changes. I also set a breakpoint where that variable is checked during the warpout rendering to decide if a warp flash should be drawn.
> 
> Changing the option always correctly set the boolean. Didn't matter if I did this during a mission or not. This ruled out the usual issue I've had in the past where Release builds had optimized out the code that actually set the variable.
> 
> I did in-mission testing of both the player warpout and NPC. I didn't think they used different code paths but I wanted to be sure. Each warpout showed the `Fireball_warp_flash` boolean still being set to what I expected it to and the warp flash drew when it was `true`.
> 
> Finally I verified one other wrinkle; that the warp flash bitmap was properly loaded. I theorized that perhaps if `Fireball_warp_flash` was false at game start or during mission load then the bitmap would not be loaded which would cause rendering to be skipped. However, this proved not to be the case as even if warp flash is disabled the bitmap is still loaded into bmpman and the ID correctly set in the fireball data.
> 
> This was all in addition to visual verification that the warp flash was, in fact, visible.
> 
> Outside of that, I'm not sure what else to test. That feels pretty thorough, but maybe I missed something?

Beyond this I'm not sure how else to try and track this down without being able to reproduce it.

**Comment by zathras5** [comment]
I hope this hasn't been abandoned yet? Maybe the game thinks that warp flash is disabled since the build from Nightly: 03 July 2024. I launched the last working build from 2024.07.02, warpglow01 and warpball01 work fine. Then I disabled the warp flash, restarted the game, I saw that warpglow01 was working, but without the flash effect and warpball01. The same thing happens in all the latest builds, warpglow01 loads but the flash effect itself is disabled.

**Comment by wookieejedi** [comment]
So with the in-game options you have set Warp Flash to Enabled, then saved correct? Then you restarted the game, double checked that warp flash was still enabled, then went into a mission and did not see a warp flash?

**Comment by skdKitsune** [comment]
> So with the in-game options you have set Warp Flash to Enabled, then saved correct? Then you restarted the game, double checked that warp flash was still enabled, then went into a mission and did not see a warp flash?

I've tried pretty much everything apart from completely uninstalling FS2 and every single mod. Every mod is affected by this.
Tried disabling the warp flash, enabling it, enabling it via command line with F3 menu disabled/enabled and vice versa.
Every single time restarting the game. The issue persists since I opened this report. 
(even did a complete Windows reinstall, which wiped my Appdata folder, though that wasn't part of my troubleshooting process)

**Comment by MjnMixael** [comment]
Just to be clear, is everyone trying this with the MediaVPs loaded? Warpflash is hardcoded to require a file named "warpball01" which retail Freespace does not include. You will not see a flash in retail or mods that don't include that file.

**Comment by skdKitsune** [comment]
> Just to be clear, is everyone trying this with the MediaVPs loaded? Warpflash is hardcoded to require a file named "warpball01" which retail Freespace does not include. You will not see a flash in retail or mods that don't include that file.

Yep, happens on the mediavps and mods that require mvps to run
