### ISSUE TITLE
When loading any BP2-act 3 mission with RC5: Ship 'Falcata 1' is an illegal type to be in a wing.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#6366]
![afbeelding](https://github.com/user-attachments/assets/c8c53547-7cd6-47bd-930b-f7b68610d18e)

When opening any Act 3 mission with the RC builds for 24.2 I get this error.
Notably, Falcata 1 is an UEF Ainsarri. This ship is a fighter. 
Also of note is that removing the "Stealth" flag from the ship's flag also removes the errors.

**Comment by MoerasGrizzly** [comment]
After a bit of digging I suspect this commit: https://github.com/scp-fs2open/fs2open.github.com/pull/5998

**Comment by Baezon** [comment]
Basically the ainsarri has both "fighter", its ship type, and "stealth", to make it stealthy (in favor of $Stealth, which was deprecated). But since "stealth" is also a ship type, it now overrides it's previous "fighter" status, breaking all sorts of stuff because the mod expects it to be a fighter.

**Comment by Goober5000** [comment]
Well, this is strange.  That's definitely the root cause, but it'll be tricky to thread the needle.

**Comment by Goober5000** [comment]
I don't think that would have helped in this case.  The design issue is Volition's original choice to indicate the ship class with a ship *flag*, and a secondary issue is WMC's later misinterpretation of the stealth flag for a nonexistent stealth ship class.
