### ISSUE TITLE
FRED bug: "Set Head ANIs using Messages.tbl" button doesn't set the Command head correctly

### ISSUE THREAD

**Issue by jlberman** [scp-fs2open/fs2open.github.com#6379]
How to reproduce: set a Command persona in mission settings.

Create a mission with a message sent by #Command.

Hit "set head anis using messages.tbl".

Command head is not set in the events manager.

**Comment by Goober5000** [comment]
Hmm, looking at my comments in that function, I see exactly what's happening.  That function specifically *only* sets the heads for *wingman* personas.  This is because, in my experience, many missions use the "Large Ship" or "Terran Command" persona for multiple ships with different heads, and would not want all of those ships to be changed to the same head.

Obviously in this siutation there is a case to be made for setting heads for all personas.  I could add some kind of selector that would allow the FREDder to control which category of personas this applied to.

**Comment by jlberman** [comment]
Agreed - that would be great
//
