### ISSUE TITLE
FPS drop using MSAA for Inferno

### ISSUE THREAD

**Issue by Fusionblaster** [scp-fs2open/fs2open.github.com#6401]
I experienced a massive FPS drop (>60 FPS to around 5 FPS) when playing the dev version of Inferno Nostos with the Multi Sample Anti Aliasing option turned to 16 samples. I am playing with max graphical options, and at 8 samples or less the game plays fine with no apparent FPS drop, but at 16 samples for Nostos and Nostos alone, the framerate for any and all missions drastically drops. This issue appears to affect no other mod, as I was able to play FSPort and FS2 MVPs at 16 samples without issue. As of earlier this month, Nostos had run fine at the 16 sample mark, and I have done nothing other than keep FSOpen and the Nostos repo updated that could be responsible for the change.

**Comment by BMagnu** [comment]
It is highly likely that this is simply a small performance fluctuation from either more textures loaded, or a driver change, or whatever. Also, double check that your other test cases actually _run_ with MSAAx16, as between the ingame options, knossos.net settings and the command line, it's possible the option is overwritten without you noticing it.

A steep performance drop as you describe is at least to be expected with MSAA if it reaches the bottleneck of your GPU. Due to peculiarities of FSO's renderer, what's actually bottlenecking here is GPU memory bandwidth (i.e. how much VRAM the GPU can access at once). If that reaches saturation, you will notice a very sudden and very drastic reduction in performance, as you describe. In fact, MSAAx16 is heavy enough that I would expect all but the highest end GPUs to hit this saturation in most mods (my RTX2070 certainly does). And as memory bandwidth is the culprit here, some rather intuitively unconnected things can affect performance. How many high res textures may be loaded / displayed, if a video is playing in the background, if the VRAM is generally full from other applications, etc.

**Comment by Fusionblaster** [comment]
I checked with the current MVPs and did suffer the same issue testing 16x MSAA on To Destroy or Not to Destroy. I am admittedly confused why this would end up happening when I'm running a 4090 in an MSI Titan 18HX(whose specs are ludicrously overbuilt for a gaming laptop).

**Comment by BMagnu** [comment]
It's to do with the specific type of renderer FSO uses (keyword here is "deferred rendering").
This type of renderer is famously "incompatible" with MSAA in principle.
FSO uses something called "depth aware multi-sample anti-aliasing" to get around some issues resulting from deferred rendering and MSAA in combination. This technique is computationally much closer to traditional MSAA (as opposed to other MSAA techniques for deferred rendering). The memory bandwidth however is increased by a factor of 5 compared to normal MSAA (plus, I'd speculate that "normal MSAA" is more optimized in hardware). However, memory bandwidth from shaders to VRAM is "free" until you hit this saturation, at which point everything grinds to a halt. And x16 simply pushes basically all GPU's to this point.

The real takeaway from this is that to get performance like traditional MSAA, we use a fairly special technique that trades performance for memory bandwidth, and x16 is simply so far on the scale that this tradeoff starts to backfire for basically all GPUs.

There's a point to be made to simply remove x16 MSAA from the list. I admittedly didn't test this far when implementing it, since my GPU is also far from top-end these days, so I wasn't know how far it could be pushed to. Tbh, I'll have to think about whether or not to just limit to x8...
