### ISSUE TITLE
FSO needs a user-friendly way to set the connection speed

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#6402]
See this thread by r4r1t3:
https://www.hard-light.net/forums/index.php?topic=99430.0

For new users who haven't set the connection speed, it would be good to proceed with a sensible default so that gameplay isn't brought to a screeching halt.  ~~We should also add an option to in the in-game options screen~~ (but see below).

I seem to recall that the connection speed may not actually matter at all these days, so we may not need an option at all, but I'll double check with @notimaginative.

**Comment by notimaginative** [comment]
After a quick look at the code `NetworkConnection` is obsolete and no longer referenced anywhere. It's replaced by a `Psnet_connection` variable which defaults to LAN. However it's only purpose now is to change the default object update value for a player if it's set to dialup, and that's easily done in-game already. So `Psnet_connection` could really just be removed.

`ConnectionSpeed` defaults to Fast on Linux/Mac, and unset on Windows, for some reason. So that ifdef just needs to be removed so it defaults to Fast on all platforms (`multiutil.cpp:2939`). That option should probably stay, even though it's only for UI info purposes and doesn't alter the behavior of the game in any way.

**Comment by Goober5000** [comment]
Addendum: I've been told the error popup associated with ConnectionSpeed can be removed, as long as the rest of the UI/setting code is left

**Comment by Goober5000** [comment]
Fixed by #6412
