### ISSUE TITLE
`Player` hook variable not available in "On State Start" hook

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#6408]
The main hall specifically is what I'm concerned about, since I suspect it would work in a mission. But I'd really like to do some stuff dependent on the currently active main hall. But the Player hook variable is a little weird, and I'm not sure of all the implications for such a broad hook, so I'm not confident doing it myself.

**Comment by Goober5000** [comment]
The `hv.Player` script variable is always set to be `Player_obj`, i.e. the in-game object corresponding to the player's ship.  So that would not be valid while the main hall is active.  I assume you would want to call the `ba.getCurrentPlayer()` script function instead.

I'm pretty sure that there is a valid player at all times once the game gets past the pilot select screen, so as long as you aren't on that screen, `ba.getCurrentPlayer()` should return a valid player.

**Comment by Baezon** [comment]
That is confusing (`hv.Player` is not a `player` type...), but understandable (and works).
