### ISSUE TITLE
Campaign files getting corrupted.

### ISSUE THREAD

**Issue by PhantomHoover** [scp-fs2open/fs2open.github.com#717]
This is a pretty old install that's seen several mod and FSO versions. On selecting a lot of campaigns I get an ingame error saying that the campaign save file isn't compatible with the current mod (but the campaign is then playable); on others there's no error message when selected but the little marker doesn't appear next to its name, I get the error on exiting to the mainhall and I stay on whatever campaign I had previously selected; the log indicates that the files are invalid. Attached are two of the corrupted campaign files.
[fucked.zip](https://github.com/scp-fs2open/fs2open.github.com/files/394922/fucked.zip)

**Comment by asarium** [comment]
I can reproduce this. When I try to select WiH Part 1 the pilot campaign save file faild to be loaded. Stepping through it with a debugger shows that in csg.cpp:436, for some reason, the entry for GTI Bretonia is invalid (index is -1).

**Comment by PhantomHoover** [comment]
That's a mod issue, then, BP recently made an update that removed the GTI Bretonia. The crashing vanilla FS2 campaign file may also be due to interaction with FSBlue after the same update.

**Comment by niffiwan** [comment]
thanks for confirming that BP removed the GTI Bretonia, I had a suspicion that modpacks changing could cause an issue like this. Fixing it might be as simple as treating this error as non fatal. Just need to think through that would be OK in all situations.

**Comment by Goober5000** [comment]
I would imagine this should be treated as non-fatal.  It's non-fatal if a modpack adds a ship, isn't it?

**Comment by niffiwan** [comment]
yes it is

**Comment by Goober5000** [comment]
Is the Bretonia the only ship that was removed?  I'm wondering if there is a good heuristic to use, e.g. require that at least 95% of the ships be present.

(At least *some* ships should be required to be present, otherwise there would be nothing preventing someone from loading a campaign with a totally different mod.)

**Comment by MageKing17** [comment]
> otherwise there would be nothing preventing someone from loading a campaign with a totally different mod

...Do we care?

**Comment by Goober5000** [comment]
I think we should.  It's another layer of safeguarding against unexpected bugs or posts to the help forums.

In other words, the error should be non-fatal up until the arbitrary threshold is crossed.

**Comment by FSCyborg** [comment]
Maybe the best solution is to have Knossos write a timestamp for the last time the mod is verified that FSO can read in the mod.json?  If the campaign was last opened after that timestamp and is missing files, throw a warning.  If the campaign was last opened before that timestamp and is missing files, ignore it, since Knossos just verified everything.

**Comment by MageKing17** [comment]
The error was already made non-fatal back in #1787.
