### ISSUE TITLE
[PBR] Performance issues when firing laser weapons

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#787]
I noticed that whenever I fire primary weapons my FPS drops from 60 to ~40. I tracked the first occurrence of this issue to the nightly when the PBR changes were merged.

If it helps, my GPU is an AMD R9 380.

**Comment by asarium** [comment]
Per @The-E's suggestion I tried lowering the lighting level in the options and that made the issue disappear. Ever lighting value of 4 or above shows the issue so it's definitely lighting related.

**Comment by SamuelCho** [comment]
Any difference when you turn off deferred lighting or disable post processing?

**Comment by asarium** [comment]
Disabling either post processing or deferred lighting fixes the issues.

**Comment by chief1983** [comment]
Any more on this?  Seems like a serious issue given how often laser weapons fire.

**Comment by asarium** [comment]
I don't encounter this issue anymore but I also upgraded my GPU so that might have fixed the issues somehow.

**Comment by EatThePath** [comment]
Even if this issue is still present, it seems to me that it is really just a case of an optional graphics feature being expensive. Dynamic lights can be disabled as pointed out here, and as I understand it dynamic lights for weapons besides beams were a new thing with deferred, so it's hard to say they're being inordinately expensive since there's nothing to compare them to. Is there reason to think there's a deeper problem here than just needing to turn down lighting detail if you have a card that can't handle that many lights?

**Comment by JohnAFernandez** [comment]
Putting this in low priority since it does not have a lot of reports since it was first created.

**Comment by EatThePath** [comment]
Given the age and nature of this issue I'm closing it. Our periodic performance testing should turn up any current issues with laser lighting if they still persist.
