### ISSUE TITLE
Padlock view text doesn't show up in certain resolutions

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#865]
When you're in padlock (looking left, right, up, or rear) there's supposed to be some text up at the top that displays which direction you are facing. The external and chase cam text shows up in the same spot.

However, in certain resolutions the text is not visible at all, presumably its too far above the visible area. 16:9 resolutions seem OK, 4:3 resolutions don't show it.

**Comment by Yarn366** [comment]
I tried 1366x768, 1600x900, and 2263x1273 (all 16:9) and the text never appeared. What resolutions work for you?

**Comment by z64555** [comment]
Shows up on 1280x960 (4:3), 1280x720(16:9), 1280x768 (5:3), 1280x800 (16:10), 1280x1024(5:4).

And it seems to show up in 1366x768 as well? All of these tests were in windowed mode, however. I'll check these again later today using fullscreen and fullscreen window.

**Comment by Yarn366** [comment]
I did some more testing and found that the TrueType merge is when this bug was introduced. Resolution doesn't appear to have any effect here. Before I commented, you must have tested 16:9 resolutions in 3.7.4 and 4:3 resolutions in a recent build, which would explain your result.

Again, it's the TrueType merge that made the text disappear.

**Comment by Yarn366** [comment]
PR #959 fixes this issue.
