### ISSUE TITLE
Mission (and table) text data is not a C-string

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#933]
I have been investigating why the unit tests fail with a valgrind error which lead me to `stristr` which reads out of the boundaries of the passed string. @rtoijala already described this issue in #924. The same issue is also detected by AddressSanitizer.

I found that `process_raw_file_text` writes `EOF_CHAR` at the end of the parsed strings but not a null character which means that, as far as I can tell, the string in the parse code is not a C-string and may not be used by the various string manipulation functions. Since not using those functions is not really an option the parse code has to be modified so that a null character is appended to the processed text.

**Comment by rtoijala** [comment]
This is not yet fixed. `allocate_mission_text` only zeroes `Mission_text` and `Mission_raw_text` when the new size is larger than the old size. This means that they are still not C-strings when the new size is larger.

If you uncomment the test `missing_end_multi_text` in `test/src/menuui/test_intel_parse.cpp` and run the unit tests with `--gtest_shuffle --gtest_repeat`, it fails always (which is my mistake), but it sometimes fails with `Intel_info_size == 2` and sometimes with `Intel_info_size ==3` because of this issue.

Copying the memset calls in `allocate_mission_text` into the `if (size <= Mission_text_size)` block fixes the issue, at least for me.

**Comment by asarium** [comment]
You're right, feel free to submit a PR with the `memsets` in the right location.

**Comment by rtoijala** [comment]
Would you mind doing it? I'm quite busy today and tomorrow.
